### ISSUE TITLE
parallel

### ISSUE THREAD

**Issue by aliafshany** [MortezaBashsiz/CFScanner#1]
Hello there
Unfortunately, i wasn't able to install Parallel library.

would you please use a new library instead?
here is the error i encounter while installing Parallel on macbook pro ventura m2

<img width="762" alt="image" src="https://user-images.githubusercontent.com/40741745/213903932-15694d6e-961e-4ad0-bfa0-0fad97cf8440.png">

**Comment by MortezaBashsiz** [comment]
Hi
This is not python
simply install parallel in your Mac with package manager
For example, If you had Ubuntu you could do it with
`apt install parallel`
