### ISSUE TITLE
All IP's FAILED. The result set is empty!

### ISSUE THREAD

**Issue by Saya47** [MortezaBashsiz/CFScanner#10]
As the title says. That's impossible. What could be the issue?

**Comment by MortezaBashsiz** [comment]
Could you plz give me more details or output example?

**Comment by Saya47** [comment]
Hello! Of course, here's what I see on my Terminal:
![image](https://user-images.githubusercontent.com/35542834/216988537-3cfce678-ffc3-4a85-af55-389414deb0d2.png)
And the result is empty:
![image](https://user-images.githubusercontent.com/35542834/216988666-ecde144a-b027-4de7-b3f7-7ca4015e0011.png)

**Comment by MortezaBashsiz** [comment]
Is it failed for all IPs?
Is your Internet behind Irancell?

**Comment by Saya47** [comment]
Yes All IP's failed. I ran the script again to make sure, first time around I ran it with 16 jobs now ran it with 4 jobs:
![image](https://user-images.githubusercontent.com/35542834/217154784-df5ed412-d117-4103-98e7-6543f0b6c01f.png)
My ISP is TCI (Mokhaberat).

**Comment by MortezaBashsiz** [comment]
Then I can not do anything 
This is not from script
Something is wrong there
I am writing another script which will scan ips much better
you can wait for it or run it with another internet provider

**Comment by Saya47** [comment]
OK. Thanks very much.
