### ISSUE TITLE
CF IP List

### ISSUE THREAD

**Issue by A5DkjGQUZx** [MortezaBashsiz/CFScanner#102]
Why don't u use this list? https://www.cloudflare.com/ips/

**Comment by A5DkjGQUZx** [comment]
**DEFINITIVE** ips-v4 list, auto updated by CF: (https://www.cloudflare.com/ips-v4)
**DEFINITIVE** ips-v4 list, auto updated by CF: (https://www.cloudflare.com/ips-v6)

**Comment by MortezaBashsiz** [comment]
Because they are only whitelisted IPs
I use CF IPs by BGP ASN

**Comment by A5DkjGQUZx** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Mz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Mz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#0563C1" vlink="#954F72">



Cloud Flare Range IP | SUBNET | Number of IPS
-- | -- | --
173.245.48.0/20 | 12 | 4,094
103.21.244.0/22 | 10 | 1,022
103.22.200.0/22 | 10 | 1,022
103.31.4.0/22 | 10 | 1,022
141.101.64.0/18 | 14 | 16,382
108.162.192.0/18 | 14 | 16,382
190.93.240.0/20 | 12 | 4,094
188.114.96.0/20 | 12 | 4,094
197.234.240.0/22 | 10 | 1,022
198.41.128.0/17 | 15 | 32,766
162.158.0.0/15 | 17 | 131,070
104.16.0.0/13 | 19 | 524,286
104.24.0.0/14 | 18 | 262,142
172.64.0.0/13 | 19 | 524,286
131.0.72.0/22 | 10 | 1,022
Total |   | 1,524,706



</body>

</html>

**Comment by A5DkjGQUZx** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Mz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Mz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



cf.local.iplist Range IP | SUBNET | Number of IPS
-- | -- | --
23.227.37.0/24 | 8 | 254
23.227.38.0/23 | 9 | 510
23.227.60.0/24 | 8 | 254
64.68.192.0/24 | 8 | 254
65.110.63.0/24 | 8 | 254
66.235.200.0/24 | 8 | 254
68.67.65.0/24 | 8 | 254
91.234.214.0/24 | 8 | 254
103.21.244.0/24 | 8 | 254
103.22.201.0/24 | 8 | 254
103.22.202.0/23 | 9 | 510
103.81.228.0/24 | 8 | 254
104.16.0.0/13 | 19 | 524,286
104.24.0.0/14 | 18 | 262,142
104.28.0.0/15 | 17 | 131,070
104.30.1.0/24 | 8 | 254
104.30.2.0/23 | 9 | 510
104.30.4.0/22 | 10 | 1,022
104.30.8.0/21 | 11 | 2,046
104.30.16.0/20 | 12 | 4,094
104.30.32.0/19 | 13 | 8,190
104.30.64.0/18 | 14 | 16,382
104.30.128.0/17 | 15 | 32,766
104.31.0.0/16 | 16 | 65,534
108.162.192.0/20 | 12 | 4,094
108.162.210.0/23 | 9 | 510
108.162.212.0/23 | 9 | 510
108.162.216.0/23 | 9 | 510
108.162.218.0/24 | 8 | 254
108.162.235.0/24 | 8 | 254
108.162.236.0/22 | 10 | 1,022
108.162.240.0/21 | 11 | 2,046
108.162.248.0/23 | 9 | 510
108.162.250.0/24 | 8 | 254
108.162.255.0/24 | 8 | 254
141.101.65.0/24 | 8 | 254
141.101.66.0/23 | 9 | 510
141.101.68.0/22 | 10 | 1,022
141.101.72.0/22 | 10 | 1,022
141.101.76.0/23 | 9 | 510
141.101.82.0/23 | 9 | 510
141.101.84.0/22 | 10 | 1,022
141.101.90.0/24 | 8 | 254
141.101.92.0/22 | 10 | 1,022
141.101.96.0/21 | 11 | 2,046
141.101.106.0/23 | 9 | 510
141.101.108.0/23 | 9 | 510
141.101.110.0/24 | 8 | 254
141.101.112.0/20 | 12 | 4,094
162.158.0.0/22 | 10 | 1,022
162.158.4.0/23 | 9 | 510
162.158.8.0/21 | 11 | 2,046
162.158.16.0/20 | 12 | 4,094
162.158.32.0/22 | 10 | 1,022
162.158.36.0/23 | 9 | 510
162.158.38.0/24 | 8 | 254
162.158.40.0/21 | 11 | 2,046
162.158.48.0/24 | 8 | 254
162.158.51.0/24 | 8 | 254
162.158.52.0/22 | 10 | 1,022
162.158.56.0/22 | 10 | 1,022
162.158.60.0/24 | 8 | 254
162.158.62.0/23 | 9 | 510
162.158.72.0/21 | 11 | 2,046
162.158.80.0/23 | 9 | 510
162.158.82.0/24 | 8 | 254
162.158.84.0/22 | 10 | 1,022
162.158.88.0/21 | 11 | 2,046
162.158.96.0/21 | 11 | 2,046
162.158.108.0/22 | 10 | 1,022
162.158.112.0/23 | 9 | 510
162.158.114.0/24 | 8 | 254
162.158.117.0/24 | 8 | 254
162.158.118.0/23 | 9 | 510
162.158.124.0/22 | 10 | 1,022
162.158.128.0/19 | 13 | 8,190
162.158.160.0/20 | 12 | 4,094
162.158.176.0/24 | 8 | 254
162.158.178.0/23 | 9 | 510
162.158.180.0/22 | 10 | 1,022
162.158.184.0/22 | 10 | 1,022
162.158.191.0/24 | 8 | 254
162.158.192.0/22 | 10 | 1,022
162.158.196.0/24 | 8 | 254
162.158.198.0/23 | 9 | 510
162.158.200.0/21 | 11 | 2,046
162.158.208.0/22 | 10 | 1,022
162.158.212.0/24 | 8 | 254
162.158.214.0/23 | 9 | 510
162.158.216.0/21 | 11 | 2,046
162.158.224.0/20 | 12 | 4,094
162.158.240.0/21 | 11 | 2,046
162.158.248.0/22 | 10 | 1,022
162.158.253.0/24 | 8 | 254
162.158.255.0/24 | 8 | 254
162.159.0.0/18 | 14 | 16,382
162.159.64.0/21 | 11 | 2,046
162.159.72.0/22 | 10 | 1,022
162.159.76.0/23 | 9 | 510
162.159.78.0/24 | 8 | 254
162.159.128.0/17 | 15 | 32,766
162.251.82.0/24 | 8 | 254
172.64.0.0/15 | 17 | 131,070
172.66.0.0/22 | 10 | 1,022
172.66.40.0/21 | 11 | 2,046
172.67.0.0/16 | 16 | 65,534
172.68.0.0/19 | 13 | 8,190
172.68.32.0/21 | 11 | 2,046
172.68.40.0/22 | 10 | 1,022
172.68.45.0/24 | 8 | 254
172.68.46.0/23 | 9 | 510
172.68.48.0/20 | 12 | 4,094
172.68.64.0/20 | 12 | 4,094
172.68.80.0/23 | 9 | 510
172.68.83.0/24 | 8 | 254
172.68.84.0/22 | 10 | 1,022
172.68.88.0/21 | 11 | 2,046
172.68.96.0/20 | 12 | 4,094
172.68.112.0/21 | 11 | 2,046
172.68.120.0/23 | 9 | 510
172.68.123.0/24 | 8 | 254
172.68.124.0/22 | 10 | 1,022
172.68.128.0/21 | 11 | 2,046
172.68.136.0/22 | 10 | 1,022
172.68.140.0/23 | 9 | 510
172.68.142.0/24 | 8 | 254
172.68.144.0/21 | 11 | 2,046
172.68.152.0/22 | 10 | 1,022
172.68.161.0/24 | 8 | 254
172.68.162.0/23 | 9 | 510
172.68.164.0/22 | 10 | 1,022
172.68.168.0/21 | 11 | 2,046
172.68.176.0/23 | 9 | 510
172.68.179.0/24 | 8 | 254
172.68.180.0/22 | 10 | 1,022
172.68.184.0/21 | 11 | 2,046
172.68.196.0/22 | 10 | 1,022
172.68.200.0/21 | 11 | 2,046
172.68.208.0/21 | 11 | 2,046
172.68.217.0/24 | 8 | 254
172.68.218.0/23 | 9 | 510
172.68.220.0/22 | 10 | 1,022
172.68.224.0/20 | 12 | 4,094
172.68.240.0/21 | 11 | 2,046
172.68.248.0/22 | 10 | 1,022
172.68.252.0/23 | 9 | 510
172.68.255.0/24 | 8 | 254
172.69.0.0/20 | 12 | 4,094
172.69.16.0/24 | 8 | 254
172.69.18.0/23 | 9 | 510
172.69.20.0/22 | 10 | 1,022
172.69.32.0/20 | 12 | 4,094
172.69.48.0/24 | 8 | 254
172.69.52.0/22 | 10 | 1,022
172.69.56.0/21 | 11 | 2,046
172.69.64.0/22 | 10 | 1,022
172.69.72.0/21 | 11 | 2,046
172.69.80.0/20 | 12 | 4,094
172.69.96.0/21 | 11 | 2,046
172.69.105.0/24 | 8 | 254
172.69.106.0/23 | 9 | 510
172.69.108.0/22 | 10 | 1,022
172.69.112.0/21 | 11 | 2,046
172.69.124.0/22 | 10 | 1,022
172.69.128.0/20 | 12 | 4,094
172.69.144.0/21 | 11 | 2,046
172.69.156.0/22 | 10 | 1,022
172.69.160.0/19 | 13 | 8,190
172.69.192.0/20 | 12 | 4,094
172.69.208.0/24 | 8 | 254
172.69.210.0/23 | 9 | 510
172.69.212.0/22 | 10 | 1,022
172.69.216.0/21 | 11 | 2,046
172.69.224.0/23 | 9 | 510
172.69.227.0/24 | 8 | 254
172.69.228.0/22 | 10 | 1,022
172.69.232.0/21 | 11 | 2,046
172.69.240.0/21 | 11 | 2,046
172.69.248.0/24 | 8 | 254
172.69.250.0/23 | 9 | 510
172.69.252.0/22 | 10 | 1,022
172.70.32.0/20 | 12 | 4,094
172.70.48.0/23 | 9 | 510
172.70.51.0/24 | 8 | 254
172.70.52.0/22 | 10 | 1,022
172.70.56.0/21 | 11 | 2,046
172.70.80.0/20 | 12 | 4,094
172.70.96.0/20 | 12 | 4,094
172.70.112.0/22 | 10 | 1,022
172.70.116.0/23 | 9 | 510
172.70.120.0/21 | 11 | 2,046
172.70.128.0/21 | 11 | 2,046
172.70.136.0/23 | 9 | 510
172.70.139.0/24 | 8 | 254
172.70.140.0/22 | 10 | 1,022
172.70.144.0/22 | 10 | 1,022
172.70.148.0/23 | 9 | 510
172.70.150.0/24 | 8 | 254
172.70.152.0/22 | 10 | 1,022
172.70.156.0/23 | 9 | 510
172.70.158.0/24 | 8 | 254
172.70.160.0/22 | 10 | 1,022
172.70.172.0/22 | 10 | 1,022
172.70.176.0/21 | 11 | 2,046
172.70.185.0/24 | 8 | 254
172.70.186.0/23 | 9 | 510
172.70.188.0/22 | 10 | 1,022
172.70.192.0/18 | 14 | 16,382
172.71.0.0/24 | 8 | 254
172.71.2.0/23 | 9 | 510
172.71.4.0/22 | 10 | 1,022
172.71.8.0/21 | 11 | 2,046
172.71.16.0/23 | 9 | 510
172.71.20.0/22 | 10 | 1,022
172.71.24.0/21 | 11 | 2,046
172.71.80.0/21 | 11 | 2,046
172.71.88.0/23 | 9 | 510
172.71.90.0/24 | 8 | 254
172.71.92.0/22 | 10 | 1,022
172.71.96.0/21 | 11 | 2,046
172.71.108.0/22 | 10 | 1,022
172.71.112.0/20 | 12 | 4,094
172.71.128.0/21 | 11 | 2,046
172.71.137.0/24 | 8 | 254
172.71.138.0/23 | 9 | 510
172.71.140.0/22 | 10 | 1,022
172.71.144.0/20 | 12 | 4,094
172.71.160.0/19 | 13 | 8,190
172.71.192.0/18 | 14 | 16,382
173.245.49.0/24 | 8 | 254
173.245.54.0/24 | 8 | 254
173.245.58.0/23 | 9 | 510
173.245.63.0/24 | 8 | 254
185.146.172.0/23 | 9 | 510
188.114.96.0/22 | 10 | 1,022
188.114.100.0/24 | 8 | 254
188.114.102.0/23 | 9 | 510
188.114.106.0/23 | 9 | 510
188.114.108.0/24 | 8 | 254
188.114.111.0/24 | 8 | 254
190.93.240.0/20 | 12 | 4,094
195.242.122.0/23 | 9 | 510
197.234.240.0/22 | 10 | 1,022
198.41.129.0/24 | 8 | 254
198.41.192.0/20 | 12 | 4,094
198.41.208.0/23 | 9 | 510
198.41.211.0/24 | 8 | 254
198.41.212.0/24 | 8 | 254
198.41.214.0/23 | 9 | 510
198.41.216.0/21 | 11 | 2,046
198.41.224.0/21 | 11 | 2,046
198.41.232.0/23 | 9 | 510
198.41.236.0/22 | 10 | 1,022
198.41.240.0/23 | 9 | 510
198.41.242.0/24 | 8 | 254
198.217.251.0/24 | 8 | 254
199.27.128.0/22 | 10 | 1,022
199.27.132.0/24 | 8 | 254
5.226.179.0/24 | 8 | 254
5.226.181.0/24 | 8 | 254
12.221.133.0/24 | 8 | 254
23.141.168.0/24 | 8 | 254
23.178.112.0/24 | 8 | 254
23.247.163.0/24 | 8 | 254
31.43.179.0/24 | 8 | 254
38.67.242.0/24 | 8 | 254
45.8.104.0/22 | 10 | 1,022
45.8.211.0/24 | 8 | 254
45.12.30.0/23 | 9 | 510
45.14.174.0/24 | 8 | 254
45.80.111.0/24 | 8 | 254
45.84.59.0/24 | 8 | 254
45.85.118.0/23 | 9 | 510
45.87.175.0/24 | 8 | 254
45.94.169.0/24 | 8 | 254
45.95.241.0/24 | 8 | 254
45.131.4.0/22 | 10 | 1,022
45.131.208.0/22 | 10 | 1,022
45.133.247.0/24 | 8 | 254
45.137.99.0/24 | 8 | 254
45.142.120.0/24 | 8 | 254
45.145.28.0/23 | 9 | 510
45.158.56.0/24 | 8 | 254
45.159.216.0/22 | 10 | 1,022
64.21.2.0/24 | 8 | 254
65.205.150.0/24 | 8 | 254
66.81.247.0/24 | 8 | 254
66.81.255.0/24 | 8 | 254
72.52.113.0/24 | 8 | 254
80.94.83.0/24 | 8 | 254
89.47.56.0/23 | 9 | 510
89.116.250.0/24 | 8 | 254
89.207.18.0/24 | 8 | 254
91.192.107.0/24 | 8 | 254
91.193.58.0/23 | 9 | 510
91.195.110.0/24 | 8 | 254
91.199.81.0/24 | 8 | 254
93.114.64.0/23 | 9 | 510
95.214.178.0/23 | 9 | 510
103.11.212.0/24 | 8 | 254
103.11.214.0/24 | 8 | 254
103.79.228.0/23 | 9 | 510
103.112.176.0/24 | 8 | 254
103.121.59.0/24 | 8 | 254
103.156.22.0/23 | 9 | 510
103.160.204.0/24 | 8 | 254
103.168.172.0/24 | 8 | 254
103.169.142.0/24 | 8 | 254
103.172.111.0/24 | 8 | 254
154.84.175.0/24 | 8 | 254
103.204.13.0/24 | 8 | 254
103.244.116.0/22 | 10 | 1,022
154.85.9.0/24 | 8 | 254
104.234.158.0/24 | 8 | 254
104.254.140.0/24 | 8 | 254
108.165.216.0/24 | 8 | 254
154.85.99.0/24 | 8 | 254
123.253.174.0/24 | 8 | 254
141.11.194.0/23 | 9 | 510
141.193.213.0/24 | 8 | 254
146.19.22.0/24 | 8 | 254
147.78.121.0/24 | 8 | 254
147.78.140.0/24 | 8 | 254
147.185.161.0/24 | 8 | 254
154.51.129.0/24 | 8 | 254
154.51.160.0/24 | 8 | 254
154.83.2.0/24 | 8 | 254
154.83.22.0/24 | 8 | 254
154.83.30.0/24 | 8 | 254
154.84.14.0/23 | 9 | 510
154.84.16.0/24 | 8 | 254
154.84.20.0/23 | 9 | 510
154.84.24.0/24 | 8 | 254
154.84.26.0/23 | 9 | 510
154.219.3.0/24 | 8 | 254
156.237.4.0/23 | 9 | 510
156.238.14.0/24 | 8 | 254
156.238.18.0/23 | 9 | 510
156.239.152.0/23 | 9 | 510
156.239.154.0/24 | 8 | 254
159.112.235.0/24 | 8 | 254
159.246.55.0/24 | 8 | 254
160.153.0.0/24 | 8 | 254
162.44.104.0/22 | 10 | 1,022
168.100.6.0/24 | 8 | 254
170.114.45.0/24 | 8 | 254
170.114.46.0/24 | 8 | 254
170.114.52.0/24 | 8 | 254
172.83.72.0/23 | 9 | 510
172.83.76.0/24 | 8 | 254
185.207.92.0/24 | 8 | 254
174.136.134.0/24 | 8 | 254
176.126.206.0/23 | 9 | 510
185.7.190.0/23 | 9 | 510
185.18.250.0/24 | 8 | 254
185.38.135.0/24 | 8 | 254
185.59.218.0/24 | 8 | 254
185.67.124.0/24 | 8 | 254
185.72.49.0/24 | 8 | 254
185.109.21.0/24 | 8 | 254
185.135.9.0/24 | 8 | 254
185.148.104.0/22 | 10 | 1,022
185.162.228.0/22 | 10 | 1,022
185.170.166.0/24 | 8 | 254
185.174.138.0/24 | 8 | 254
185.176.24.0/24 | 8 | 254
185.176.26.0/24 | 8 | 254
185.193.28.0/22 | 10 | 1,022
185.201.139.0/24 | 8 | 254
185.213.240.0/24 | 8 | 254
185.213.243.0/24 | 8 | 254
185.221.160.0/24 | 8 | 254
185.234.22.0/24 | 8 | 254
185.238.228.0/24 | 8 | 254
185.244.106.0/24 | 8 | 254
188.42.88.0/23 | 9 | 510
188.244.122.0/24 | 8 | 254
191.101.251.0/24 | 8 | 254
192.65.217.0/24 | 8 | 254
192.133.11.0/24 | 8 | 254
193.9.49.0/24 | 8 | 254
193.16.63.0/24 | 8 | 254
193.17.206.0/24 | 8 | 254
193.67.144.0/24 | 8 | 254
193.188.14.0/24 | 8 | 254
193.227.99.0/24 | 8 | 254
194.1.194.0/24 | 8 | 254
194.36.49.0/24 | 8 | 254
194.36.55.0/24 | 8 | 254
194.36.216.0/22 | 10 | 1,022
194.40.240.0/23 | 9 | 510
194.53.53.0/24 | 8 | 254
194.152.44.0/24 | 8 | 254
194.169.194.0/24 | 8 | 254
195.85.23.0/24 | 8 | 254
195.85.59.0/24 | 8 | 254
195.137.167.0/24 | 8 | 254
195.245.221.0/24 | 8 | 254
196.13.241.0/24 | 8 | 254
196.207.45.0/24 | 8 | 254
199.60.103.0/24 | 8 | 254
199.181.197.0/24 | 8 | 254
199.212.90.0/24 | 8 | 254
202.82.250.0/24 | 8 | 254
203.13.32.0/24 | 8 | 254
203.17.126.0/24 | 8 | 254
203.19.222.0/24 | 8 | 254
203.22.223.0/24 | 8 | 254
203.23.103.0/24 | 8 | 254
203.23.104.0/24 | 8 | 254
203.23.106.0/24 | 8 | 254
203.24.102.0/23 | 9 | 510
203.24.108.0/23 | 9 | 510
203.28.8.0/23 | 9 | 510
203.29.52.0/22 | 10 | 1,022
203.30.188.0/22 | 10 | 1,022
203.32.120.0/23 | 9 | 510
203.34.28.0/24 | 8 | 254
203.34.80.0/24 | 8 | 254
203.55.107.0/24 | 8 | 254
203.89.5.0/24 | 8 | 254
203.107.173.0/24 | 8 | 254
203.193.21.0/24 | 8 | 254
204.62.141.0/24 | 8 | 254
204.68.111.0/24 | 8 | 254
204.209.72.0/23 | 9 | 510
205.233.181.0/24 | 8 | 254
206.196.23.0/24 | 8 | 254
207.189.149.0/24 | 8 | 254
208.100.60.0/24 | 8 | 254
212.24.127.0/24 | 8 | 254
212.110.134.0/23 | 9 | 510
212.239.86.0/24 | 8 | 254
216.120.180.0/23 | 9 | 510
Total |   | 1,690,524



</body>

</html>

**Comment by A5DkjGQUZx** [comment]
Better to keep with the "Definitive" list of CF...

1. lower number of IPs
2. Always sure it is kept updated as their Anycast range used for ingress (what people get in return of CDN dns query)
3. the ANS AS13335 broadcast so many different IP prefixes used for so many different purposes and it is always changing. The famous  1.0.0.0/24 and 1.1.1.0/24 are also in the prefix table of AS13335, also the 198.217.251.0/24 belonging to Visa and much more.

They use Anycast for ALL ingress. Do not worry about the BGP...
https://blog.cloudflare.com/cloudflare-servers-dont-own-ips-anymore/
https://www.cloudflare.com/learning/cdn/glossary/anycast-network/
https://blog.cloudflare.com/a-brief-anycast-primer/

**Comment by MortezaBashsiz** [comment]
I ignore none used IPs like 1.0.0.0 in the script
BTW I wrote the script flexible to make it possible of scanning custom subnets
On the other hand there are several subnets in ASN's that are useful with good performance which are not in whitelists
