### ISSUE TITLE
The progress percentage isn't displayed correctly

### ISSUE THREAD

**Issue by iMoein** [MortezaBashsiz/CFScanner#107]
When scanning the IP, the true progress percentage of the process isn't shown and remains stuck at 2.76%, but the process continues to work.

**Comment by MortezaBashsiz** [comment]
Thanks will take a look

**Comment by MortezaBashsiz** [comment]
I bet you are scanning range 104 if yes
This is because range 104 is too big and will update after it finished will update the progress bar

**Comment by MortezaBashsiz** [comment]
It is done now
pull again and try

**Comment by iMoein** [comment]
Yeah, you're right. I just checked the IP range, it's /13 and we need to scan 524,286 unique IPs within this range.
