### ISSUE TITLE
IP Calculation Method

### ISSUE THREAD

**Issue by iMoein** [MortezaBashsiz/CFScanner#109]
What do you think about calculating the overall progress percentage accurately? You can add up all the subnets on the IP range and since you're converting the subnets to IPs, subtract one IP from the total subnet count each time you check an IP. This way, you can determine both the progress percentage and the remaining number of IPs.

I use the following code to calculate the sum of IPs along with subnets.

```

#!/bin/bash
subnets=$(cat cf.local.iplist)
total_hosts=0
for subnet in $subnets
do
    hosts=$(ipcalc -n "$subnet" | awk '/Hosts\/Net:/ {print $2}')
    ((total_hosts+=hosts))
done
echo "Total Hosts: $total_hosts"

```

**Comment by iMoein** [comment]
The changes you made to the progress bar have resulted in a percentage greater than 100%, which is not ideal. However, it gives a better sense of progress compared to before when it stopped at a large IP range.
This method might be helpful, although if the IP range and IP list are large, it may cause delays or errors on weaker computers when starting the process.

**Comment by MortezaBashsiz** [comment]
Thanks
Plz contribute
These type of changes can not be proceeded in comments or issues 
You can always create PR to branch dev
