### ISSUE TITLE
با اینترنت های مبین نت و ایرانسل خانگی همه تست ها fail شدن

### ISSUE THREAD

**Issue by hossainehsani1982** [MortezaBashsiz/CFScanner#111]
سلام, 
با اینترنت موبایل ایرانسل و شاتل به راحتی ip سالم میده. ولی با اینترنت مبین نت و اینترنت خانگی ایرانسل ای پی دریافت نمیکنه. جالبه که با ای پی سالمی که قبلا گرفتم v2ray روی اینترنت هایی که الان ip سالم نمیدن کار میکنه.

**Comment by MortezaBashsiz** [comment]
درود
ممکنه فیلتر شده باشن
ممکنه اختلال باشه
در هر صورت این اسکریپت برای اینه که شما از فیلترشکن خودتون استفاده کنید و آی پی سالم پیدا کنید

**Comment by sasanmarivani75** [comment]
آقا سلام این بخش realese کجاست اسکنر رو هر چی گشتم پیدا نکردم اسکنر برا ویندوز لطفا لینک رو برام بفرسا مرسی
