### ISSUE TITLE
How to solve ping fluctuation issue on found ip s?

### ISSUE THREAD

**Issue by Pourya-za** [MortezaBashsiz/CFScanner#112]
Recently, ip scanner returns ips whose pings fluctuate that are practically useless. This is because, it tests momentary ping which could fluctuate in permanent utilization.
Is there anyway to configure the app to test each ip's ping and jitter 4 times in 2 seconds (or more) (for instance sampling every 0.5 second)?
By this way, any ip's ping which fluctuates over 1000ms (within 2 seconds) will delist. And finally ip scanner will return stable ips.
It could be second phase of scanning, i mean at first it scans fast all ips which have ping, then it tests every resulted ip's ping to find out stable ips.

**Comment by MortezaBashsiz** [comment]
Hi
Good idea
Will leave this issue to add as a feature to the program
Thanks

**Comment by The13eauty** [comment]
thanks pourya for your idea. i hope we see this feature in the program as soon as possible

**Comment by MortezaBashsiz** [comment]
Added in latest update
Now you are able to define the retries 
It will give you the avg time and also all the results as output
