### ISSUE TITLE
فایل exe  نسخه ویندوز

### ISSUE THREAD

**Issue by mostafa9112** [MortezaBashsiz/CFScanner#122]
سلام نسخه ویندوز فایل exe توش نبود یا من اشتباه رفتم؟

**Comment by behnammoradi76** [comment]
هنوز اضافه نشده » ما هم منتظریم؛ انگار توضیحات اپدیت شده ولی هنوز بارگذاری نشده فایل

**Comment by Kulumi6585** [comment]
دقیقا منم پیداش نکردم

**Comment by parsi8686** [comment]
منم دنبالشم

**Comment by mostafa9112** [comment]
خروجی گرفتم اما یه فایل config.json.template کم دارم واسه ران کردنش

**Comment by mostafa9112** [comment]
اوکی کردمش بلد نیستم آپلود کنم براتون

**Comment by goingfine** [comment]
download now from release section
https://github.com/MortezaBashsiz/CFScanner/releases
