### ISSUE TITLE
working ips found , not working at all

### ISSUE THREAD

**Issue by ZASS-DEV** [MortezaBashsiz/CFScanner#129]
i did like 4-6 scans and its not finding anything. even on that ip range i am using at this moment .
so the program skipping something i dont know what exactly. im sure about it.
as i said even that ip working well for me not showing in program. overall founding 0 ips working
can you check it ?

**Comment by goingfine** [comment]
u mean win app?

**Comment by mohammad3723** [comment]
سلام خواهشا در کانال تلگرام برای افراد مبتدی هم توضیح بذارید چگونه استفاده کنیم

**Comment by goingfine** [comment]
@ZASS-DEV 
چند تا نکته رو توجه کنید. موقع اسکن کردن فیلترشکن روشن نباشه
تعداد اسکن موازی رو روی عدد بالا نزارید
برنامه رو با دسترسی Administrator اجرا کنید
در نهایت توی فولد برنامه فایل log.txt رو باز کنید و اگر توش خطایی مشاهده کردید اینجا بزارید تا بررسی کنیم

**Comment by ZASS-DEV** [comment]
> @ZASS-DEV
> 
> چند تا نکته رو توجه کنید. موقع اسکن کردن فیلترشکن روشن نباشه تعداد اسکن موازی رو روی عدد بالا نزارید برنامه رو با دسترسی Administrator اجرا کنید در نهایت توی فولد برنامه فایل log.txt رو باز کنید و اگر توش خطایی مشاهده کردید اینجا بزارید تا بررسی کنیم

برای مثال من این رنج رو خیلی از آیپی هاش رو بدون مشکل استفاده میکنم اما در برنامه چیزی پیدا نمیکنه فایل لاگ رو پیوست کردم 
[log.txt](https://github.com/MortezaBashsiz/CFScanner/files/10828684/log.txt)

**Comment by goingfine** [comment]
کلا توی هیچ رنجی هیچی پیدا نمیکنه یا فقط با یکی دو رنج مشکل داره؟

**Comment by ZASS-DEV** [comment]
> کلا توی هیچ رنجی هیچی پیدا نمیکنه یا فقط با یکی دو رنج مشکل داره؟

تو هیچ رنجی با اینترنت های مختلف تست کردم. شاتل ، آسیاتک ، همراه اول ، ایرانسل ، مخابرات

**Comment by goingfine** [comment]
خب من فکر کنم مشکل از جای دیگست. مثلا فایروالتون یا انتی ویروس و تنظیمات ویندوز یا چیزای شبیه به این

وقتی برنامه رو باز میکنید اون پایین این پیام میاد؟


`Fronting domain is not accesible! you might need to get new frontig url from our github or check your internet connection.
`

**Comment by ZASS-DEV** [comment]
> خب من فکر کنم مشکل از جای دیگست. مثلا فایروالتون یا انتی ویروس و تنظیمات ویندوز یا چیزای شبیه به این
> 
> وقتی برنامه رو باز میکنید اون پایین این پیام میاد؟
> 
> 
> `Fronting domain is not accesible! you might need to get new frontig url from our github or check your internet connection.
> `

با اینترنت ایرانسل و همراه بله این پیام میاد. اما با شاتل نه

**Comment by goingfine** [comment]
احتمال میدم برنامه v2ray نمیتونه رو سیستمتون اجرا بشه. یا اینکه اجرا میشه اما نمیتونه listen کنه

کامند پرامئت رو توی شاخه برنامه باز کنید و اونجا v2ray.exe رو اجرا کنید ببینید اجرا میشه
اگر شد و پیام خطایی نداد بعد این رو اجرا کنید:
` .\v2ray.exe run -config "v2ray-config\generated\config.159.246.55.2.json"`
قبلش حتما به جای اون `159.246.55.2.json` باید اسم یه فایلی که تو مسیر `v2ray-config\generated` رو بزارید

خب اگه تا اینجا اوکی بود باید پیام بده که `V2Ray 5.1.0 started` بعدش بابد ببینید تونسته روی پورت لیسن کنه یا نه

**Comment by ZASS-DEV** [comment]
> احتمال میدم برنامه v2ray نمیتونه رو سیستمتون اجرا بشه. یا اینکه اجرا میشه اما نمیتونه listen کنه
> 
> کامند پرامئت رو توی شاخه برنامه باز کنید و اونجا v2ray.exe رو اجرا کنید ببینید اجرا میشه اگر شد و پیام خطایی نداد بعد این رو اجرا کنید:
> 
> ` .\v2ray.exe run -config "v2ray-config\generated\config.159.246.55.2.json"`
> 
> قبلش حتما به جای اون `159.246.55.2.json` باید اسم یه فایلی که تو مسیر `v2ray-config\generated` رو بزارید
> 
> خب اگه تا اینجا اوکی بود باید پیام بده که `V2Ray 5.1.0 started` بعدش بابد ببینید تونسته روی پورت لیسن کنه یا نه

با تشکر از حوصله و توضیحات با جزییات شما و همچنین این پروژه خوب. فایل های کانفیگ رو کاستوم به سرور خودم کردم و کاملا مشکل حل شد. بسیار بابت زحماتتون برای این پروژه متشکرم. هم شما و هم مرتضی جان.
