### ISSUE TITLE
دو تا پیشنهاد خیلی مهم

### ISSUE THREAD

**Issue by ea1234567** [MortezaBashsiz/CFScanner#131]
نرم افزار نوشته شده واقعا عالی و زیبا هست،واقعا دست مریزاد به شما

دو تا پیشنهاد خیلی مهم دارم:

پیشنهاد اولم اینه که از هر آی پی 2 بار تست پینگ گرفته بشه و در نتایج فقط پینگ دوم رو در نظر بگیره (میانگین نباشه) چون همیشه بار اول پینگ بالایی میدن آی پی ها ولی بار دوم و سوم گاها پینگ کمتر از نصف میشه،این تغییر رو بصورت پیش فرض میتونید اعمال کنید،یا اینکه یه گزینه ای بزارید خودمون انتخاب کنیم از هر آی پی چند بار پینگ گرفته بشه و ملاک فقط پینگ آخر باشه (نمیدونم میانگین بهتره یا پینگ آخر،اینجا دیگه دانش و  سلیقه برنامه نویس ارجح هست)

پیشنهاد دومم اینه که نتایج رو الان نمیشه sort کرد،قابلیت sort رو هم لطفا فعال کنید که بتونیم آی پی ها رو بر اساس پینگ sort کنیم

**Comment by ea1234567** [comment]
نرم افزار ویندوز منظورم هست

**Comment by goingfine** [comment]
در نطر میگیریم ممنون
