### ISSUE TITLE
نسخه 32 بیتی ویندوز

### ISSUE THREAD

**Issue by mohamad15516** [MortezaBashsiz/CFScanner#135]
**کارتون درسته دمتون گرم به ما امید و آزادی میدید لطفا نسخه ویندوز رو هم برای ویندوز های 32 بیتی منتشر کنید ممنون از تمام تلاشتون پیروز باشید**

**Comment by Amirziplin** [comment]
آره این هم خوبه ، مثلا من با تبلتم مشکل داشتم

**Comment by goingfine** [comment]
دقیقا چه خطایی گرفتین

**Comment by mohamad15516** [comment]
![win32](https://user-images.githubusercontent.com/113285931/221789796-5e057ea6-8a0d-464d-9d94-f5595dfdc4c8.jpg)


> دقیقا چه خطایی گرفتین

**Comment by goingfine** [comment]
[x86.zip](https://github.com/MortezaBashsiz/CFScanner/files/10848693/x86.zip)
اینو جایگزین کنید ببینید کار میکنه

**Comment by mohamad15516** [comment]
> [x86.zip](https://github.com/MortezaBashsiz/CFScanner/files/10848693/x86.zip) اینو جایگزین کنید ببینید کار میکنه

بله درست شد و باز کرد ممنون از لطفتون  حالا باهاش اسکن دارم میکنم اگه اروری نده ولی خیلی لطف کردید ئاقعا خسته نباشید

**Comment by goingfine** [comment]
خواهش
از نسخه بعد 32 هم میزاریم
