### ISSUE TITLE
اضافه کردن یک جای ایپی ها

### ISSUE THREAD

**Issue by alijoon3376** [MortezaBashsiz/CFScanner#137]
سلام دولوپر عزیز ، آیا امکان این وجود داره که همه آیپی های سالم رو یک جا به یک ساب دامین اضافه  کنیم ؟

**Comment by goingfine** [comment]
متوجه منظورتون از همه آیپی های سالم رو یک جا به یک ساب دامین اضافه کنیم نمیشم

**Comment by alijoon3376** [comment]
> متوجه منظورتون از همه آیپی های سالم رو یک جا به یک ساب دامین اضافه کنیم نمیشم

ببینید وقتی ما اسکن میکنیم ایپیارو، مثلا 500 عدد ایپی سالم پیدا میکنه برنامه، ایا راهی هست همه این 500 عدد ایپی پشت یک ساب دامین برن تا اگه یکیش کار نکرد بعدی کار کنه و نیاز نباشه مرتب ایپی عوض کنیم

**Comment by goingfine** [comment]
بااین برنامه میتونید ای پی ها رو پیدا کنید. مورد مد نظر شما از حیطه این برنامه خارجه
