### ISSUE TITLE
نحوه راه اندازی

### ISSUE THREAD

**Issue by whereisafshin** [MortezaBashsiz/CFScanner#14]
سلام برای راه اندازی این اسکریپت نیازه v2ray نصب باشه رو سیستم؟

**Comment by MortezaBashsiz** [comment]
درود نه نیازی نیست نصب باشه
خودش همراه خودش داره

**Comment by whereisafshin** [comment]
> درود نه نیازی نیست نصب باشه خودش همراه خودش داره

یه مشکل تو راه اندازی دارم طبق راهنما وارد میشم دستورات رو میزنم ولی سریع اسکریپت اجراش تموم میشه، کجا کارو اشتباه انجام دادم؟ امکان داره یه ویدیو جدید از راه اندازیش تو کانال یوتیوب بزارید

**Comment by MortezaBashsiz** [comment]
مجدد اسکریپت رو بگیرید از نو
و اجرا کنید
خروجی رو اینجا بزارید

**Comment by miadabdi** [comment]
@MortezaBashsiz 
سلام ممنون برای این پروژه.
 برای این تغییرات آخری که شما یه config.real رو به ما میدین و دانلود میکنیم که میتونیم کانفیگ خودمون جایگزینش کنیم.

```
id: 
Host: 
path: 
serverName: 
```

ولی الان نمیدونم این کانفیگ چ پروتکل هایی رو ساپورت میکنه. مثلا من که Vmess + ws + tls زدم خب serviceName ندارم.
و vmess + grpc + tls زدم serviceName و SNI دارم ولی Host ندارم. حداقل تو کانفیگ کلاینت ها همچین مقداری نمیدیم.
یا اصن vmess ساپورت میکنه؟ یا فقط vless یا چیز دیگه ای هست؟

**Comment by MortezaBashsiz** [comment]
این کلا vmess هست
یه ویدیو درست میکنم حتما برای اینکه چطوری باهاش راحت کار کنید
شما همون کانفیگ دیفالت رو که برای خودم هست استفاده کن و بعدش آی پی ها رو برای کلاینت خودت استفاده کن
معمولا وقتی vmessرو پاسخ بدن بقیه رو هم پاسخ میدن

**Comment by NabiKAZ** [comment]
میتونید توی یه کلاینت v2ray مثلاً ویندوز اکسپورت نسخه کلاینت رو به شکل json بگیرید. (فرقی نمیکنه چه نوع کانفیگ و پروتوکلی باشه) اون رو عیناً توی فایل config.json.temp بگذارید و این دو ویرایش رو بزنید:
پورت ساکس inbounds رو بزارید PORTPORT
آدرس سرور outbounds رو بزارید IP.IP.IP.IP
دیگه اهمیتی نداره محتوای config.script یا config.real چی باشه.(ازشون استفاده نمیشه)
بعد با همون دستور همیشگی اجراش کنید.
من اینطوری جواب گرفتم.

**Comment by havre24** [comment]
کد اخر رو که میزنم این ارور رو میگیرم مشکل از کجاست؟

I require 'parallel' but it's not installed. Please install it and try again.

**Comment by havre24** [comment]
> این اسکریپت رو فقط باید توی خونه از کامپیوتر و اینترنت خودتون اجرا کنید

سلام ممنون در اخر موفق شدم اجراش کنم، ولی ممنون میشم اگر اموزش تست کردن روی کانفیگ خودمون رو بذارید مخصوصا برای grpc

**Comment by bvaredi** [comment]
مرتضی جان سلام.

ممنون از وقتی که گذاشتی برای ساخت این اسکریپت.
آیا میشه روی مک هم ازش استفاده کرد ؟ 
اگر پاسخ مثبت هست از چه آموزشی میتونم استفاده کنم براش؟ 

قربانت

**Comment by MortezaBashsiz** [comment]
درود برای مک فعلا سازگار نیست
