### ISSUE TITLE
Subdomain with A record in addition to http://bot.sudoer.net/best.cf.iran.all

### ISSUE THREAD

**Issue by A5DkjGQUZx** [MortezaBashsiz/CFScanner#140]
Hi Morteza,

Would be great if you can setup multiple subdomains in form of **OperatorName**.DomainName.TLD and add proper/related  working IP's as A records. 
This can be automated it by CF's API as described here: https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/

**Comment by MortezaBashsiz** [comment]
Hi
I will not do it. But you can do it yourself if you want
