### ISSUE TITLE
custom config !!

### ISSUE THREAD

**Issue by Amirziplin** [MortezaBashsiz/CFScanner#141]
لطفا در نسخه های آینده امکان وارد کردن کانفیگ از طرف کابر رو اضافه کنید ، مثلا کابر کانفیگ خودشو  بجای config.json.template بذاره 
و اگه ممکنه گزینه وارد کردن رنج آیپی برای اسکن هم اضافه کنید .
با تشکر فراوان

**Comment by goingfine** [comment]
considering, tnx
