### ISSUE TITLE
میشه بجای استفاده از لینک vmess از config.real  بصورت manually ایتم ها رو وارد v2rayng کرد؟

### ISSUE THREAD

**Issue by hesam80** [MortezaBashsiz/CFScanner#142]
میشه بجای استفاده از لینک vmess از config.real  بصورت manually ایتم ها رو وارد v2rayng کرد؟

**Comment by goingfine** [comment]
فایل config.real رو تو شاخه v2ray-config با تظیمات متناظر خودتون ادیت کنید تست کنید
ببینید اگر جواب داد اینجا اعلام کنید تا برای نسخه های بعد ببینیم چطور میشه این امکان رو بزاریم

**Comment by hesam80** [comment]
با درود فراوان
ممنون از راهنمایی جناب مهندس باشسیز
در رابطه با بسته شدن فیلترینگ bot.sudoer
خواهشا تو این روزا که وضعیت اینترنت ایران بسیار افتضاح شده ، همین کمک های
دوستان هستش که میتونه در انتقال دیتا و وصل بودن خیل عظیمی از جامعه ایرانی
داخل ، به حرکت و جنبش کنونی ، کمک کنه
بازهم بسیار قدردان دوستانی همچون شما هستیم
به امید ایران ، اینترنت و روزهای آزاد
