### ISSUE TITLE
استفاده از کانفیگ شخصی

### ISSUE THREAD

**Issue by ea1234567** [MortezaBashsiz/CFScanner#143]
میشه یه آموزش اضافه کنید که بتونیم از کانفیگ خودمون استفاده کنیم توی اپ ویندوز؟

حتما باید vmess باشه؟ من کل کانفیگ هام vless هست چون ریورس پراکسی کردم و کل یوزرها رو بردم روی پورت 443

**Comment by goingfine** [comment]
فایل config.real رو تو شاخه v2ray-config با تظیمات متناظر خودتون ادیت کنید تست کنید 
ببینید اگر جواب داد اینجا اعلام کنید تا برای نسخه های بعد ببینیم چطور میشه این امکان رو بزاریم

**Comment by ea1234567** [comment]
> فایل config.real رو تو شاخه v2ray-config با تظیمات متناظر خودتون ادیت کنید تست کنید ببینید اگر جواب داد اینجا اعلام کنید تا برای نسخه های بعد ببینیم چطور میشه این امکان رو بزاریم

الان با vless تست کردم نشد
شاید با vmess بشه

**Comment by zoheirkabuli** [comment]
من همون موقع که منتشر کردید config.real تغییر دادم فقط با vmess کار میکنه
اگر بشه کاری کرد که مثلا ما کانفیگ به برنامه اضافه کنیم و بگیم با این کانفیگ تست بگیر خیلی عالی میشه
و پشتیبانی از vless و trojan هم اضافه بشه لطفا
درضمن خیلی کارتون عالیه
حیف که بلد نیستم وگرنه توی توسعه حتما کمکتون میکردم

**Comment by goingfine** [comment]
به طور کلی شما فایل v2ray-config/config.json.template رو با کانفیگ خودتون جایگزین کنید باید کار کنه

**Comment by goingfine** [comment]
اینو تست کنید اگر اوکی بود بگید ببنیم میتونیم این امکان رو تو برنامه اضافه کنیم برای ریلیز های بعدی
این کار رو بکنید:
فایل v2ray-config/config.json.template رو باز کنید تمام محتواش رو پاک کنید و کاملا با کانفیگ خودتون جایگزینش کنید. بعد تست کنید

**Comment by saeedparsam2** [comment]
> اینو تست کنید اگر اوکی بود بگید ببنیم میتونیم این امکان رو تو برنامه اضافه کنیم برای ریلیز های بعدی این کار رو بکنید: فایل v2ray-config/config.json.template رو باز کنید تمام محتواش رو پاک کنید و کاملا با کانفیگ خودتون جایگزینش کنید. بعد تست کنید

تست کردم اینو جواب داد با vless+ws+tcp که احتمالا با بقیه ی کانفیگا هم جواب بده.

**Comment by saeedparsam2** [comment]
هربار که برنامه اجرا میشه همون آی‌پی قبلیارو سرچ میکنه؟
لیست رنج‌ آی‌پی آپدیت نمیشه؟

**Comment by ea1234567** [comment]
> اینو تست کنید اگر اوکی بود بگید ببنیم میتونیم این امکان رو تو برنامه اضافه کنیم برای ریلیز های بعدی این کار رو بکنید: فایل v2ray-config/config.json.template رو باز کنید تمام محتواش رو پاک کنید و کاملا با کانفیگ خودتون جایگزینش کنید. بعد تست کنید

بعد از اینکه مقادیر خودمون رو جایگزین کردیم باید فایل رو هم rename کنیم؟
منظورم اینه که اسم config.json.template رو تغییر بدیم به config.json ؟
پس این وسط تکلیف فایل config.real چی میشه؟
اسکریپت در این مورد کمی مبهم هست و راهنمای واضحی نداره
ممنون میشم لطف کنید و یکم در این مورد توضیح بدید

**Comment by goingfine** [comment]
فعلا داریم تست میکنیم دیگه. چیزیو رینیم نمیخواد بکنید 
دقیقا همینو انجام بدین فقط:
https://github.com/MortezaBashsiz/CFScanner/issues/143#issuecomment-1447956716






> > اینو تست کنید اگر اوکی بود بگید ببنیم میتونیم این امکان رو تو برنامه اضافه کنیم برای ریلیز های بعدی این کار رو بکنید: فایل v2ray-config/config.json.template رو باز کنید تمام محتواش رو پاک کنید و کاملا با کانفیگ خودتون جایگزینش کنید. بعد تست کنید
> 
> بعد از اینکه مقادیر خودمون رو جایگزین کردیم باید فایل رو هم rename کنیم؟ منظورم اینه که اسم config.json.template رو تغییر بدیم به config.json ؟ پس این وسط تکلیف فایل config.real چی میشه؟ اسکریپت در این مورد کمی مبهم هست و راهنمای واضحی نداره ممنون میشم لطف کنید و یکم در این مورد توضیح بدید
