### ISSUE TITLE
اضافه کردن رنج آی پی بصورت دستی

### ISSUE THREAD

**Issue by kaamyaab** [MortezaBashsiz/CFScanner#148]
سلام و وقت بخیر خدمت شما

پیشنهادی داشتم جهت بهبود کارایی نرم افزار اراِه شده جهت اسن ای پی ها،

لطفا قسمتی را اضافه کنید که بوسیله ی آن بشود رنج آی پی های دلخواه را از کار بر دریافت کرده و غیر از کلود فلر نظیر رنج آی پی های ابر آروان  را نیز بشود اسکن کرد.

باتشکر از زحماتی که در این راستا میکشید.

**Comment by goingfine** [comment]
این ویژگی توی آخرین ریلیز اضافه شده
