### ISSUE TITLE
خطا در هنگام اجرا

### ISSUE THREAD

**Issue by hamidtb** [MortezaBashsiz/CFScanner#150]
سلام
اسکریپت رو اپدیت کردم به آخرین ورژن
اما زمانی که میخوام اسکریپت رو اجرا کنم خطای زیر رو میده

$ bash cfScanner.sh SUBNET 8 ./config.real 250
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
updating config.real

using your own config ./config.real
id: 248ecb72-89cf-5be7-923f-b790fca681c5
Host: scherehtzhel01.sudoer.net 
Port: 443
path: api01
serverName: 248ecb72-89cf-5be7-923f-b790fca681c5.sudoer.net

reading config ...
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3

**Comment by armineslami** [comment]
ظاهرا با اپدیت جدید باید اطلاعات کانفیگ رو بصورت json ذخیره کنید:

**Comment by MortezaBashsiz** [comment]
درود
بله باید جیسان ذخیره کنید

**Comment by seniormmd1** [comment]
> درود بله باید جیسان ذخیره کنید

استاد دو لاین اخر فایل جیسان باید چی وارد بشه 
frontdomain 
scandomain
این دوتا مقدارشون برابر چی هست توی کانفیگ ممنون میشم یه راهنمایی بکنید
