### ISSUE TITLE
جلوگیری از اجرا شدن نرم افزار توسط آنتی ویروس خود ویندوز

### ISSUE THREAD

**Issue by ea1234567** [MortezaBashsiz/CFScanner#151]
ورژن قبلی همچین مشکلی نداشت
ورژن جدید بدافزار شناسایی میشه

تهدید رو هم جدی در نظر میگیره و فایل اجرایی رو فورا پاک میکنه،معمولا توی تهدید های متوسط اجازه میده که ignore کنی و فایل رو به وایت لیست اضافه کنی

**Comment by goingfine** [comment]
دقیقا چه پیامی میده
اسکرین شات

**Comment by ea1234567** [comment]
> دقیقا چه پیامی میده اسکرین شات

https://www.uplooder.net/img/image/90/2015eefce8268861c7204248ce9fc535/Untitled.png

**Comment by goingfine** [comment]
عکس رو همینجا اپلود کنید

**Comment by ea1234567** [comment]
> عکس رو همینجا اپلود کنید

![Untitled](https://user-images.githubusercontent.com/40317198/222291947-289e5859-f668-4f38-a3cb-4d9ee4ea95bc.png)

**Comment by goingfine** [comment]
خیلی عجیبه احتمالا روی سیستمتون یا بین راه آلوده شده!
این گزارش virustotal از همین ریلیز که کاملا clean هست
https://www.virustotal.com/gui/url/72b7dd680861e50fde3b7c8598b2d72d061585bd425149adfad002066f418dca

شما دو تا کار انجام بدید
اولا دقیقا همین فایل رو برید از از قسمت قرنطینه دفندر پیدا کنید و زیپ کنید و اینجا بزارید تا بتونیم ببینیم فایل تغییر کرده یا نه و چکش کنیم

دوما یک بار دیگه از بخش ریلیز ها دانلود کنید ببینید دوباره همین داستان رو دارید یا نه. اگر میتونید تو یک ویندوز دیگه هم تست کنید.

**Comment by ea1234567** [comment]
> خیلی عجیبه احتمالا روی سیستمتون یا بین راه آلوده شده! این گزارش virustotal از همین ریلیز که کاملا clean هست https://www.virustotal.com/gui/url/72b7dd680861e50fde3b7c8598b2d72d061585bd425149adfad002066f418dca
> 
> شما دو تا کار انجام بدید اولا دقیقا همین فایل رو برید از از قسمت قرنطینه دفندر پیدا کنید و زیپ کنید و اینجا بزارید تا بتونیم ببینیم فایل تغییر کرده یا نه و چکش کنیم
> 
> دوما یک بار دیگه از بخش ریلیز ها دانلود کنید ببینید دوباره همین داستان رو دارید یا نه. اگر میتونید تو یک ویندوز دیگه هم تست کنید.


الان روی یه PC دیگه تست کردم بازم آنتی ویروس پاکش کرد
هر دوی سیستم ها ویندوز ۱۱ هستن با آخرین آپدیت دفندر
