### ISSUE TITLE
سرعت اپلود

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#155]
سلام
ممنون بابت نرم افزار بسیار خوبتون که واقعا کاربردی هستش 
اگر امکانش هست تست سرعت اپلود هم بذارید چون همونطور که می دونید الان مشکل همه سرعت اپلود هستش که محدود شده و سرعت دانلود روی خیلی از سرور ها اذیت کننده نیست
خیلی ممنونم

**Comment by MortezaBashsiz** [comment]
Duplicated #78
