### ISSUE TITLE
استاپ موقت و ریزوم

### ISSUE THREAD

**Issue by cy33r** [MortezaBashsiz/CFScanner#157]
**لطفا قابلیت استاپ موقت و ریزوم رو هم اضفه کنید**

**Comment by goingfine** [comment]
اضافه خواهد شد لطفا ایشوی تکراری نزنید

**Comment by cy33r** [comment]
**مهندس جان کسی توی تاپیک ها اشاره نکرده بود . 
فعلا با همون ad scanner ادامه میدم تا انشالله نرم افزار رو رفع مشکل و پر امکانات کنید  سپاس**
