### ISSUE TITLE
sed: -e expression #1, char 43: unknown option to `s'

### ISSUE THREAD

**Issue by danamjb** [MortezaBashsiz/CFScanner#161]
I get this error after most of IP checks during scan.
It seems its a problem not just a warning because it will find no clean ips but on the same subnet and internet connection, the windows version finds some ips.

Ubuntu 22.04
Latest commit

**Comment by MortezaBashsiz** [comment]
Could you please get the latest update of the repository and tell me how you execute the command
Do you give a specific subnet or IP list? if yes then make sure not empty line in your list file

**Comment by danamjb** [comment]
The repository is up to date (I used git pull before run).
I run this command:
`~/CFScanner/bash# bash cfScanner.sh SUBNET 8 1 ./ClientConfig.json 50`
for some IPs, it will fail (prints out FAILED), but the same IP is flagged as clean (and actually works fine) in windows version.
This is how it looks like:

![image](https://user-images.githubusercontent.com/117814041/222427332-7081e75b-bdcf-4a37-a042-a3e038737cd6.png)

Some details to consider:
- In the ClientConfig.json, these options should remain unchanged right? Cuz I don't know what they are! `frontDomain`, `scanDomain`, `subnetsList`
- On the Linux page of the project, you mentioned that `tput` is a dependency. But I wasn't able to install it using `apt-get install libncurses5-dbg`, I got this error:
`E: Package 'libncurses5-dbg' has no installation candidate`
Although, the script didn't throw any error or exception saying that the package is not installed. Should I add any ppa for installing this package?

Thanks a lot

**Comment by MortezaBashsiz** [comment]
It may be related to the tput but not sure
BTW it seems on ubuntu 22.04 there are some incompatibilities 
Plz try to install tput and reopen the issue if it was the same after installing tput

**Comment by danamjb** [comment]
@MortezaBashsiz I just wanted to say that it is also tested on Ubuntu 20.04 and the same issue persists, and also it seems `tput` is installed on Ubuntu by default. But I saw you closed the issue :(

**Comment by MortezaBashsiz** [comment]
I already mentioned if you have problem reopen it :D
What is your sed version?

**Comment by danamjb** [comment]
> I already mentioned if you have problem reopen it :D What is your sed version?

Sorry, I thought only the repo owner could open it.

**Comment by MortezaBashsiz** [comment]
It may be related to your path config
 Use like 
`api01/download`
Not
`/api01/download`

Remove the first /

**Comment by danamjb** [comment]
From the beginning, I wasn't using the first /.

**Comment by danamjb** [comment]
An observation:
I have two servers and two v2ray configs, the path for the first config contains / in the middle (path: something/something) but the second one does not contain any / (path: something). When I run the script with the second config, the problem will disappear.

**Comment by MortezaBashsiz** [comment]
So you are sure that it does not work for path like
`something/something`

Then could you share the config file created by the script? You can find them in config directory in root of repository

**Comment by danamjb** [comment]
[This](https://pastebin.mozilla.org/6qz8KU8v) is a sample config generated in `config` directory.
As you can see, the `path` value will not get filled up right when you use a path in `sth/sth` format. I tested a path without / and the value was filled up correctly.

**Comment by MortezaBashsiz** [comment]
OK
Thanks, so the script has problem 
I will work on it and inform here

**Comment by MortezaBashsiz** [comment]
issue has been resolved in Linux version
You can pull the latest and try
