### ISSUE TITLE
مشکل فایل کانفیگ در نسخه جدید اسکریپت(روی لینوکس)

### ISSUE THREAD

**Issue by AlirezaGhanavati** [MortezaBashsiz/CFScanner#167]
عرض سلام و خداقوت

توی نسخه جدید اسکریپت ظاهرا دایرکتوری فایل های اجرایی تغییر کرده ولی آموزشی مطابق اون قرار داده نشده. ضمن اینکه چندتا فیلد دیگه از جمله frontdomain , scandomain اضافه شده ولی توضیحی درخصوصش ارائه نشده.
ضمن اینکه Config.real دیفالت خود اسکریپ کار نمیکنه، چون وقتی پاسش میدیم به اسکریپت خطا میده. 
لطفا در مورد راه اندازی با config.real دیفالت خود اسکریپت راهنمایی کنید.(منظورم config.real هست که بعد از دستور curl دانلود میشه روی سرور)

**Comment by danamjb** [comment]
سلام وقت بخیر

فایل‌های اجرایی لینوکس به پوشه `bash` منتقل شدن. شما باید به این پوشه تغییر مسیر بدید و سپس اسکریپت رو ران کنید (همه مراحل [اینجا ](https://github.com/MortezaBashsiz/CFScanner/blob/main/bash/README.md)توضیح داده شده). فقط هنگام اجرا به جای `config.real` باید از `ClientConfig.json` استفاده کنید.

در رابطه با کانفیگ، از این پس باید از فایل `ClientConfig.json` برای مقداردهی اطلاعات کانفیگ سرورتون استفاده کنید. این فایل آپدیت شده و مقدایر `scandomain` و `frontdomain` دیگه در اون وجود ندارن (یک بار `git pull` بزنید یا محتویات [این ](https://github.com/MortezaBashsiz/CFScanner/blob/main/bash/ClientConfig.json)فایل رو داخلش کپی پیست کرده و سپس با اطلاعات کانفیگ خودتون پرش کنید.) به طور کلی هم اگر دست به این مقادیر نزنید و مقدار پیش‌فرضشون رو نگه دارید فکر نمیکنم مشکلی پیش بیاد.
