### ISSUE TITLE
امکان اسکن ipv6

### ISSUE THREAD

**Issue by aliali256** [MortezaBashsiz/CFScanner#168]
سلام
لطفا امکان بارگذاری آیپی یا CIDR ورژن 6 و همچنین اسکن اون رو برای کلاینت ویندوز قراردهید.

**Comment by MortezaBashsiz** [comment]
درود فعلا برای این موضوع برنامه‌ای نداریم
به این دلیل که روی اکثر اوپراتورها ساپورت نمیشه و برای عموم مردم کاراریی نداره
سپاس
