### ISSUE TITLE
مشکل عدم کامپایل نسخه جدید و عدم اسکن ایپی 

### ISSUE THREAD

**Issue by megasoheilsh** [MortezaBashsiz/CFScanner#175]
سلام نسخه
  v1.0.8462.33246 
هیچی رو اسکن نمیکنه ، و سورس هم کامپال نمیشه سورس خراب گذاشتید ؟

**Comment by MortezaBashsiz** [comment]
درود
این چه سوالی هست که میپرسید؟
سورس خراب گذاشتید؟
معمولا سوالی یا مشکلی هست باید با جزییات مطرح بشه
نه اینکه خیلی طلبکارانه اینطوری بیایید کامنت بزارید
منم میبندم این ایشو رو
یاد بگیرید چطوری باید مشکل رو مطرح کنید بعد یه ایشو دیگه باز کنید
