### ISSUE TITLE
IP scan returns empty result set - اسکن آی پی مقدار خالی برمیگرداند

### ISSUE THREAD

**Issue by nasser1245** [MortezaBashsiz/CFScanner#176]
وقت بخیر
من اسکن آی پی انجام میدم با اسکنر که کل عملیات به نظر بدون مشکل اجرا میشه . پراگرس تا 100 میره ولی در نهایت آیپی لیست نال برگردونده میشه. هم با کانفیگ آقا مرتضی تست کردم هم کانفیگ خودم که رو سروری که با CFAnsible کانفیگ شده. با یا بدون custom ip و همچنین با یا بدون subnet تست کردم همیشه جواب نال هست. تست روی اینترنت مخابرات

**Comment by MortezaBashsiz** [comment]
درود
لینوکسی یا ویندوزی؟

**Comment by nasser1245** [comment]
لینوکسم آقا مرتضی. اوبونتو 20. با sudo هم زدم باز همون بود. یه خطای curl میده ولی به نظر میرسه مساله مهمی نباشه. چون در نهایت از فایل لوکال استفاده میکنه. چند خط اول initialize رو اوردم.
خودم اول شک کردم که شاید بخاطر اینه که توی کانفیگ v2ray که بعد از ران کردن ansible بدست میاد مقادیر add و host با هم برابر نیستن. مقدار host برخلاف add که توش HostName یکبار وارد شده؛ دو بار HostName وارد شده؛ که تو initialize ای که پایین اوردم مشخصه.
اما این هم نبود چون با مقادیر پیش فرض خودتون هم باز لیست آی پی ها null میشد.
```
using your own config ClientConfig.json
{
        "id": "3dccb528-28fa-5527-bacf-ee85c7fb0eae",
        "host": "schereserver0.{HostName}.{HostName}",
        "port": "443",
        "path": "api01",
        "serverName": "b783caee-b9df-11ed-b914-e3806fe46fd0.biainja.net",
        "subnetsList": "cf.local.iplist"
}

You are testing download
reading config ...
parallel: invalid option -- '-'
could not get url curl -s https://asnlookup.com/asn/AS13335/
will use local file
```

**Comment by nasser1245** [comment]
مشکل حل شد آقا مرتضی. مشکل از parallel بود که گویا درست نصب نشده بود و اصلا عملیات انجام نمیشد فقط پراگرس جلو میرفت. روی ریپو apt تنها ورژن 2016 برای پارالل هست (نمیدونم چرا) ولی دستی که دانلود و آخرین نسخه رو نصب کردم لیست آی پی رو داد.
مرسی
