### ISSUE TITLE
more options!!

### ISSUE THREAD

**Issue by Amirziplin** [MortezaBashsiz/CFScanner#178]
لطفا تست آپلود و اگه امکان داره jitter هم اضافه کنید ، بعضی آیپی های بدست آمده دانلودشون عالیه ولی آپلود ضعیف دارن 
تو قسمت وارد کردن آی پی دستی فقط میشه یه آیپی وارد کرد اگه بشه براش نت ماسک بذارین یا رنج آیپی تعریف کرد عالی میشه
یه مشکلی هم که هست اینه که فایلهای کانفیگ  رو ادیت میکنم ،بعد از اجرای برنامه دوباره به حالت پیشفرض برمیگردن (شاید فقط برای من اینجوریه)
گزینه load ip ranges  هم هر نوع فایلی بهش دادم چیزی وارد نمیکنه (حتی از cf.local.iplist هم آی پی وارد نمیکنه)
آیکون برنامه رو هم تغییر بدین جذاب تر میشه 😁
با تشکر از شما

**Comment by goingfine** [comment]
اگه هر IP range رو توی یک خط جدا بزارید باید بتونه لودش کنه. الان من لیست دادم بهش:

![image](https://user-images.githubusercontent.com/126115050/222881688-c443ec7c-0f02-4a03-be34-603cb4e1fd76.png)

اگر نشد فایل ip‌ تون رو اینجا بزارید ببنیم مشکلش چیه

فایلهای کانفیگ جنریت میشن و هر دفعه از نو نوشته میشن. از نسخه بعد امکان اضافه کردن کانفیگ شخصی رو هم اضافه میکنیم

**Comment by Amirziplin** [comment]
> اگه هر IP range رو توی یک خط جدا بزارید باید بتونه لودش کنه. الان من لیست دادم بهش:
> 
> ![image](https://user-images.githubusercontent.com/126115050/222881688-c443ec7c-0f02-4a03-be34-603cb4e1fd76.png)
> 
> اگر نشد فایل ip‌ تون رو اینجا بزارید ببنیم مشکلش چیه
> 
> فایلهای کانفیگ جنریت میشن و هر دفعه از نو نوشته میشن. از نسخه بعد امکان اضافه کردن کانفیگ شخصی رو هم اضافه میکنیم

آره اینجوری میشه ولی باید براش نت ماسک تعریف کرد و فایل ادیت کرد ، منظورم یه کادر بود که مثلا از 198.0.01 تا 198.0.0.12 رو بهش بدیم اسکن کنه

**Comment by goingfine** [comment]
اذیت نکنید نهایت میخواید توی فایل یه 24/ به آخر آی پی اضافه کنید دیگه.
این پروژه اوپن سورس هست و از کانتریبویت هاتون اسقبال میشه. ما وقت نمیکنیم به همه درخواست ها برسیم چون زمان زیادی میبره.
از هر کاری منجمله طراحی لوگو و آیکون و افزودن ویژگی های جدید استقبال میکنیم.

**Comment by Amirziplin** [comment]
باشه ممنون
