### ISSUE TITLE
Stop Scan / توقف اسکن - Win 32-bit

### ISSUE THREAD

**Issue by mohsen-armoun** [MortezaBashsiz/CFScanner#179]
**توضیحات**
همین که اسکن شروع میشه توقف میخوره
دقیقا مثل قبل (#156) با این تفاوت که دیگه ارور Unhadled exception رو نمیده
**OS**
Win 7 ultimate SP1 32-bit
**Network**
Wireless ( Hotspot Irancell/MCI) 
روی شبکه Lan مشکلی نداره !! و اسکن رو انجام میده

**تصویر**
![This is an image](https://s2.uupload.ir/files/log2_8pwp.jpg)

**فایل log**

[log.txt](https://github.com/MortezaBashsiz/CFScanner/files/10887747/log.txt)

@MortezaBashsiz @goingfine

**Comment by goingfine** [comment]
close the app
make an empty file in the app folder and name it `enable-debug`
run the app and do some scan
then in the app folder find debug.txt file
attach it here to see if we can have some more info about your issue

**Comment by goingfine** [comment]
ضمنا اون پیام Exiting فقط زمانی میاد که دکمه Close روی برنامه رو بزنید یا Alt+F4 رو زده باشید.
تعداد ترد ها رو هم کمتر بزارید.

**Comment by mohsen-armoun** [comment]
> enable-debug

[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10887886/debug.txt)

**Comment by goingfine** [comment]
خب الان که تست کردید وسط اسکن از برنامه خارج شد یا نه؟

**Comment by mohsen-armoun** [comment]
> خب الان که تست کردید وسط اسکن از برنامه خارج شد یا نه؟

نه از برنامه خارج نمیشه، فقط Stop میکنه اسکن رو و وقتی هم میخوام بعد Stop شدن، برنامه رو کلا ببندم گیر میکنه و نمیبنده برنامه رو ALT+F4 هم جواب نمیده و حتما باید از پروسه End Task کنم

**Comment by goingfine** [comment]
و این مشکل فقط زمانی پیش میاد که نت هات اسپات وصله؟

**Comment by mohsen-armoun** [comment]
> و این مشکل فقط زمانی پیش میاد که نت هات اسپات وصله؟

تو ورژن قبلی همین مشکل رو داشتم با شبکه Lan ولی الان رو Lan اوکی شده ، ولی رو هات اسپات گیر میکنه

**Comment by goingfine** [comment]
اوکی. توی فولدر برنامه این دستور رو توی CMD اجرا کنید و خروجیش رو بزارید اینجا:

`.\v2ray.exe run -config="v2ray-config/generated/config.159.246.55.14.json"`

**Comment by mohsen-armoun** [comment]
> .\v2ray.exe run -config="v2ray-config/generated/config.159.246.55.14.json"

یا من دستور رو اشتباه نوشتم یا مشکل جای دیگه هست ، حتی معمولی هم میخوام `V2ray.exe` اجرا کنم ارو 64-bit میده

**تصویر**
![This is an image](https://s2.uupload.ir/files/log3_2kzn.jpg)

**Comment by mohsen-armoun** [comment]
> .\v2ray.exe run -config="v2ray-config/generated/config.159.246.55.14.json"



> اوکی به همون هات اسپات وصل باشید و توی فولدر برنامه این دستور رو توی CMD اجرا کنید و خروجیش رو بزارید اینجا:
> 
> `.\v2ray.exe run -config="v2ray-config/generated/config.159.246.55.14.json"`

دستور رو که اشتباه نوشته بودم ، یه پوشه کم بود تو آدرس CD ، ولی باز هم همون ارور 64-bit رو میده
احتمالا از همونه و هنوز با نسخه 32Bit اوکی نشده ؟
@goingfine

**Comment by goingfine** [comment]
ما چون ویندوز ۳۲ بیتی نداریم برای تست یکم دستمون بستست. 
خب شما این فایل که نسخه ۳۲ بیتی v2ray هست رو از اینجا دانلود کنید:
`https://github.com/v2ray/v2ray-core/releases/download/v4.28.2/v2ray-windows-32.zip`
از داخلش فایل `v2ray.exe` رو بردارید و جایگزین فایل متناظرش در فولدر برنامه ما بکنید

بعد همه موارد بالا رو دوباره تست کنید ببینید همه چیز درست میشه یا نه. حتما ببنید IP هم پیدا میکنید یا نه گزارشش رو بدید.
اگه اوکی بود توی ریلیز های بعدی درستش کنیم.

**Comment by mohsen-armoun** [comment]
> ما چون ویندوز ۳۲ بیتی نداریم برای تست یکم دستمون بستست. خب شما این فایل که نسخه ۳۲ بیتی v2ray هست رو از اینجا دانلود کنید: `https://github.com/v2ray/v2ray-core/releases/download/v4.28.2/v2ray-windows-32.zip` از داخلش فایل `v2ray.exe` رو بردارید و جایگزین فایل متناظرش در فولدر برنامه ما بکنید
> 
> بعد همه موارد بالا رو دوباره تست کنید ببینید همه چیز درست میشه یا نه. حتما ببنید IP هم پیدا میکنید یا نه گزارشش رو بدید. اگه اوکی بود توی ریلیز های بعدی درستش کنیم.

متاسفانه باز هم جواب نداد



[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10888067/debug.txt)

**Comment by goingfine** [comment]
این رو هم انجام بدید

https://github.com/MortezaBashsiz/CFScanner/issues/179#issuecomment-1454671399

**Comment by goingfine** [comment]
خب اون نسخه v2ray که گذاشتم قدیمی بود این رو دانلود کنید

`https://github.com/v2fly/v2ray-core/releases/download/v5.4.0/v2ray-windows-32.zip`

این باید کار کنه

**Comment by goingfine** [comment]
مشکل شما حل شد؟
@mohsen-armoun

**Comment by mohsen-armoun** [comment]
> `https://github.com/v2fly/v2ray-core/releases/download/v5.4.0/v2ray-windows-32.zip`

سلام @goingfine  ، خسته نباشید، عذرخواهی میکنم برای دیر پاسخ دادن
خیر همچنان همونه و تغییری نکرده ، فقط موقع دستور CMD یه پیغام نمایش میده که گذاشتم تصویرش رو

**فایل log**
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10890787/debug.txt)

**اجرای دستور CMD**
بعد اجرای دستور همینجا میمونه تو این صفحه با این پیغام
![This is an image](https://s2.uupload.ir/files/log4_d9w1.jpg)

**Comment by goingfine** [comment]
برای من که کار کرد.
 الان مشکل با هات اسپاته ؟ وقتی با لن وصل هستید کار میکنه و IP پیدا میکنه یا نه؟
ضکنا کماکان همون مثل قبل متوقف میشه و هنگ میکنه؟

**Comment by mohsen-armoun** [comment]
> برای من که کار کرد. الان مشکل با هات اسپاته ؟ وقتی با لن وصل هستید کار میکنه و IP پیدا میکنه یا نه؟ ضکنا کماکان همون مثل قبل متوقف میشه و هنگ میکنه؟

با هات اسپات که هنگ میکنه و استپ میکنه
الان با Lan یه 1 ساعتی هست گذاشتم و هیچ IPی رو برنمیگردونه !

**Comment by goingfine** [comment]
اینو جایگزین کنید و در حالت دیباگ تست کنید
فایل دیباگ رو بزارید اینجا
[x86-test.zip](https://github.com/MortezaBashsiz/CFScanner/files/10891581/x86-test.zip)

**Comment by mohsen-armoun** [comment]
> اینو جایگزین کنید و در حالت دیباگ تست کنید فایل دیباگ رو بزارید اینجا [x86-test.zip](https://github.com/MortezaBashsiz/CFScanner/files/10891581/x86-test.zip)

الان مشکل هنگ کردن رفع شده و روی هات اسپات هم داره اسکن میکنه، فقط میممونه Ip پیدا کردن، باید بزارم تست کنه ببینم چیزی پیدا میکنه

[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10891630/debug.txt)

**Comment by goingfine** [comment]
باز داره میگه v2ray.exe نسخه 32 بیتی نیست
مطمینید همین نسخه 32بینی رو که گذاشتم ریختید و جایگزین کردید

داره اینو میگه

`An error occurred trying to start process 'v2ray.exe' with working directory 'C:\Users\---\Downloads\v1.0.8462.33246-Windows-x86\v1.0.8462.33246-Windows-x86'. The specified executable is not a valid application for this OS platform.`

**Comment by mohsen-armoun** [comment]
> باز داره میگه v2ray.exe نسخه 32 بیتی نیست مطمینید همین نسخه 32بینی رو که گذاشتم ریختید و جایگزین کردید
> 
> داره اینو میگه
> 
> `An error occurred trying to start process 'v2ray.exe' with working directory 'C:\Users\---\Downloads\v1.0.8462.33246-Windows-x86\v1.0.8462.33246-Windows-x86'. The specified executable is not a valid application for this OS platform.`

به سیستم دسترسی ندارم متاسفانه، فردا دوباره از اول تست میگیرم اطلاع میدم 🙏🏻

**Comment by mohsen-armoun** [comment]
> `https://github.com/v2fly/v2ray-core/releases/download/v5.4.0/v2ray-windows-32.zip`

خوب من برگشتم
سلام سلام
اون فایل `32bit v2ray` رو مجدد کپی نکرده بودم که مشکل میخورد و ارور `OS` رو میداد
فایل آخری که گذاشتید رو کپی کردم و روی هات اسپات تو همون لحظه اول `IP `پیدا کردم
هم فایل `Debug `رو اینجا میزارم هم فایل کامل برنامه رو 
ممنون
**Debug**
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10894392/debug.txt)

**CFS-32bit**
[v1.0.8462.33246-Windows-x86.zip](https://github.com/MortezaBashsiz/CFScanner/files/10894398/v1.0.8462.33246-Windows-x86.zip)

**Comment by mohsen-armoun** [comment]
> باز داره میگه v2ray.exe نسخه 32 بیتی نیست مطمینید همین نسخه 32بینی رو که گذاشتم ریختید و جایگزین کردید
> 
> داره اینو میگه
> 
> `An error occurred trying to start process 'v2ray.exe' with working directory 'C:\Users\---\Downloads\v1.0.8462.33246-Windows-x86\v1.0.8462.33246-Windows-x86'. The specified executable is not a valid application for this OS platform.`


خوب من برگشتم
سلام سلام
اون فایل `32bit v2ray` رو مجدد کپی نکرده بودم که مشکل میخورد و ارور `OS` رو میداد
فایل آخری که گذاشتید رو کپی کردم و روی هات اسپات تو همون لحظه اول `IP `پیدا کردم
هم فایل `Debug `رو اینجا میزارم هم فایل کامل برنامه رو 
ممنون
**Debug**
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10894392/debug.txt)

**CFS-32bit**
[v1.0.8462.33246-Windows-x86.zip](https://github.com/MortezaBashsiz/CFScanner/files/10894398/v1.0.8462.33246-Windows-x86.zip)

**Comment by goingfine** [comment]
نزدیک بود سکته بدی منو خخخ

مبارکه
