### ISSUE TITLE
 تست آپلود

### ISSUE THREAD

**Issue by hossein16219** [MortezaBashsiz/CFScanner#180]
سلام و سپاس بیکران از زحمات شما
این پروژه بینظیره با این قابلیتها و آپدیتهای سریع

لطفا امکان تعیین سرعت و تست آپلود هم به نسخه ویندوز اضافه کنید چون اکثر آیپیهایی که فعال هستن و پینگ مناسبی هم دارن در عمل سرعت خوبی نمیدن و فقط اونایی که آپلودشون بالاست عملکرد خیلی خوبی دارن - با توجه به محدودیت شدید آپلود بین الملل در ایران این مورد ضروری هست برای یافتن آیپی های پرسرعت .

**Comment by goingfine** [comment]
اگر وقت کنیم. قول نمیدم
