### ISSUE TITLE
Please provide .NET 6 bundled package

### ISSUE THREAD

**Issue by AliM1988** [MortezaBashsiz/CFScanner#182]
Can you provide a bundled package that includes (.NET 6)? It makes independent package, no need to download and install [Microsoft .NET 6.0 Desktop Runtime].

My OS version is windows 8. So .NET 6 can't be installed on it.
Please see v2rayN which provide a bundled package that .NET 6 is embed on it. ([Link](https://github.com/2dust/v2rayN/releases/tag/6.12))

**Comment by goingfine** [comment]
سلام دو مشکل هست یکی اینکه وقت نمیکنیم و مشکل بعدی حجم زیادیه که باندل داره برای اپلود و امکان اپلودش رو نداریم.
