### ISSUE TITLE
درخواست پابلیک کردن کد

### ISSUE THREAD

**Issue by pumper** [MortezaBashsiz/CFScanner#186]
سلام اگه براتون امکانش هست کد مربوط به bot.sudoer.net رو پابلیک کنید تا بقیه بتونن چند تا سرور مشابهش ایجاد کنند .
با تشکر از زحماتتون توی این مدت.🙏🙏

**Comment by MortezaBashsiz** [comment]
درود
انجام خواهم داد در چند روز آینده

**Comment by zoheirkabuli** [comment]
> درود انجام خواهم داد در چند روز آینده

بخش نمایش IP ها با من ✌️
