### ISSUE TITLE
هنگ کردن هنگام استفاده از نتایج اسکن

### ISSUE THREAD

**Issue by M-Sadegh-M** [MortezaBashsiz/CFScanner#187]
سلام
من تمام لیست را اسکن کردم و حدود 32000 آیپی بدست آوردم.
الان وقتی میخواهم از قسمت نتایج اون آیپی ها را بارگزاری کنم نرم افزار هنگ می‌کنه.
اگر گزارشی احتیاج هست بگید تا ارسال کنم.

https://user-images.githubusercontent.com/124435580/222926547-a25a29ab-7799-496c-bbec-ed1103624bab.mp4

**Comment by goingfine** [comment]
خداییش زیاده 32k 😁

**Comment by M-Sadegh-M** [comment]
> خداییش زیاده 32k 😁

اسکن کردم یکبار برا همیشه نخواهم هربار حدود 1.7M را اسکن کنم
همین لیستا اسکن کنم هربار
🙃

**Comment by goingfine** [comment]
فایل نتایج رو بزارید اینجا بررسی کنیم

**Comment by M-Sadegh-M** [comment]
> فایل نتایج رو بزارید اینجا بررسی کنیم

[20230303-191719-results.zip](https://github.com/MortezaBashsiz/CFScanner/files/10892601/20230303-191719-results.zip)

**Comment by goingfine** [comment]
مشکل حل شد تو ریلیز بعدی درستش میکنیم
