### ISSUE TITLE
باز نشدن سایت 

### ISSUE THREAD

**Issue by kiavash599** [MortezaBashsiz/CFScanner#193]
سلام در تاریخ 14 اسفند 1401 سایت مربوطه شما باز نمیشه

**Comment by MortezaBashsiz** [comment]
درود
خاموش شده و کلا باز نخواهد شد

**Comment by kiavash599** [comment]
یعنی هیچ وقت دیگه این سرویس راه نخواهد افتاد
خیلی عالی بود. میشه بپرسم چرا؟
