### ISSUE TITLE
مشکل ظاهری در نسخه ویندوز

### ISSUE THREAD

**Issue by zoheirkabuli** [MortezaBashsiz/CFScanner#202]
![image](https://user-images.githubusercontent.com/56550780/222980499-e479beed-ebf8-42e6-ba86-b42c0e6fe20b.png)
![image](https://user-images.githubusercontent.com/56550780/222980502-fa3adea8-0c89-4af0-89a0-85f0736560e4.png)
سلام من این دو مشکل ظاهری رو دارم

**Comment by goingfine** [comment]
من فکر کنم تنظیمات تم یا فونت و اینجور چیزای ویندزتون تنظیمات دیفالت نیست و تغییر کرده درسته؟
میتونید همه تنظیمات این مدلی رو ریست کنید به پیش فرض؟

ضمنا نسخه دقیق ویندوز و دات نتتون رو چیه

**Comment by zoheirkabuli** [comment]
من تغییری در فونت یا ظاهر ویندوز ندادم

فکر کنم مشکل از دات نت باشه آپدیت میکنم بهتون اطلاع میدم

**Comment by goingfine** [comment]
سایز فونت که افزایش داره ظاهرا

**Comment by zoheirkabuli** [comment]
فونت رو ریست کردم
دات نت شش رو نصب کردم اینم نسخه دقیق ویندوزم 
Edition	Windows 11 Enterprise
Version	22H2

OS build	22621.1265

**Comment by aparatcutgame** [comment]
مال بنده هم همین ایرادو داره
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/تصویر_صفحه_2023-03-08_005325_ago.png" border="0" alt="آپلود عکس" /></a>
ویندوز 11 اینترپرایز
22H2
دات نت هم آپدیته.

**Comment by alichb** [comment]
![Screenshot 2023-03-08 112930](https://user-images.githubusercontent.com/36522561/223655818-d060eaac-eefe-465d-b1ec-b269b8d6421e.jpg)
مشکل نمایش در مانیتور 4K دکمه استارت/استاپ صحیح نمایش داده نمیشه. در رزولوشن های پایین تر مشکلی ندارد.

**Comment by goingfine** [comment]
> ![Screenshot 2023-03-08 112930](https://user-images.githubusercontent.com/36522561/223655818-d060eaac-eefe-465d-b1ec-b269b8d6421e.jpg) مشکل نمایش در مانیتور 4K دکمه استارت/استاپ صحیح نمایش داده نمیشه. در رزولوشن های پایین تر مشکلی ندارد.


توی حالت غیر ماکزیمایز چطوریه؟

**Comment by goingfine** [comment]
همه لطفا این رو اجرا کنید و عکسش رو بزارید اینجا
[ui-debug.zip](https://github.com/MortezaBashsiz/CFScanner/files/10920880/ui-debug.zip)

**Comment by aparatcutgame** [comment]
این پیغام رو داد:
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/تصویر_صفحه_2023-03-08_185608_odjr.png" border="0" alt="آپلود عکس" /></a>

**Comment by goingfine** [comment]
ویندورتون ۳۲ بیتیه؟

**Comment by aliali256** [comment]
سلام از نسخه ابتدایی ویندوز، برا منم مشکل gui داشته. ویندوز 10

![1](https://user-images.githubusercontent.com/5729722/223832160-03e95e32-e272-4949-9071-b8f343aade8b.JPG)
![2](https://user-images.githubusercontent.com/5729722/223832252-60f49a98-b8f4-43b8-a9f7-63832fe6d7de.png)
![3](https://user-images.githubusercontent.com/5729722/223832285-94156c26-fe14-49c9-9272-77ede23c6e69.png)
![4](https://user-images.githubusercontent.com/5729722/223832307-5e81f7f9-4da8-4714-adff-209db2ece1b3.png)
![5](https://user-images.githubusercontent.com/5729722/223832332-7ba9c482-fae2-4da3-b4b5-40163948a8d3.png)
![6](https://user-images.githubusercontent.com/5729722/223832360-cbd18478-4ec6-4c6c-b195-d4b8491a51d4.png)

**Comment by alichb** [comment]
> > مشکل نمایش در مانیتور 4K دکمه استارت/استاپ صحیح نمایش داده نمیشه. در رزولوشن های پایین تر مشکلی ندارد.
> 
> توی حالت غیر ماکزیمایز چطوریه؟

در حالت غیر ماکسیمایز هم همین مشکل هست در رزولوشن 4k

**Comment by goingfine** [comment]
> همه لطفا این رو اجرا کنید و عکسش رو بزارید اینجا [ui-debug.zip](https://github.com/MortezaBashsiz/CFScanner/files/10920880/ui-debug.zip)

@alichb @zoheirkabuli @aliali256

**Comment by zoheirkabuli** [comment]
با اینکه دات نت رو نصب دارم و نسخه اصلی بالا میاد ولی این هی خطای دات نت میده که نصب نیست

@goingfine

**Comment by goingfine** [comment]
اینو بریزید تو فولدر برنامه بعد اجراش کنید

**Comment by aliali256** [comment]
![14](https://user-images.githubusercontent.com/5729722/223843649-72a653a0-690a-4b86-8036-e7090a64f365.JPG)
![15](https://user-images.githubusercontent.com/5729722/223843675-c9d39b03-908c-4ff3-b352-d970dc7d51c5.JPG)

**Comment by zoheirkabuli** [comment]
![image](https://user-images.githubusercontent.com/56550780/223848476-036d23ad-7f76-464a-ae78-9a22caea690c.png)
![image](https://user-images.githubusercontent.com/56550780/223848511-9186c0be-ff8b-4c50-9107-340a9c5f8061.png)

**Comment by goingfine** [comment]
خب حالا اینو تست کنید ببینید مشکل لیست تب کلوفلر حل شد یا نه؟
عکسشم بزارید

[ui-debug2.zip](https://github.com/MortezaBashsiz/CFScanner/files/10925248/ui-debug2.zip)

**Comment by aliali256** [comment]
![19](https://user-images.githubusercontent.com/5729722/223851900-c22068ba-5ffa-428c-a48d-9ab72859a98f.JPG)
![20](https://user-images.githubusercontent.com/5729722/223851924-bd0e0228-1e19-42d2-b932-13925e57ec53.png)

نه کامل، هنوز بعضی Label ها کامل نیستند، Listbox ایپی ها کلا رفت تو حالت Normal.

**Comment by goingfine** [comment]
ای بابا یه باگی داره خود این دات نت انگار
راستی فونت ویندوزتون رو بزارید روی صد درصد. 
اینو رو امتحان کنید داخل اون باکس که نوشتم ۶۰۰ عددهای مختلف رو وارد کنید و بعددکمه set width رو بزنید ببنید عرض لیست تغییر میکنه و روی چه عددی درست میشه

[Uploading ui-debug3.zip…]()

**Comment by goingfine** [comment]
اینو تست کنید

[ui-debug4.zip](https://github.com/MortezaBashsiz/CFScanner/files/10929395/ui-debug4.zip)

**Comment by zoheirkabuli** [comment]
![image](https://user-images.githubusercontent.com/56550780/223983870-33072dd5-2d6e-46aa-99be-eb3916649bfc.png)

**Comment by goingfine** [comment]
مرسی
بدون زدن اون دکمه همون اول که باز کردین چه شکلی بود
عکسش

**Comment by aparatcutgame** [comment]
> ویندورتون ۳۲ بیتیه؟

نه
فکر کنم باگه چون مواردش داره زیاد میشه.
این هم عکسای جدید نتونستم تو حالت 100% بندازم همه چی بی کیفیت شده بود و اصلا ابزار عکس گیری هنگ کرد حتی الانم که برگردونمش کار نمیکنه فکر کنم این باگ ویندوزه چون تو لینوکس روی 100 درصد رزلوشون همه چی کار میکرد. به هر صورت تو اون حالت هم زیاد فرقی نکرد.
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/cloudflare_scan_-_1.0.8468.21569_18_12_1401_01_14_50_ب.ظ_ejo9.png" border="0" alt="آپلود عکس" /></a>
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/cloudflare_scan_-_1.0.8468.21569_18_12_1401_01_23_57_ب.ظ_d4c.png" border="0" alt="آپلود عکس" /></a>

**Comment by goingfine** [comment]
بدون زدن اون دکمه همون اول که باز کردین چه شکلی بود

**Comment by aparatcutgame** [comment]
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/cloudflare_scan_-_1.0.8468.21569_18_12_1401_01_30_29_ب.ظ_81u9.png" border="0" alt="آپلود عکس" /></a>
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/cloudflare_scan_-_1.0.8468.21569_18_12_1401_01_30_36_ب.ظ_i669.png" border="0" alt="آپلود عکس" /></a>

**Comment by goingfine** [comment]
مشکل از گذاشتن روی زوم 125 درصد هستش.
چند بار گفتم بزارید روی 100 درصد و تست کنید ولی خب هیچکدوم انگار توجه نمیکنید.
الان خودم ویندوزم رو گذاشتم روی 125 درصد و برای من هم بهم ریخت.
باید ببینم توی این حالت داستانش چیه.
همتون لطفا روی 100 درصد بزارید و تایید کنید که روی 100 درصد مشکل حل میشه یا نه

**Comment by goingfine** [comment]
حتی خود ویژوال استودیو نمیتونه توی حالت 125 درصد کار کنه و بهم میریزه!! 
خدا لعنتت نکنه ماکروسافت یه ویژگی میدی به ملت که خودتم کامل ساپورتش نمیکنی😂


![vsss](https://user-images.githubusercontent.com/126115050/223994872-917e9c31-fb63-4b1e-a800-76ed4620e9f8.png)

**Comment by goingfine** [comment]
ویندوز یه باگ عجیب و مسخره داره تو حالت 125.
ببینید درست شد

@alichb @zoheirkabuli @aliali256 @aparatcutgame 

[ui-debug5.zip](https://github.com/MortezaBashsiz/CFScanner/files/10930804/ui-debug5.zip)

**Comment by aparatcutgame** [comment]
> مشکل از گذاشتن روی زوم 125 درصد هستش. چند بار گفتم بزارید روی 100 درصد و تست کنید ولی خب هیچکدوم انگار توجه نمیکنید. الان خودم ویندوزم رو گذاشتم روی 125 درصد و برای من هم بهم ریخت. باید ببینم توی این حالت داستانش چیه. همتون لطفا روی 100 درصد بزارید و تایید کنید که روی 100 درصد مشکل حل میشه یا نه

ویندوز اینو توصیه شده واسه لپ تاپم زده عجیبه. صفحه هم احساس میکنم تو این حالت یکم بی کیفیت میشه.
چون فکر کنم واسه شما pc هست مشکلی نداره.
<a href="https://uupload.ir/" target="_blank"><img src="https://s2.uupload.ir/files/cloudflare_scan_-_1.0.8468.26547_18_12_1401_03_50_24_ب.ظ_1nn.png" border="0" alt="آپلود عکس" /></a>
تو حالت فول سایز مشکل داره. و دکمه skip فرورفته.

**Comment by aliali256** [comment]
سلام Scale 125% توسط خود ویندوز پیشنهاد شده که بهینه هست 100% خیلی دور میشه آیکون ها ولی نتایج به این صورت هست
100%
![1](https://user-images.githubusercontent.com/5729722/224058492-829acf90-955c-4554-af90-b49e87882f4f.JPG)
![2](https://user-images.githubusercontent.com/5729722/224058441-60305fe1-ab62-4236-a3d9-d5958405c6ad.JPG)
در حالت Maximize مشکل داریم رو 100% تمام صفحه نیست.

125% Scale
![3](https://user-images.githubusercontent.com/5729722/224058732-ae827213-0440-4d2e-b372-7edc3278cb82.JPG)
![4](https://user-images.githubusercontent.com/5729722/224058771-5c4b8634-ce43-4588-9736-93f2097c4c87.JPG)
در حالت 125% گزینه Skip کامل نشون میده، و حالت Maximize از پایین صفحه میره تو نوار وظیفه، ولی باز کامل تمام صفحه نیست.

**Comment by aparatcutgame** [comment]
تمام مشکلات حل شده اما تو حالت تمام صفحه پایینش(download error و اینا) نمایش داده نمیشه.

همچنان هم کامل تمام صفحه رو نمی گیره
