### ISSUE TITLE
not working on mac anymore

### ISSUE THREAD

**Issue by mrjavadseydi** [MortezaBashsiz/CFScanner#203]
**Describe the bug**
after running ` bash cfScanner.sh --test-type BOTH --mode SUBNET --thread 16 --tryCount 4 --config config.real --speed 100 --file custom.subnets` i'm getting this error :

```
getopt: illegal option -- n
error validate
```

 if  i remove -n from cfScanner.sh:504 that error disappears but i will get this error : 

```
updating config.real

using your own config 
cat: : No such file or directory

config file does not exist 

```

**Screenshots**
https://ibb.co/3v8w7xw

**Desktop :**
 - OS: macos ventura
 - Version 13.1 (22C65)

**Comment by MortezaBashsiz** [comment]
Sorry this script is not fully supported on mac
And we are not also support it completely and all mac integration is supported by other contributors 
But you can find the solution and contribute if you like

**Comment by armineslami** [comment]
It's because in macOs, `getopt` doesn't support long option names. To make the code work on macOS you need to modify the code and use short option names. See [#205](https://github.com/MortezaBashsiz/CFScanner/pull/205)
