### ISSUE TITLE
Problem with custom subnet

### ISSUE THREAD

**Issue by ImanIranNejad** [MortezaBashsiz/CFScanner#204]
hi i want to use [gcore's cdn ip addresses list](https://api.gcore.com/cdn/public-net-list) but  wasn't able to do it .
how can i import this list to custom.subnet without doing it manually?
and yes i modified config file to my values that are based gcore cdn with port 80.
btw its working without finding clean ip's  but  want to test it with my scanned ip's

**Comment by MortezaBashsiz** [comment]
Windows or Linux?
For Linux you need to insert them in a file without empty line and double coutation

**Comment by ImanIranNejad** [comment]
for linux . thanks

**Comment by robin98** [comment]
@ImanIranNejad did this method helped you?

**Comment by ImanIranNejad** [comment]
> @ImanIranNejad did this method helped you?

no it will not generate config files for test i dont know why. even in windows version i add  only 188.72.125.0/24 (its from gcore)
and it will not generate anything at generated folder.

**Comment by robin98** [comment]
> > @ImanIranNejad did this method helped you?
> 
> no it will not generate config files for test i dont know why. even in windows version i add only 188.72.125.0/24 (its from gcore) and it will not generate anything at generated folder.

Yep, same for me. I tried my best and changed everything in app config so it become compatible with gcore, but found no luck.
I think this method doesn't meant for the scanning gcore subnets.
in the other hand, I tried scanning using Angry IP Scanner and found some working IP's which can be uses as the CDN replacement address but none of them stable enough. I don't know if gcore services generally not a good option for our usage or maybe the IPs was blocked duo to very smaller range for their CDN.

anyway, I think we need a different strategy for scanning the gcore subnets. @MortezaBashsiz maybe you can assist?
who knows? maybe if we found a way for using gcore's CDN, it worth it.
