### ISSUE TITLE
امکان تغییر پروتکلها در فایل کانفیگ

### ISSUE THREAD

**Issue by aliamg1356** [MortezaBashsiz/CFScanner#207]
متوجه شدم برای تست آی پی ها از کانفیگ پیش فرض استفاده میکنه بر پایه vmess و ترانزیمیشن ws
اگر بشه از پروتکلهای دیگه استفاده کرد و ترانزیمیشن gprcخوب میشه و اگه امکانش هست از فایک کانفیگها کدام قسمتها باید تغییر پیدا کنه یکم توضیح بدین  ممنون بابت زحمات

**Comment by goingfine** [comment]
توی نسخه بعدی اضافه میشه
