### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by iMoein** [MortezaBashsiz/CFScanner#208]
Hello, I encounter the following error on macOS:

$ bash % bash cfScanner.sh --mode SUBNET --test-type BOTH --thread 8 --tryCount 1 --config config.real --speed 100

getopt: illegal option -- -
error validation

**Comment by MortezaBashsiz** [comment]
It should be OK
Did you check with the latest update?

**Comment by iMoein** [comment]
I'm using your latest update that I received today. I've tried hard to solve this problem by updating the packages, but I couldn't succeed.

The steps I've taken so far are updating getop via brew and installing it via util-linux. However, it seems that no version of getop matches the file you have prepared, or there is a need to install a specific version that is not available on macOS or I cannot find it. Can you please provide more information or guidance on how to resolve this issue?

**Comment by iMoein** [comment]
I wrote some code to check if the required packages are installed, and if not, install them. However, it didn't work as expected.

`#!/bin/bash

# Define a function to check if a package is installed
function check_package {
    if ! command -v $1 &> /dev/null
    then
        echo "$1 is not installed; installing..."
        brew install $1
    else
        echo "$1 is already installed"
    fi
}

# Check if Homebrew is installed; if not, install it
if ! command -v brew &> /dev/null
then
    echo "Homebrew is not installed; installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Check and install the required packages
check_package getopt
check_package jq
check_package git
check_package tput
check_package bc
check_package curl
`

**Comment by iMoein** [comment]
I wrote some code to check if the required packages are installed, and if not, install them. However, it didn't work as expected.
<img src="https://i.postimg.cc/1tmLKMjr/Screenshot-2023-03-07-at-9-05-58-PM.png" alt="bashcode" width="100%" >

**Comment by kazemrahmani** [comment]
سلام آقا مرتضی اسکنر ویندوز برای من هیچ ای پی نمی اره لطفا راهنمایی بفرمایید

**Comment by iMoein** [comment]
I found this command from your discussion section and the problem seems to be solved
$ bash cfScanner.sh -m SUBNET -t BOTH -thr 56 -try 1 -c config.real -s 100

**Comment by MortezaBashsiz** [comment]
You are right
I have to update readme to add mac syntax
Thanks
