### ISSUE TITLE
به نظر میرسه برخی آی‌پی‌های سالم عبور نمیکنند!

### ISSUE THREAD

**Issue by NabiKAZ** [MortezaBashsiz/CFScanner#21]
اینطور به نظر میرسه که روی این خط برخی آی‌پی‌های سالم عبور نمیکنند. کد هم مشخصه که داره چیزی رو با سایت خودتون تست میکنه.

https://github.com/MortezaBashsiz/CFScanner/blob/f6faaebf651e56f6ca3fd78d80662a89dfb49919/scripts/cfFindIP.sh#L109

من برای اطمینان توی حلقه IP رو برابر یه آی‌پی که مطمئن بودم درسته قرار دادم و تایم‌اوت هم زیاد کردم و بعد از مدتی failed شد و ازش رد نشد که به تست اصلی برسه.
خود آدرس fronting.sudoer.net هم بدون فیلترشکن تقریباً باز نمیشه حداقل برای من. که میتونه دلیلش همین باشه.
اینطوری ممکنه خیلی آی‌پی‌های سالم رو که پشت اون دستور میمونن رو از دست بدیم.
کلاً پروژه زیاد وابستگی به آدرس‌های سایتتون داره.

**Comment by MortezaBashsiz** [comment]
البته اون دامنه مستقیم باز نخواهد شد
حتی اگه فیلتر هم بشه باز هم همون دومین فرانت از آی پی کلاد فلر رد میشه
یعنی اگه دومین فرانت برای شما کار نکنه طبیعتا احتمال اینکه کلادفلر روی اون آی پی توی اون روز ی که شما ران میکنید در دسترس باشه و سرویس بده کمه
