### ISSUE TITLE
ipv4 ranges - cloudflare 

### ISSUE THREAD

**Issue by MHSanaei** [MortezaBashsiz/CFScanner#217]
سلام 
ممنون از برنامه ی خوبتون
خواستم بگم که لیست ip cloudflare واقعا درست نیست یه سری  ip داخلش هست که اصلا برای cloudflare نیست به هرحال من لیست رو از خود سایت cloudflare  گرفتم 
https://www.cloudflare.com/ips-v4
و به subnet با prefix 22 تقسیم کردم که هر range شامل 1022 ip میشه در نتیجه راحت میشه رنج های مختلف رو اسکن کرد
اینجا قرار میدم خواستین استفاده کنید 

[ipv4 ranges cloudflare.txt](https://github.com/MortezaBashsiz/CFScanner/files/10920266/ipv4.ranges.cloudflare.txt)

**Comment by MortezaBashsiz** [comment]
درود
این آیپی ها برای بی جی پی کلادفلر هست
میتونید اینجا لیست کاملش رو ببینید
ما هم از همینا پیدا میکنیم
اون لیستی هم که شما میگید وایت لیست کلادفلر هست و کلادفلر کلی آی پی دیگه داره
https://asnlookup.com/organization/cloudflare/

**Comment by MHSanaei** [comment]
ممنون از سرعت بالای شما در پاسخ 
بله این موضوع رو نمیدونستم 
لیست رو اپدیت کردم تکراری هارو حذف کردم و رنج های بزرگ رو خورد کردم 
خدمت شما 
[ipv4 ranges cloudflare.txt](https://github.com/MortezaBashsiz/CFScanner/files/10921023/ipv4.ranges.cloudflare.txt)

**Comment by OmidEbrahimii** [comment]
سلام و عرض ادب خدمت شما
اقای سنایی هیچ راه ارتباطی با شما پیدا نکردم نه توی تلگرام ایدی گذاشتید نه اینجا و این خیلی بده 
لطف کنید یه اپدیت بدید این پنل 3ایکس مشکل کیوار کد داره و بعد دو سه تا یوزر کیوار کد رو نشون نمیده بعد از دو سه بار حذف و نصب یه بار شانسی کار میکنه
