### ISSUE TITLE
افت سرعت اسکن

### ISSUE THREAD

**Issue by ea1234567** [MortezaBashsiz/CFScanner#218]
سلام و خسته نباشید خدمت مرتضی و goingfine و سگاروی عزیز،کاری که شما دارید انجام میدید واقعا فراتر از عالی هست،دست مریزاد

نسخه جدید ویندوزی هم واقعا عالی شده

فقط یک ایرادی که از نسخه های اولیه پابرجا هست (نسخه ویندوزی) اینه که وقتی سرعت اسکن رو میبریم بالا مثلا 32 میزاریم،اسکن با سرعت بالایی استارت میشه ولی به آخرای اسکن که میرسیم سرعت اسکن شدیدا کاهش پیدا میکنه
مثلا یه رنج 510 تایی میزنم اسکن بشه تا 490 تا سرعت عالی هست ولی 20 تای آخر خیلی با تاخیر جلو میره،انقدر کند میشه که مجبور میشم دستی stop رو بزنم

یه پیشنهاد هم قبلا داده بودم که مشخص کنیم از هر آی پی چند بار پینگ گرفته بشه و میانگین ذکر بشه یا پینگ آخر ملاک قرار بگیره

بابت وقتی که گذاشتید و زحمات شبانه روزی که کشیدید تشکر میکنم

**Comment by goingfine** [comment]
بیزحمت همین 512 تا رو به طور کامل و در حالت دیباگ تست بگیر و لاگش رو بزار
یبار با 32 یبار با 4 ترد 

Close the app
Make an empty file in the app folder and name it `enable-debug`
Run the app and do some scan.
Then in the app folder find `debug.txt` file.
Attach it here to see if we can have some more info about your issue.

**Comment by ea1234567** [comment]
> بیزحمت همین 512 تا رو به طور کامل و در حالت دیباگ تست بگیر و لاگش رو بزار یبار با 32 یبار با 4 ترد
> 
> Close the app Make an empty file in the app folder and name it `enable-debug` Run the app and do some scan. Then in the app folder find `debug.txt` file. Attach it here to see if we can have some more info about your issue.

وقتی حالت debug رو فعال میکنم دیگه نمیتونم سرعت اسکن رو عوض کنم و بزارم روی 4 یا 32
روی عدد 1 ثابت میمونه

**Comment by goingfine** [comment]
موقتا غیرفعالش کردم با این تست بگیرید
فایل رو برای هر حالت جدا کنید و بزارید
[debug.zip](https://github.com/MortezaBashsiz/CFScanner/files/10929584/debug.zip)

**Comment by ea1234567** [comment]
> موقتا غیرفعالش کردم با این تست بگیرید فایل رو برای هر حالت جدا کنید و بزارید [debug.zip](https://github.com/MortezaBashsiz/CFScanner/files/10929584/debug.zip)

[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/10929875/debug.txt)

**Comment by ea1234567** [comment]
آپلود کردم
تست رو بانفیگ شخصی انجام دادم
البته با کانفیگ دیفالت هم همین مشکل رو دارم
سی پی یو من AMD Ryzen هست،ممکنه این نرم افزار با AMD ناسازگار باشه؟
AMD Ryzen 1200 (4 Core - 8 Thread)

**Comment by ea1234567** [comment]
CPU: AMD Ryzen 1200 (4 Core - 8 Thread)
Ram: 8G DDR4
تست با کانفیگ شخصی خودم انجام شد،البته با کانفیگ دیفالت هم همین مشکل رو دارم
احتمال ناسازگاری این نرم افزار با سی پی یو های برند ای ام دی وجود داره؟

**Comment by goingfine** [comment]
حداقل توی این لاگی که گذاشتین اون 32 سریع توی 1.5 دقیقه تمام شده و گیر نکرده.

32:
مدت زمان: 1:30
پیدا کرده: 46
درصد موفقیت: **10%**

:4
مدت زمان: 6:10
پیدا کرده: 399
درصد موفقیت: **78%**

نکته: این نتیجه درصد موفقیت باید برای شما نشونه این باشه که تعداد ترد بالا وقتی نتتون یا سروتون بسیار سریع نیست فقط باعث تایم اوت و از دست دادن IP های سالم میشه

یسری خطا داریم توی حالت 4 که میگه نمیتونه روی پورت لیسن کنه و پورت مشغوله که میتونه بخاطر اسکن قبلی باشه که هنوز پورت ها بسته نشدند.
بعد از اتمام اسکن 32 توی تسک منیجر دقت کنید ببینید پروسس هایی با نام v2ray.exe در حال اجرا باقی موندند؟ و چند تا هستن.

**Comment by ea1234567** [comment]
حرف شما کاملا متین هست و منم در حریان هستم که اسکن ۳۲ دقت کمتری داره

سوال من اینه که چرا سرعت اسکن اولیه بسیار بالاتر از سرعت اسکن در مراحل پایانی هست،حتی روی ۴ هم همین مشکل وجود داره

**Comment by goingfine** [comment]
طبق لاگی که گذاشتین مشکل حادی مشاهده نشد. اما اگر همچین احساسی دارین ممکنه بخاطر همین خطا ها باشه که گفتم یا دلایل دیگه که باید اطلاعات بیشتری باشه بیشتر بررسی بشه.
قضیه پروسس ها رو بررسی کنید. ضمنا اگر بتونید یک ویدیو از کند شدن بگیرید هم خوبه

**Comment by ea1234567** [comment]
> من اینو بررسی کردم ببنید وقتی یک ساب نت مثلا با 500 آی پی رو با مثلا 32 ترد اسکن میکنیم برنامه میاد این 500 تا رو بین 32 ترد پخش میکنه و اینها به طور موازی شروع میکنند به اسکن. درست؟ از طرفی ما باید تا انتهای همه 500 ای پی صبر کنیم تا بتونیم بریم به ساب نت بعدی. اینم درست؟ خب وقتی به انتهای اون 500 تا میرسیم خیلی از این ترد ها کارشون تموم شده اما تعداد کمی کارشون هنوز تموم نشده و همه باید صبر کنند تا همه اون 32 ترد اخر کارشون تموم بشه تا بتونیم بریم ساب نت بعدی. کار خاصی نمیشه کرد برای این مساله و باگ هم نیست این رو اجرا کنید و اون اقسمت که working thread رو نشون میده ببینید تا روشن بشه قضیه چیه
> 
> [working-threads.zip](https://github.com/MortezaBashsiz/CFScanner/files/10940947/working-threads.zip)

بله درسته،تست کردم دقیقا همین بود که شما فرمودین

یه سوال فنی داشتم،الان سی پی یو من کلا 8 ترد داره،چجوری میشه که روی 32 ترد هم برای من جواب میده گاها

**Comment by goingfine** [comment]
سیستم عامل مدیریتش میکنه با زمان بندی
