### ISSUE TITLE
Other CDN's

### ISSUE THREAD

**Issue by ImanIranNejad** [MortezaBashsiz/CFScanner#220]
hi its been a week that im trying to use this script for other cdn's but so far i couldnt success.
i tried both linux and win versions.
it cant generate configs at generated folder in windows so i think it might be same problem at linux.
there are other cdn's that im using them right now but i want to find best ip's as we do for CF ip's
i hope you can help me with this 
thanks

**Comment by MortezaBashsiz** [comment]
As you can see
This is Cloudflare scanner which works only for cloudflare cdn and no other cdn
