### ISSUE TITLE
.\v2ray.exe tls ping  درست کار نمیکنه تو نسخه قبل که تست کردم مشکلی نبود

### ISSUE THREAD

**Issue by m0riii** [MortezaBashsiz/CFScanner#221]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by goingfine** [comment]
مشکلتون رو دقیق و با جزییات مطرح کنید

**Comment by zoheirkabuli** [comment]
من هی این خطارو میگیرم
‍‍```
Pinging without SNI
Handshake succeeded
Allowed domains:  [cdnjs.cloudflare.com *.cdnjs.cloudflare.com sni.cloudflaressl.com]

Pinging with SNI
handshake failure:  read tcp 192.168.1.3:2609->188.114.99.0:443: wsarecv: An existing connection was forcibly closed by the remote host.
Tls ping finished
```

**Comment by zoheirkabuli** [comment]
```
Pinging without SNI
Handshake succeeded
Allowed domains:  [cdnjs.cloudflare.com *.cdnjs.cloudflare.com sni.cloudflaressl.com]

Pinging with SNI
handshake failure:  read tcp 192.168.1.3:2609->188.114.99.0:443: wsarecv: An existing connection was forcibly closed by the remote host.
Tls ping finished
```

**Comment by zoheirkabuli** [comment]
@goingfine  من هعی خطارو میگیرم موقع تست handshake

**Comment by iSegaro** [comment]
سلام , دارید ادرس ورکر رو تست میگیرید این خطا رو میبینید؟

**Comment by zoheirkabuli** [comment]
> سلام , دارید ادرس ورکر رو تست میگیرید این خطا رو میبینید؟
> 

نه دامنه شخصی خودمه که پشت کلودفلر هستش

**Comment by iSegaro** [comment]
سلام
از دامنهای مجانی که گذاشتم استفاده کردی؟ اون دامنه هایی که ساختید احتمالا حذف شده دوباره چک کنید
اگه دامنه شخصی هست توی تنظیمات ssl کلادفلر تغییری اعمال کردید که این خطا برمیگردونه
قابلیت هند شیک با sni برای مهمه فقط بدون sni کار نمیکنه فقط با sni

**Comment by zoheirkabuli** [comment]
> سلام از دامنهای مجانی که گذاشتم استفاده کردی؟ اون دامنه هایی که ساختید احتمالا حذف شده دوباره چک کنید اگه دامنه شخصی هست توی تنظیمات ssl کلادفلر تغییری اعمال کردید که این خطا برمیگردونه قابلیت هند شیک با sni برای مهمه فقط بدون sni کار نمیکنه فقط با sni

تنظیمات رو تغییری ندادم وقتی VPN روشنه پاسخ succeeded میده ولی درحالت خاموش این خطارو میده
