### ISSUE TITLE
get Top Download Errors: (25) 25 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#223]
i get this error when use new version

Top Download Errors: (25)
25 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)

**Comment by MortezaBashsiz** [comment]
Please specify which version you are using
Linux?
Windows?
Python?
and more detail

**Comment by babakbenam** [comment]
سلام
وقتی اجرا میکنم این پیام دو دریافت میکنم!
bash cfScanner.sh -vpn YES -m SUBNET -t BOTH -thr 8 -try 1 -c config.real -s 100
Unexpected option: -v - this should not happen.
Usage: cfScanner [ -vpn YES/NO ]
			[ -m SUBNET/IP ] 
			[ -t DOWN/UP/BOTH ]
			[ -thr <int> ]
			[ -try <int> ]
			[ -c <configfile> ]
			[ -s <int> ] 
			[ -f <custome-ip-file> (if you chose IP mode)]

**Comment by goingfine** [comment]
دقیق توضیح بدید که آیا با کانفیگ شخصی تست گرفتید یا کانفیگ پیش فرض. کلا تونستید IP پیدا کنید یا نه؟

توی برنامه ویندوز این خطا الزاما مشکلی نداره و خیلی از IP ها که کار نمیکنن این خطا رو میدن. یا اینکه مشکلی با تنظیمات tls و ssl سرورتون هست البته باز دقیق ترش رو @iSegaro میدونه.

اگر میتونید کانفیگتون رو بزارید تست بگیریم.

**Comment by babakbenam** [comment]
ba config pishfarz. aslan natonestam ip peida konam. man to terminal macOS sai kardam ip tamiz peida konam. to update haie gozashte ama tonestam az hamin ravesh ip tamiz peida konam va moshkeli nadashtam. vali alan Unexpected option: -v - this should not happen mizane.

**Comment by Jolge100** [comment]
> S

نسخه ویندوز روی ویندوز سرور تست گرفتم
و از کانفیگ default خودتون استفاده کردم 
هیچ ایپی رو بهم سالم نشون نمی ده و در واقع همه رو همین ارور می ده

**Comment by iSegaro** [comment]
سلام
این ارور
25 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)
مربوط به گواهی ssl و tls هست
اگه روی دامنه شخصی خودتون تست گرفتید و این ارور رو دارید قبلش باید هندشیک رو تست بگیرید مطمن بشید که مشکلی نداره و موفقیت امیز باشه اگه نبود از اکانت کلادفلر طبق توضیحی که توی دیسکاشن گذاشتم tls رو موقتا به ورژن 1 تغییر بدید

اگه دامنه در اختیار شما نست هیچ کاری از دست شما برنمیاد

**Comment by Jolge100** [comment]
> سلام این ارور 25 => One or more errors occurred. (The SSL connection could not be established, see inner exception.) مربوط به گواهی ssl و tls هست اگه روی دامنه شخصی خودتون تست گرفتید و این ارور رو دارید قبلش باید هندشیک رو تست بگیرید مطمن بشید که مشکلی نداره و موفقیت امیز باشه اگه نبود از اکانت کلادفلر طبق توضیحی که توی دیسکاشن گذاشتم tls رو موقتا به ورژن 1 تغییر بدید
> 
> اگه دامنه در اختیار شما نست هیچ کاری از دست شما برنمیاد

از همون اکانت default روی نرم افزار استفاده کردم و این ارور رو می گیرم متاسفانه
خودم اکانتی اضافه نکردم

**Comment by goingfine** [comment]
سرور ایرانه دیگه؟ شاید نت سرور داستان خاص خودش رو داره
برنامه رو دیباگ بالا بیارید لاگشو بزارید

Close the app
Make an empty file in the app folder and name it `enable-debug`
Run the app and do some scan.
Then in the app folder find `debug.txt` file.
Attach it here to see if we can have some more info about your issue.

**Comment by Jolge100** [comment]
این ارور رو می گیرم


```
App started. Version: 1.0.8470.31454
OS: Microsoft Windows 10.0.20348 X64, Cpu Arch: X64, Framework: .NET 6.0.14
2023/03/12 09:25:51 Start fronting check, timeout: 5, Resolver IP: , withCustumDNSResolver: False
2023/03/12 09:25:51 Starting fronting check with url: https://speed.cloudflare.com/__down?bytes=1000
2023/03/12 09:25:52 Fronting check done in 515 ms, content: '00000000000000000000000000000000000000000000000000'
2023/03/12 09:25:57 Starting scan engine with target speed: 100000, dl timeout: 2, config: 'Default' => Default...
2023/03/12 09:25:57 
 ------- Start IP Check ------- 
2023/03/12 09:25:57 Start fronting check, timeout: 1, Resolver IP: 23.227.37.1, withCustumDNSResolver: True
2023/03/12 09:25:57 Starting fronting check with url: https://speed.cloudflare.com/__down?bytes=1000
2023/03/12 09:25:57 Fronting check had exception: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
2023/03/12 09:25:57 
------- End IP Check -------

2023/03/12 09:25:57 
 ------- Start IP Check ------- 
2023/03/12 09:25:57 Start fronting check, timeout: 1, Resolver IP: 23.227.37.2, withCustumDNSResolver: True
2023/03/12 09:25:57 Starting fronting check with url: https://speed.cloudflare.com/__down?bytes=1000
2023/03/12 09:25:57 Fronting check had exception: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
2023/03/12 09:25:57 
------- End IP Check -------

2023/03/12 09:25:57 
 ------- Start IP Check ------- 
2023/03/12 09:25:57 Start fronting check, timeout: 1, Resolver IP: 23.227.37.3, withCustumDNSResolver: True
2023/03/12 09:25:57 Starting fronting check with url: https://speed.cloudflare.com/__down?bytes=1000
2023/03/12 09:25:57 Fronting check had exception: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
2023/03/12 09:25:57 
------- End IP Check -------
```

**Comment by Jolge100** [comment]
راه حلی براش نیست ؟

**Comment by iSegaro** [comment]
دامنه مرتضی گویا فیلتر شده
یه تست هند شیک بگیر با ان دستور ببین چی بر مگردونه برای من که resolve نمیشه روی نت مخابرات
`.\v2ray.exe tls ping sudoer.net`

**Comment by Jolge100** [comment]
> .\v2ray.exe tls ping sudoer.net

واقعیتش اینو بلد نیستم چجوری باید انجام بدم
می شه بگید چجوری باید انجامش داد ؟

**Comment by Jolge100** [comment]
> 

بله الان که فیلتر شده ولی همون موقع success هم گرفته بودم و این مشکل پابرجا بود

**Comment by iSegaro** [comment]
این ارور دوتا دلیل بیشتر نداره
توی ورژن TLS که نمیشه هندشیک بشه با موفقیت 
یا فیلتر شدن دامنه
جز این چیز دیگه نیست
