### ISSUE TITLE
سرعت کم آی پی های کلاد فلر

### ISSUE THREAD

**Issue by shaaans260** [MortezaBashsiz/CFScanner#226]
من از دامنه of.to و کلادفلر طبق آموزش استفاده کردم و وصل شدم اما سرعتم خیلی پایینه
بین 2000 تا 3000 میلی ثانیه
در اسکنر بهترین آی پی را انتخاب میکنم اما بازم سرعت پایینه
مشکل ازکجاست؟
![Screenshot_۲۰۲۳۰۳۰۹_۱۰۵۱۰۵_v2rayNG](https://user-images.githubusercontent.com/19187707/223958435-9ecb0760-2b68-47d9-8ca0-99f96ef0f41b.jpg)

**Comment by MortezaBashsiz** [comment]
خیلی دلایل میتونه داشته باشه
و این مشکل اسکنر نیست
پیشنهاد میکنم که آی پی های دیگر از رنجهای دیگر رو هم تست بگیرید
اسکنر فقط برای پیدا کردن آی پی هایی هست که کار میکنن و یک پارامتری هم برای سرعت پاسخدهیشون نشون میده
ممکنه که همیشه درست نباشه
