### ISSUE TITLE
پیشنهاد گزینه‌های انتخابی برای کاربری راحت تر و فهم ساده‌تر برای استفاده

### ISSUE THREAD

**Issue by raminrez** [MortezaBashsiz/CFScanner#228]
سلام و درور فراوان از همه دوستانی که تلاش زیادی میکنند برای زنده نگه داشتن این اسکریپت و پیشرف روز به روزش

من پیشنهاد دارم٬ برای اینکه استفاده از اسکریپل راحت تر باشه٬‌برای قابلیت های مختلف گزینه به کاربر بدیم که:
1.  حدال میزان علم و کانفیگی که کاربر نیاز داره برای اجرای اسکریپت کمتر بشه.
2. از خطاهای تایپی هم حلوگیزی میشه. و کابر کمتر دچار سردرگمی میشه.

به‌طور مثال گزینه‌های: vpn, thr, try, s, type, mode
درصورتی که داخل دستور وارد نشده بود٬ یکی یکی با امکان انتخاب از یوزر پرسیده بشه

**Comment by MortezaBashsiz** [comment]
درود
ممنونم ولی تجربه ثابت کرده که این کار برای کاربر دشوار‌تر میشه
باید تا حد امکان اینترکشن رو بین کاربر و اسکریپت کم کرد
توی یک خط ورودی ها رو بدن بهتر هست
سپاس
