### ISSUE TITLE
خطا در محاسبه میانگین

### ISSUE THREAD

**Issue by 123asd321dsa** [MortezaBashsiz/CFScanner#229]
سلام
اول دوباره تشکر میکنم برای همه زحمات

یه مشکلی که هست وقتی میذاریم یه ای پی رو مثلا 4 بار تست کنه
اگه یکی از این تست ها ناموفق باشه، وقتی میخواد میانگین رو محاسبه کنه اون تست ناموفق رو 0 در نظر میگیره و عدد میانگین خیلی پایینتر و غیرواقعی تر میشه
مثلا:

`832,  1704   1625 DOWN FOR IP 45.87.175.131`

اینو گذاشته بودم 4 بار تست کنه، دوبار ناموفق بوده میانگینش شده 832!

**Comment by MortezaBashsiz** [comment]
درود
آره حواستون باشه
اشتباه حساب میکنه
سعی میکنم درستش کنم

**Comment by MortezaBashsiz** [comment]
resolved in latest update
