### ISSUE TITLE
Computational error

### ISSUE THREAD

**Issue by kiavash599** [MortezaBashsiz/CFScanner#242]
There is a computational error in the linux version.
The Average calculation is wrong, when the number of attempts is selected more than one time and some tryings are failed so their pings would be zero so it should not be included in average calculation.
Instance:
Number of the attempts: 3
Attempts 100/200/Failed
Program return: 100
But the correct answer should be: (100 + 200) / 2 = 150

**Comment by MortezaBashsiz** [comment]
It has been fixed in last version
Update your repository
