### ISSUE TITLE
Running in background, save console to log file

### ISSUE THREAD

**Issue by kiavash599** [MortezaBashsiz/CFScanner#243]
Please explain or added the _RUN IN BACKGROUND_ and _SAVING THE CONSOLE OUTPUT TO A FILE_ features with **setsid**  and   **> <file name> commands**

**Comment by MortezaBashsiz** [comment]
Since this process will take a long time and the command line arguments are too much
On the other hand, if the arguments passed wrongly in background noob users don't know how to kill it
we will not have this feature

**Comment by kiavash599** [comment]
Hi Morteza
Thanks for explanation 
    On Friday, March 10, 2023 at 08:02:23 AM GMT+1, Morteza Bashsiz ***@***.***> wrote:  
 
 


Closed #243 as not planned.
