### ISSUE TITLE
Docker on Mac

### ISSUE THREAD

**Issue by immasoud** [MortezaBashsiz/CFScanner#246]
سلام
میشه اسکریپت رو روی داکر روی مک (اپل سیلیکون) ران کرد؟ 
چون من همش ارور میگریم
<img width="1165" alt="Screenshot 1401-12-19 at 11 17 10" src="https://user-images.githubusercontent.com/49973074/224254909-9f7e819d-65f6-4be8-ac34-d71e3287ca37.png">

**Comment by MortezaBashsiz** [comment]
ایمیج داکری هم هست
پول کنید
ریپو را آپدیت کنید توی کانتینر
بعدش ران کنید
