### ISSUE TITLE
termux ترموکس

### ISSUE THREAD

**Issue by Alidkhh** [MortezaBashsiz/CFScanner#254]
روی ترموکس (termux) ارورمیده که فقط روی مک و لینوکس قابل اجراست
میشه جوری توسعه بدید که با ترموکس هم بشه رانش کرد؟
تشکر

**Comment by Alirezag23** [comment]
اول روی ترموکس با پایتون تست کردم به مشکل خوردم بعد با bash تست کردم مشکلی نداشت
اول با ایرانسل چند تا سرور گرفتم بعد اون سرور های که روی ایرانسل کار می کرد روی گذاشتم برای همراه اول تا اون های که روی هر دو تا اپراتور کار می کنه پیدا بشه
اگر شد می گم چیکار کردم

**Comment by MortezaBashsiz** [comment]
درود
دقت کنید خروجی رو با دقت بخونید
دیپندنسیا رو نصب کنید
مشکل نداره

**Comment by Alidkhh** [comment]
> اول روی ترموکس با پایتون تست کردم به مشکل خوردم بعد با bash تست کردم مشکلی نداشت اول با ایرانسل چند تا سرور گرفتم بعد اون سرور های که روی ایرانسل کار می کرد روی گذاشتم برای همراه اول تا اون های که روی هر دو تا اپراتور کار می کنه پیدا بشه اگر شد می گم چیکار کردم

با بش که تست میکنم ای پی های خیلی زیادی پیدا میکنه که خیلیاش وصل نمیشن و سرعتشون یه عددی بین 200 تا 205 هست برا شمام همینطوره؟اگ اینطور نیست راهنمایی میکنید چیکار کنم؟

**Comment by Alirezag23** [comment]
سرعت بیشتر IP های که پیدا می کنه برای من خوبه
اگر مشکل داری می تونی چند تا کار کنی اول از همه این که از config پیشفرض استفاده نکن و config رو برای اون سروری که داری تغییر بده(اگر سرور شخصی پشت کلود فلر هست یا فری نود یا هر روش دیگه ای مهم نیست)
دوم سرعت اینترنت خودت رو اول بدون VPN بگیر مثلا ۲ مگابایت بر ثانیه هست یکم کمتر از سرعتی که داری رو به ورودی بده(bash cfScanner.sh -vpn YES -m SUBNET -t BOTH -thr 32 -try 1 -c config.json -s 1500 یه همچین چیزی باشه)

بعد از این که به مقدار کافی IP پیدا کرد فایل مربوط به IP ها رو با این دستور باز کن sort -n -r FILENAME | less این طوری IP ها رو به ترتیب سرعت می چینه (برای خروج q رو بزن)
من این کار ها رو می کنم و برای من خوب جواب داده

**Comment by Alirezag23** [comment]
> > اول روی ترموکس با پایتون تست کردم به مشکل خوردم بعد با bash تست کردم مشکلی نداشت اول با ایرانسل چند تا سرور گرفتم بعد اون سرور های که روی ایرانسل کار می کرد روی گذاشتم برای همراه اول تا اون های که روی هر دو تا اپراتور کار می کنه پیدا بشه اگر شد می گم چیکار کردم
> 
> با بش که تست میکنم ای پی های خیلی زیادی پیدا میکنه که خیلیاش وصل نمیشن و سرعتشون یه عددی بین 200 تا 205 هست برا شمام همینطوره؟اگ اینطور نیست راهنمایی میکنید چیکار کنم؟

سرعت بیشتر IP های که پیدا می کنه برای من خوبه
اگر مشکل داری می تونی چند تا کار کنی اول از همه این که از config پیشفرض استفاده نکن و config رو برای اون سروری که داری تغییر بده(اگر سرور شخصی پشت کلود فلر هست یا فری نود یا هر روش دیگه ای مهم نیست)
دوم سرعت اینترنت خودت رو اول بدون VPN بگیر مثلا ۲ مگابایت بر ثانیه هست یکم کمتر از سرعتی که داری رو به ورودی بده(bash cfScanner.sh -vpn YES -m SUBNET -t BOTH -thr 32 -try 1 -c config.json -s 1500 یه همچین چیزی باشه)

بعد از این که به مقدار کافی IP پیدا کرد فایل مربوط به IP ها رو با این دستور باز کن sort -n -r FILENAME | less این طوری IP ها رو به ترتیب سرعت می چینه (برای خروج q رو بزن)
من این کار ها رو می کنم و برای من خوب جواب داده
