### ISSUE TITLE
نکات مهم استفاده از اسکنر نسخه ویندوز

### ISSUE THREAD

**Issue by alireza1027** [MortezaBashsiz/CFScanner#257]
### Discussed in https://github.com/MortezaBashsiz/CFScanner/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **iSegaro** March  7, 2023</sup>
سلام
خوب برای استفاده از اسکنر نسخه ویندوز قبل از استفاده نیاز هست که نکاتی رو چک کنید تا بتونید بهترین خروجی رو از برنامه بگیرید.
اگه کانفیگ های v2ray شما بر روی سرور شخصی هستند یا از سرورهای رایگان استفاده میکنید یا اینکه دامین شخصی یا مجانی دارید و متصل کردید به کانفیگ هاتون قبل استفاده از اسکنر نکات زیر رو حتما رعایت کنید تا ببینید میتونید از اسکنر استفاده کنید یا نه , بعد از چک کردن هم در اخر چندین نمونه ساختار کانفیگ ها رو برای شما قرار میدم که براساس اون استفاده و اسکن رو انجام بدید.

- نکته مهم اینکه همونطور که میدونید این اسکنر فقط بر اساس CDN کلادفلر هست پس تمامی کانفیگ های شما چه پولی چه مجانی باید پشت CDN کلادفلر باشند.

آموزش ویدیویی استفاده از اسکنر نسخه ویندوز در کانال تلگرام اضافه شده و لینکش در انتهای همین مطلب قرار داده شده , خیلی مهم هست ابتدا تمامی مطالب این صفحه رو بخونید و سپس آموزش ویدیویی رو ببینید تا درک کنید سازوکار استفاده رو

1. نکته اول چک کردن قابلیت TLS HandShake :
برای اینکه اسکنر بتونه اسکنش رو انجام بده قابلیت هندشیک حتما باید برقرار باشه , برای این منظور وارد فولدر برنامه اسکنر بشید و روی یه فضای خالی از فولدر کلید شیفت کیبورد رو نگه دارید و راست کلیک کنید و Open in Windows Terminal رو بزنید , مانند تصویر

![image](https://user-images.githubusercontent.com/121983867/223519546-bd59c500-ff5c-4284-a5af-89c9a1e8e1d2.png)

** دوستانی که گزینه open in terminal رو توی منوی راست کلیک ندارن، توی آدرس بار بالای همون پوشه برنامه کلیک کنن و تایپ کنن cmd اینتر بزنن terminal همون پوشه باز میشه براشون.

بعد از این کار در محیط ترمینالی که برای شما باز میشه عبارت زیر را بنویسید و Enter را بزنید :

> .\v2ray.exe tls ping example.com

در اینجا example.com منظور ادرس دامنه ای هست که به سرور(شخصی یا مجانی) متصل هست به عنوان مثال :

> .\v2ray.exe tls ping replit.isegaro.click

ادرس replit.isegaro.click اشاره داره به ادرس دامنه ای که به یک سرور پشت کلادفلر لینک شده , نتیجه مانند عکس زیر باید عبارت handshake succeeded را برای ما نشان دهد , بعد از موفقیت امیز بودن امکان استفاده از اسکنر برای ما وجود دارد , مانند تصویر

![image](https://user-images.githubusercontent.com/121983867/223523085-abc55690-d1f4-4a19-910c-112a49a83ab0.png)

اگر نتیجه TLS Handshake موفقیت امیز نبود به صورت موقت در کلادفلر ورژن TLS رو روی مقدار یک تنظیم کنید و دوباره تست بگیرید , نتیجه موفقیت امیز خواهد بود , فراموش نکنید بعد از اینکه کارتون با اسکنر تموم شد دوباره TLS رو به اخرین ورژن برگردونید

![image](https://user-images.githubusercontent.com/121983867/224009162-0123fa80-7dce-45c5-9e5d-4cec09db517e.png)

2. ساختار کانفیگ هایی که میتونیم در اسکنر استفاده کنیم :

**نحوه تنظیم کانفیگ های شخصی برای کار با برنامه**
برای استفاده از کانفیگ های شخصی خودتون در برنامه فقط کافیه فایل json کانفیگ رو باز کنید و دو نقطه از اون رو ویرایش کنید تا کانفیگ توسط برنامه قابل استفاده باشد. تغییرات مورد نظر ما در دو بخش inbound و outbound باید اعمال شوند. این دو بخش را در کانفیگ پیدا کنید، در بخش inbound به مانند کد زیر در مقابل بخش port باید کلمه `PORTPORT `و حتما داخل گیومه قرار داده شود:

```
{
  "inbounds": [{
    "port": "PORTPORT", 
    "listen": "127.0.0.1",
    "tag": "socks-inbound",
    "protocol": "socks",
    "settings": {
...
```

در قسمت outbound باید به دنبال کلمه address بگردید و در مقابل آن عبارت `IP.IP.IP.IP` را به مانند زیر قرار دهید:

```
 "outbounds": [
    {
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "IP.IP.IP.IP", 
...
```

در ادامه میتوانید نمونه های کانفیگ های مختلف v2ray را مشاهده نمایید:

کانفیگ های V2ray بر اساس پروتکل های مختلف ماننده VMESS , VLESS , TROJAN کار میکنند که هر کدام از این پروتکل های ترنسپورت های مختلفی مثل وبسوکت WS , تی سی پی TCP , جی ار پی سی GRPC و ... دارند که شما از تمامی انها امکان استفاده در اسکنر رو دارید فقط باید اطلاعات ساختار Template انها را رعایت کنید که نمونهای صحیح انها در اینجا قرار داده میشه , دقت کنید در این ساختار ها فقط در قسمت outbounds ما باید مشخصات کانفیگ شامل 5 قسمت Port , UUID, PATH , HOST , SNI را تغییر بدیم که با عبارت xxxxx مشخص شده , پس هرجا که عبارت xxxxx وجود داره رو فقط بسته به کانفیگ خودتون تغییر بدید و در باقی کدها تغییری انجام ندهید.
در اینجا چند نمونه از کانفیگ های پر طرفدار به عنوان نمونه برای شما قرار میدهیم.

1-2 ساختار کانفیگ Vmess+WS+TLS :
```
{
  "inbounds": [{
    "port": "PORTPORT", 
    "listen": "127.0.0.1",
    "tag": "socks-inbound",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    }
  }],
  "outbounds": [
    {
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "IP.IP.IP.IP", 
        "port": xxxxx,
        "users": [{"id": "xxxxx" }]
      }]
    },
		"streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
            "headers": {
                "Host": "xxxxx"
            },
            "path": "xxxxx"
        },
        "tlsSettings": {
            "serverName": "xxxxx",
            "allowInsecure": false,
			"fingerprint": "chrome",
			"alpn": [
			"http/1.1"
			]
        }
    }
	}],
  "other": {}
}
```
2-2 ساختار کانفیگ Vless+GRPC+TLS :

```
{
  "inbounds": [{
    "port": "PORTPORT", 
    "listen": "127.0.0.1",
    "tag": "socks-inbound",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    }
  }],
  "outbounds": [
    {
    "protocol": "vless",
    "settings": {
      "vnext": [{
        "address": "IP.IP.IP.IP", 
        "port": xxxxx,
        "users": [{"id": "xxxxx",
		"encryption": "none"
			}]
      }]
    },
		"streamSettings": {
        "network": "grpc",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "xxxxx",
          "alpn": [
            "http/1.1"
          ],
          "fingerprint": "chrome"
        },
        "grpcSettings": {
          "serviceName": "",
          "multiMode": false
        }
      }
	}],
  "other": {}
}
```
3-2 ساختار Trojan+WS+TLS :

```
{
  "inbounds": [{
    "port": "PORTPORT", 
    "listen": "127.0.0.1",
    "tag": "socks-inbound",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    }
  }],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "IP.IP.IP.IP",
            "method": "chacha20",
            "ota": false,
            "password": "xxxxx",
            "port": xxxxx,
            "level": 1,
            "flow": ""
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "xxxxx",
          "alpn": [
            "http/1.1"
          ],
          "fingerprint": "chrome"
        },
        "wsSettings": {
          "path": "xxxxx",
          "headers": {
            "Host": "xxxxx"
          }
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    }
  ],
  "other": {}
}
```

4-2 ساختار کانفیگ Vless+WS+TLS :

```
{
"inbounds": [{
    "port": "PORTPORT", 
    "listen": "127.0.0.1",
    "tag": "socks-inbound",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    }
  }],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [{
        "address": "IP.IP.IP.IP", 
        "port": xxxxx,
        "users": [{"id": "xxxxx",
		"encryption": "none"
			}]
      }]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "xxxxx",
          "alpn": [
            "http/1.1"
          ],
          "fingerprint": "chrome"
        },
        "wsSettings": {
          "path": "xxxxx",
          "headers": {
            "Host": "xxxxx"
          }
        }
      }
    }
  ],
	"other": {}
}
```
برای استفاده از این ساختار ها کافیست ابتدا اطلاعات مورد نیاز کانفیگ مثل Port , UUID, PATH , HOST , SNI را در یکی ازین ساختارها که با xxxxx مشخص شده پرکنید و سپس ساختار رو در یک فایل با فورمت json ذخیره کنید مثلا به صورت config.json و اون رو در برنامه مثل تصویر زیر اضافه کنید و اسکن رو انجام بدید :

![Untitled](https://user-images.githubusercontent.com/121983867/223538375-f902351d-fef8-4845-af55-db5f31fea124.png)

**آموزش ویدیویی استفاده از اسکنر در کانال تلگرام زیر
https://t.me/isegaro/15**

با تشکر از @MortezaBashsiz و @goingfine که در تهیه این برنامه زحمات بسیار زیادی کشیدند که در دنیا نمونه نداره
درصورتی که نیاز به آموزش جهت دریافت کانفیگ و سرور و دامنه های رایگان داشتید از طریق توییتر و کانال تلگرام من میتونید استفاده کنید
https://twitter.com/iSegaro
https://t.me/isegaro
سگارو 1401.12.16</div>

**Comment by goingfine** [comment]
این الان یعنی چی؟
همون متن رو گذاشتین اینجا؟
