### ISSUE TITLE
. \v2ray.exe tls ping mydomain   سوال در مورد

### ISSUE THREAD

**Issue by mohsen-armoun** [MortezaBashsiz/CFScanner#259]
سلام ، من وقتی از این دستور `v2ray.exe tls ping mydomain\.` استفاده میکنم برای دامنه شخصی خودم
هربار با جواب مختلفی روبرو میشم دلیلش چی میتونه باشه ؟؟  و آیا مشکلی هست ؟
@iSegaro
@goingfine 
@MortezaBashsiz 

> [mydomain] = Hide my domain
> ip.ip.ip.ip = Hide My Server IP

Network For test Irancell
=============
```
Pinging without SNI
Handshake succeeded
Allowed domains:  [mydomain]
```
=============
```
Pinging with SNI
handshake succeeded
Allowed domains:  [mydomain]
Tls ping finished
```
=============
```
Pinging with SNI
handshake failure:  read tcp 192.168.70.51:16021->ip.ip.ip.ip:443: wsarecv: An
 existing connection was forcibly closed by the remote host.
Tls ping finished
```
=============
```
Pinging without SNI
Handshake failure:  read tcp 192.168.70.51:16147->ip.ip.ip.ip:443: wsarecv: An
 existing connection was forcibly closed by the remote host.
```
=============
```
Pinging without SNI
Handshake failure:  EOF
```
=============

**Network For Test ADSL**

`Failed to resolve IP: lookup  [mydomain]: no such host
`

**Comment by iSegaro** [comment]
سلام فقط یه چیزی به ذهنم میرسه تست باید بگیری
دامنه یا ساب دامنه شما فیلتر هست یا جعل گواهی ssl اتفاق میوفته تو زمان های مختلف
وقتی پیام خطا میده دامین شما روی اون اوپراتور یا اون اینترنت مشکل داره
ادرس دامنت رو در ساعت های مختلف تست بگیر توی مرورگر تایپ کن ببین ارور 503 میگیری
اگه میگیری مشکل از جعل گواهی روی اوپراتور اینترنتت هست کاری از دستت ساخته نیست

**Comment by mohsen-armoun** [comment]
حالت عادی دامنه اصلیم روی همه اوپراتورا اوکی هست و وا میشه
ولی به قول خودت ساب دامین روی ایرانسل اوکی هست ولی روی همراه اول و ADSL مشکل داره
احتمال اینکه ساب دامنه رو زده باشن بیشتره یا مشکل ssl ؟؟؟
