### ISSUE TITLE
مشکل مک 

### ISSUE THREAD

**Issue by am-fallah** [MortezaBashsiz/CFScanner#262]
روی Mac OS 11.7.2 این اتفاق برای من میوفته 
با ورژن های قبلی اوکی بود و کار میکردم با اونا 
توی این آپدیت جدید اینطوری شده 
![photo_2023-03-11_17-53-51](https://user-images.githubusercontent.com/72158271/224495800-9ffda81e-742b-409a-bedc-2c4813848af3.jpg)

**Comment by MortezaBashsiz** [comment]
با آپدیت جدید برطرف شد
