### ISSUE TITLE
نسخه ویندوز حاوی تروجان است

### ISSUE THREAD

**Issue by mohsenmz2012** [MortezaBashsiz/CFScanner#265]
سلام چرا توی نسخه ویندوز تروجان گذاشتین؟

https://www.virustotal.com/gui/file/81d84e1c360ba6f81a9b2b115f92a2833c125a92687d8f745b7ffae9b430d0cb/detection

**Comment by goingfine** [comment]
دوست عزیر معلوم نیست فایلی که ائلود کردین چه مشکلی داشته ولی این اسکن مستقیم از ادرس دانلود همین ریلیز روی ویروس توتال که کاملا پاک هست

https://www.virustotal.com/gui/url/e0a04632732dddc255ed9d1b3a5b5ca75c145efd8b750596e76cde09e3461ef1/details

ضمنا همون اسمن خودتون هم فقط یک انتی ویروس بهش گیر داده که حتما فالس پازیتیو هست

**Comment by goingfine** [comment]
همون یک مورد هم فقط به v2ray.exe گیر داده

![image](https://user-images.githubusercontent.com/126115050/224507353-52decc40-a0a3-4a6d-b71b-d128cca4fe75.png)

**Comment by goingfine** [comment]
با بررسی بیشتر نکته بعدی اینکه هش v2ray.exe ایکه توی فایل شما هست با چیزی که ما توی فایل قرار دادیم فرق میکنه:

![image](https://user-images.githubusercontent.com/126115050/224507738-56e6e69d-61fe-474d-98b3-ec52529eef16.png)

شما یا فایلتون به هر نحوی در میانه راه الوده شده یا اینکه چز دوستان ارتش سایبری هستید.
