### ISSUE TITLE
seq: invalid floating point argument

### ISSUE THREAD

**Issue by prxpostern** [MortezaBashsiz/CFScanner#267]
سلام من خطای زیر رو دارم چکار کنم
FAILED 45.95.241.249
seq: invalid floating point argument: ‘’
Try 'seq --help' for more information.

دستوری که زدم این بوده
bash cfScanner.sh -vpn YES -m SUBNET -t DOWN -thr 8 -c config.real -f custom.subnets
داخل فایل هم یک سابنت بیشتر نیست.

ممنون میشم راهنمایی کنید

LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

**Comment by MortezaBashsiz** [comment]
تعداد try رو هم مشخص کنید
پیشفرض نداره

**Comment by MortezaBashsiz** [comment]
مقدار پیشفرض در آپدیت جدید اعمال شد

**Comment by prxpostern** [comment]
خیلی ممنون . کار کرد. فقط دوتا مساله یکی اینکه اگر بشه حداقل سرعت رو مشخص
کرد خیلی خوبه. و یکی اینکه اگر کانفیگ خودم VMESS WS نباشه. مثلا Trojan GRPC
یا VLESS TCP یا هرچیز دیگه چطور میشه بجای Config.real بنویسمش . یک نمونه
فایل جامع وجود داره که از روی اون انجام بدم ؟
