### ISSUE TITLE
پایتون نسخه مک

### ISSUE THREAD

**Issue by raminrez** [MortezaBashsiz/CFScanner#269]
هیچ چیزی داخل فایل ریسالت ذخیره نمیشه!
```
ip,avg_download_speed,avg_upload_speed,avg_download_latency,avg_upload_latency,avg_download_jitter,avg_upload_jitter,download_speed_1,upload_speed_1,download_latency_1,upload_latency_1
```

این کل نتیجه برسی آی‌پی هست. که میتونم بگم بالای ۴۰تا OK داشته

**Comment by tempookian** [comment]
توی دایرکتوری result بایستی برای هر بار که کد رو ران می‌کنید یک فایل بر اساس زمان شروع تست باشه. من الآن روی مک تست گرفتم و با حالت‌های مختلف فایل خروجی درست بود. لطف کنید بگید دقیقا با چه دستوری ران می‌کنید. 

لطفا از روی شاخه dev یه بار دیگه امتحان کنید و نتیجه رو اعلام کنید. سپاس

**Comment by raminrez** [comment]
تست رو از روی Dev ران کردم و فایل بدون هیچ مشکلی ایجاد شد
با سپاس
