### ISSUE TITLE
نحوه تکمیل فایل کانفیگ

### ISSUE THREAD

**Issue by sahelefarda** [MortezaBashsiz/CFScanner#274]

**Comment by sahelefarda** [comment]
فایل کانفیگ را چطور با اطلاعات خود تکمیل کنیم؟

**Comment by tempookian** [comment]
لطفا بیشتر توضیح بدید. از کدوم نسخه استفاده می‌کنید؟ (bash, python, go lang, windows)
و منظورتون از فایل کانفیگ چه فایلیه.

**Comment by sahelefarda** [comment]
> لطفا بیشتر توضیح بدید. از کدوم نسخه استفاده می‌کنید؟ (bash, python, go lang, windows) و منظورتون از فایل کانفیگ چه فایلیه.

از کد python استفاده میکنم.
python3 cfFindIP.py --threads 8 --config ./myconfig.json

**Comment by tempookian** [comment]
اینا رو باید از کانفیگ vmess ws tls خودتون جایگزین کنید.

- id: the uuid you use for the config
- host: the actual host for example: example.test.com
- path: the path in your vmess ws tls config (endpoint) 
- servername: sni: for example 248ecb72-89cf-5be7-923f-b790fca681c5.test.com

برای servername اون قسمت اول رو هر چیزی می‌تونید بذارید

**Comment by tempookian** [comment]
البته که می تونید کد رو با همون کانفیگ (بدون استفاده از کانفیگ خودتون و با کانفیگ سرور sudoer) هم ران کنید. یعنی:
```bash
curl -o myconfig.json https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/bash/ClientConfig.json
curl -o mysubnets.selection https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/bash/cf.local.iplist
python3 cfFindIP.py  --threads 8 --config ./myconfig.json --subnets ./mysubnets.selection
```
