### ISSUE TITLE
آپدیت

### ISSUE THREAD

**Issue by xlirezx** [MortezaBashsiz/CFScanner#275]
بعد از ریلیز شدن آپدیت جدید و دانلود اون، اسکن‌های قبلی و کانفیگهایی که انجام شده و عملا پوشه اکسترکت شده قبلی رو به دلیل جایگزینی کامل فایل ورژن جدید از دست میدیم.

**پیشنهاد:**
اگر امکانش باشه که آپدیت رو بزنیم، فایلهای جدید خود به خود در پوشه کنونی دانلود و جایگزین بشه و بقیه فایلهای موجود دست نخورده باقی بمونه خیلی عالی میشه.

**Comment by goingfine** [comment]
فعلا پوشه results رو بریزید از قبلی به جدیده
