### ISSUE TITLE
try در ویندوز

### ISSUE THREAD

**Issue by megasoheilsh** [MortezaBashsiz/CFScanner#276]
سلام ، 
لطفا امکانی بذارید که امکان تست دانلود رو بشود حذف کرد و فقط ایپی که کار میکند رو تست بگیرد ، حجم ترافیک مصرفی به شدت زیاد شده با قابلیت تست دانلود حتی با تنظیم 20 کیلوبایت 
لطفا ویژگی try با انتخاب تعداد آن به نسخه ویندوز اضافه شود
 با تشکر

**Comment by goingfine** [comment]
گزینه یک کیلو بایت بزاریم خوبه؟

**Comment by goingfine** [comment]
به اخرین ریلیز اضافه شد

**Comment by zoheirkabuli** [comment]
> به اخرین ریلیز اضافه شد

دیدم دمت گرمه
