### ISSUE TITLE
Avoid os/exec in golang

### ISSUE THREAD

**Issue by EbrahimTahernejad** [MortezaBashsiz/CFScanner#278]
Hello,

Could you please use xrayCore.Instance to launch a v2ray instance instead of using os/exec?

There is basically no point in re-writing the code in go if you are not going to use the library instead of the v2ray binary.

This can make a great tool to embed in our apps.

Thank you

**Comment by SonyaCore** [comment]
hi 
yes I will add this enhancement in a future update
