### ISSUE TITLE
ایجاد ۲ قابلیت جدید و کاربردی

### ISSUE THREAD

**Issue by Morghak963** [MortezaBashsiz/CFScanner#282]
سلام ،لطفا اگر امکان خروجی گرفتن بصورت فایل اکسل رو هم اضاف کنید عالی میشه، اینطوری میشه با هر اپراتور اسکن کرد و در فایل اکسل خروجی گرفت و آی پی های مشترکی که روی همه اپراتور ها کار میکنن رو مشخص کرد
یا حداقل این قابلیت در خود برنامه ایجاد بشه که یک آی پی مشترک بین چندین اسکن رو که پینگ خیلی خوبی میده مشخص کنه و به کاربر پیشنهاد بده

مورد بعد اینکه قابلیت تست آپلود آی پی ها اگر به نرم افزار اضاف بشه خیلی کمک کنندست،اکثر آی پی ها سرعت دانلود خوبی دارن ولی سرعت آپلود تعداد اندکی معقول هست فقط

**Comment by raminrez** [comment]
با اسکریپت پایتون خروجی اکسل میگیرید
