### ISSUE TITLE
No VPN mode

### ISSUE THREAD

**Issue by raminrez** [MortezaBashsiz/CFScanner#283]
@SonyaCore  @tempookian 

سلام دوستان
لطفاً این امکان رو فعال کنید تا حالت NO_VPN هم برای تست آی‌پی ها وجود داشته باشه. خیلی سرعت تست نهایی رو بالا میبره. البته من اینو از آموزش مرتضی یاد گرفتم

و یک سؤال اینکه٬ اسکریپت های `پایتون` و `گو` امکان این‌رو دارند که فقط آی‌پی لیست بگیرند؟ یا فقط سابنت قبول میکنند
اگر که دارند لطفا داکیومنت رو تغییر بدید تا همه متوجه وجود این قابلیت بشند

**Comment by tempookian** [comment]
سلام. بله در پایتون این امکان وجود داره

‍``--novpn``               If passed, test without creating vpn connections

در پایتون فایل شما می‌تونه حتی ترکیب این دو باشه یعنی یه سری خطا آیپی و یه سری خطا سابنت (CIDR)

**Comment by raminrez** [comment]
بسیار عالی
لطفا داکیومنتیشن بروز کنید تا راحت متوجه وجودش بشیم 🙏

**Comment by raminrez** [comment]
من الان گذاشتم روی حالت --novpn تست کنه
ولی هیچ خروجی OK نداره
درصورتی که توی همین رنج با v2ray , xray خروجی میده

**Comment by tempookian** [comment]
> من الان گذاشتم روی حالت --novpn تست کنه ولی هیچ خروجی OK نداره درصورتی که توی همین رنج با v2ray , xray خروجی میده

همچین حالتی رو غیرمحتمل نمی‌دونم ولی لطفا خط دستورتون رو بذارید که بررسی کنم

**Comment by raminrez** [comment]
عذرخواهی میکنم. بسته اینترنتی که باهاش تست میکردم تمام شده بود و باعث این بود که همش خطا میداد
مشکل برطرف شد

ولی الا سوالی که دارم. در حالت `--novpn` فقط پینگ میگیره یا تست دانلود هم میگیره؟ 
چون با توجه به فایل ریسالت داره تست دانلود هم میگیره!
حالا نمیدونم این باعث میشه لیست قابل اعتمادتر باشه؟ یا فقط پینگ گرفتن میتونه لیست آی‌آماده برای تست به ما بده

**Comment by tempookian** [comment]
این حالت تنها کاری که می‌کنه اینه مرحله ایجاد ارتباط از طریق xray یا v2ray رو حذف می‌کنه. یعنی عملا تمام انتظارات دیگه که بهش می‌دید برقرارن از جمله کمینه سرعت دانلود و آپلود و ...

**Comment by raminrez** [comment]
متوجه شدم. من الان` download-speed = 0` ست کردم و الان مشخصا دانلود و آپلود نداره.
latency همون نتیجه پینگ آی‌پی میشه؟

**Comment by SonyaCore** [comment]
> متوجه شدم. من الان` download-speed = 0` ست کردم و الان مشخصا دانلود و آپلود نداره. latency همون نتیجه پینگ آی‌پی میشه؟



> @SonyaCore @tempookian
> 
> سلام دوستان لطفاً این امکان رو فعال کنید تا حالت NO_VPN هم برای تست آی‌پی ها وجود داشته باشه. خیلی سرعت تست نهایی رو بالا میبره. البته من اینو از آموزش مرتضی یاد گرفتم
> 
> و یک سؤال اینکه٬ اسکریپت های `پایتون` و `گو` امکان این‌رو دارند که فقط آی‌پی لیست بگیرند؟ یا فقط سابنت قبول میکنند اگر که دارند لطفا داکیومنت رو تغییر بدید تا همه متوجه وجود این قابلیت بشند

درود
ببینید توی نسخه گولنگ شما هم میتونید آی پی بدید هم سابنت بدید
خود برنامه میاد این هارو پارس میکنه آی پی های لیست رو اسکن میکنه 
حتی میتونید دستی آی پی رو وارد کنید به جای وارد کردن فایل که فقط اون cidr یا آی پی مورد اسکن قرار بگیره 


در نسخه گولنگ به صورت پیشفرض بدون وی پی ان آی پی ها اسکن میشه و اگر میخواهید آی پی ها را با v2ray اسکن کنید به سادگی از فلگ vpn-- 
استفاده کنید 

و اگر برای مثال فایل v2ray با سیستم عامل شما سازگار نبود میتونید از فلگ v2ray-path استفاده کنید که دایرکتوری v2ray یی که دانلود کردید رو مشخص کنید و برنامه از اون باینری برای اسکن آی پی ها استفاده میکنه

**Comment by tempookian** [comment]
> متوجه شدم. من الان` download-speed = 0` ست کردم و الان مشخصا دانلود و آپلود نداره. latency همون نتیجه پینگ آی‌پی میشه؟

نه latency کل مسیر رفت و برگشت (round trip time)‌ رو حساب می‌کنه در حالی که پینگ یک طرفه‌ست.

من با توضیحاتی که داده شد می‌بندم اگر موردی بود خوشحال می‌شیم ایشوی جدید باز کنید. سپاس از همراهی
