### ISSUE TITLE
EOL CR LF

### ISSUE THREAD

**Issue by pulsarice** [MortezaBashsiz/CFScanner#288]
It seems like cfscanner (bash version) is sensitive to EOL character.
If I create a custom.ip.list in windows (which uses CR LF at the end of each line) and transfer it to linux server and start the test, all IPs will fail. 
Converting EOL char to linux format (LF) will resolve the isuue.

Is it possible to rectify this in the script?

**Comment by MortezaBashsiz** [comment]
Hi
Since this script is not compatible with Windows and works only on Linux and Mac we will not proceed this type of incompatibility to resolve
You need to prepare your files for Bash Environments 
To solve this you can simply use `unix2dos` and `dos2unix` tools to convert your file

Thanks
