### ISSUE TITLE
قابلیت تست آی پی ها به صورت رندوم در نسخه ویندوزی

### ISSUE THREAD

**Issue by yasbs** [MortezaBashsiz/CFScanner#289]
سلام خوب هستین.ممنون از برنامه خفنتون.خواستم آگه میشه یه گزینه هم قرار بدین که برنامه خودش آی پی ها رو به صورت رندوم بیاد تست کنه به جای اینکه رنج رنج و پشت سر هم بره جلو اینجوری به نظرم خیلی سریع تر میشه هم به آیپی و هم به رنج آی‌پی که توش بیشترین احتمال وجود آی‌پی های تمیز هست رسید.بازم ممنون از زحماتی که میکشین.به درود

**Comment by goingfine** [comment]
به اخرین ریلیز اضافه شد

**Comment by yasbs** [comment]
واقعاااااااا دستتون طلا مرسی که هستین
