### ISSUE TITLE
 اضافه کردن لیست ایپی برای نسخه ویندوز

### ISSUE THREAD

**Issue by kamiepic** [MortezaBashsiz/CFScanner#295]
خسته نباشید و خیلی ممنون بابت برنامه خوبتون, ای کاش بشه مثلا 100تایی ایپی سالم داریمو بدیم به برنامه که تست کنه
با ایپی range خواستم تست کنم نشد و ارور میداد

**Comment by tempookian** [comment]
لطفا مشخص کنید از چه نسخه‌ای استفاده می‌کنید؟ ویندوز؟ بش؟ پایتون؟ گولنگ؟ ...

**Comment by kamiepic** [comment]
نسخه ویندوز
ویرایش کردم .عذر میخوام بابت مشخص نکردنش

**Comment by goingfine** [comment]
از منوی فایل گزینه Import scan results هست دیگه
