### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by kazem3d** [MortezaBashsiz/CFScanner#307]
in python when request for "cidrs from asn lookup" encounter with 403 error 
![Screenshot from 2023-03-18 14-13-38](https://user-images.githubusercontent.com/46394776/226100723-fb9c686e-a804-4aa2-aa18-6cac531ea4d6.png)

Screenshots are attatched

**Comment by tempookian** [comment]
Thank you for reporting. In this cases (and almost in all cases) it is recommended to use your own list of subnets.

```bash
curl -o subnets.list https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/bash/cf.local.iplist
curl -o myconfig.json https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/bash/ClientConfig.json
python3 cfFindIP.py --threads 8 --config myconig.json --subnets subnets.list
```

In the future update we will take care that we do not only rely on asnlookup. PRs are also welcome in this regard :)

**Comment by kazem3d** [comment]
thanks
