### ISSUE TITLE
Fronting Errors

### ISSUE THREAD

**Issue by nwhdesign** [MortezaBashsiz/CFScanner#308]
Top Fronting Errors: (16)
16 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)

**Comment by tempookian** [comment]
لطفا مشخص کنید از کدوم نسخه برنامه استفاده می‌کنید؟ ویندوز؟ بش؟ پایتون؟ گولنگ؟ ...

**Comment by goingfine** [comment]
این پیام الزاما خطا و مشکل نیست

**Comment by nwhdesign** [comment]
داداش آخرین نسخه اره متوجه شدم که این هست نیست اما یه مشکلی هست با نت همراه و ایرانسل اصلا آیپی اسکن نمیکنه اما با نت وایفا خونگی می‌کنه خیلیام این مشکل رو دارن

**Comment by nwhdesign** [comment]
داداش آخرین نسخه اره متوجه شدم که این هست نیست اما یه مشکلی هست با نت همراه و ایرانسل اصلا آیپی اسکن نمیکنه اما با نت وایفا خونگی می‌کنه خیلیام این مشکل رو دارن
