### ISSUE TITLE
Send scan results to a path and address (endpoint)

### ISSUE THREAD

**Issue by iran-free-net** [MortezaBashsiz/CFScanner#311]
سلام و وقت بخیر
لطفا با توجه به این که بیشتر کاربران احتمالا از نسخه ویندوزی استفاده می کنند، درخواست این رو داشتم که قابلیت ارسال دیتاها به یک url address و path یا همون (Endpoint) در این نسخه اضافه بشه لطفا که بشه از این نسخه در صورتی که کاربر علاقه داشت در انتهای اسکن یک json که زحمت ساختش رو کشیدید post بشه به endpoint بدون اینکه نیاز باشه fork مجزایی کسی انجام بده

ممنون می شم اگر از این جهت کمک کنید

Environment: Windows

**Comment by goingfine** [comment]
فعلا توی برناممون نیست
