### ISSUE TITLE
مشکل نت همراه اول و ایرانسل

### ISSUE THREAD

**Issue by nwhdesign** [MortezaBashsiz/CFScanner#313]
سلام وقت بخیر با نت همراه اول و ایرانسل نمیشه از برنامه استفاده کرد لطفا بررسی کنید

**Comment by armanem2** [comment]
سلام موقع اسکن ایپی روی نت همراه اول (بدون کانفیگ شخصی) اصلا جواب نمیدهد ولی روی رایتل اغلب جواب میده

**Comment by MortezaBashsiz** [comment]
درود
این مشکل اسکریپت نیست
دامنه پیشفرض استفاده شده فیلتر شده
اگه کانفیگ شخصی دارید استفاده کنید
اگه ندارید صبر کنید تا کانفیگ پیشفرض آپدیت بشه
