### ISSUE TITLE
درسته دامنه پیش فرض فیلتره اما وقتی مشخصات سرور خودمونم میزنیم میاد برای هر ایپی یه .JSONمیسازه وتست انجام نمیده 

### ISSUE THREAD

**Issue by armanem2** [MortezaBashsiz/CFScanner#317]
درسته دامنه پیش فرض فیلتره اما وقتی مشخصات سرور خودمونم میزنیم میاد برای هر ایپی یه .JSONمیسازه وتست انجام نمیده ایپی روی نت همراه وایرانسل اسکن نمیکنه اگر اموزش خاصی داره بی زحمت بگین مال ای سگارو رو کامل انجام دادم درست نشد

**Comment by MortezaBashsiz** [comment]
لطفا مشخص کنید که از چه ورژن و نسخه ای استفاده میکنید
ویندوز لینوکس و ...
و با چه پارامترایی ران میکنید
کلا جزییات بیشتری رو بگید
نکته دیگر اینه که ممکنه روی اون پروایدر مشکل باشه و روی یک پروایدر اینترنت دیگه درست باشه

**Comment by armanem2** [comment]
نسخه ویندوز اخرین نسخه کانفیگ دستی وارد میکنم ارور میده روی رایتل وصل میشه ولی روی همراه اول ایرانسل خیر

**Comment by armanem2** [comment]
بنظرم اگه زحمتی نیست یک ویدیوامورشی برای ران کردن در حالت سرور شخصی توی یوتیوب منتشر کنین اقامرتضی متشکرم دوسددارم شدییید

**Comment by MortezaBashsiz** [comment]
درود
وقتی که روی رایتل میشه ولی روی همراه اول نمیشه یعنی اینکه در فرآیند مشکلی نیست
سعی میکنم یه آموزش براش درست کنم
سپاس
