### ISSUE TITLE
درخواست اضافه کردن امکان بررسی مجدد یا همان try  ویندوز

### ISSUE THREAD

**Issue by megasoheilsh** [MortezaBashsiz/CFScanner#318]
سلام ، همانطور که در نسخه لینوکسی امکان try یک ایپی به دفعات وجود دارد ، لازم است این امکان نیز در نسخه ویندوزی اضافه شود ، چون هر بار اسکن متفاوت با دفعه بعد آن می باشد . 
اگر به فرض امکانی بذارید که ایپی رو چند بار تست بگیره ممنون میشیم

**Comment by goingfine** [comment]
این امکان هست تو برنامه 
![](https://user-images.githubusercontent.com/126115050/224505365-0d3a3f7a-8871-4a2c-8216-46db636390c5.png)

**Comment by megasoheilsh** [comment]
> این امکان هست تو برنامه ![](https://user-images.githubusercontent.com/126115050/224505365-0d3a3f7a-8871-4a2c-8216-46db636390c5.png)

بله ولی اول باید ایپی پیدا بشه ؟ ایپی که پیدا شد دیگه اهمیتی نداره چند بار تستش

**Comment by megasoheilsh** [comment]
اضافه کردی برادر عزیز؟

**Comment by goingfine** [comment]
نه فعلا تو برناممون نیست
