### ISSUE TITLE
چطوری از کانفیگ شخص توی برنامه ویندوز استفاده کنیم 

### ISSUE THREAD

**Issue by nwhdesign** [MortezaBashsiz/CFScanner#320]
سلام از اونجایی که کانفیگ پیشفرض کار نمیکنه خواستم بدونم چطوری باید از کانفیگ شخصی خودم استفاده کنم ؟

**Comment by MortezaBashsiz** [comment]
مقادیر رو مشابه ClientConfig.json پر کنید در فایل دیگری ذخیره کنید و به عنوان ورودی بدید به اسکریپت

**Comment by nwhdesign** [comment]
از نسخه ویندوز استفاده میکنم چطور باید اعمال کنم ؟

**Comment by goingfine** [comment]
از منوی Tools گزینه add custom config رو بزنید 
قبلش هم راهنماش رو حتما بخونید:
https://github.com/MortezaBashsiz/CFScanner/discussions/210
