### ISSUE TITLE
عدم کارکرد تست اپلود اسپید

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#327]
از امروز upload speed رو نمی شه روی لینوکس چک کرد و همه رو failed می زنه
ممنون می شم بررسی کنین

**Comment by MortezaBashsiz** [comment]
درود
لطفا دستورتون رو بنویسید که چطور اجراش میکنید
آپشنهاتون چیاست

**Comment by Jolge100** [comment]
بله الان فیکس شده
خیلی خیلی ممنونم
