### ISSUE TITLE
طریقه آپدیت اسکریپت ؟

### ISSUE THREAD

**Issue by HamidOffline** [MortezaBashsiz/CFScanner#330]
سلام و درود خدمت شما ... تشکر بابت اسکریپت بسیار کاربردی 

خواستم بدونم ما باید چجوری این اسکریپت رو آپدیت کنیم 

کد دستوریش چیه

**Comment by MortezaBashsiz** [comment]
اگه با گیت گرفتید
`git pull origin main`

یا اینکه کلا پاک کنید دوباره بگیرید

**Comment by HamidOffline** [comment]
با این دستور گرفتم
git clone https://github.com/MortezaBashsiz/CFScanner.git

اما کد دستوری که میزنم این خطا رو میزنه

 not a git repository (or any of the parent directories): .git
