### ISSUE TITLE
bug in check subnet mask

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#332]
وقتی 5-6 تا به بالا رنج ایپی گذاشته می شه توی نسخه جدید فقط خط اخر رو چک می کنه و بقیه این ارور رو می ده

`")syntax error: invalid arithmetic operator (error token is "`

ممنونم

**Comment by tempookian** [comment]
سلام از چه نسخه‌ای ( بش، پایتون، گولنگ، ویندوز،...) استفاده می‌کنید؟

**Comment by Jolge100** [comment]
از bash استفاده می کنم

**Comment by MortezaBashsiz** [comment]
درود
لطفا محتویات فایل سابنت‌هاتون رو بزارید اینجا
دقت کنید که اصلا نباید خط خالی داشته باشه
و اینکه اون فایل رو حتما توی لینوکس درست کنید
اگه توی مثلا ویندوز درست کنید با فرمت داس ذخیرش میکنه و توی لینوکس قابل خواندن نیست
برای تبدیلش میتونید از دستور `dos2unix` استفاده کنید

**Comment by Jolge100** [comment]
> درود لطفا محتویات فایل سابنت‌هاتون رو بزارید اینجا دقت کنید که اصلا نباید خط خالی داشته باشه و اینکه اون فایل رو حتما توی لینوکس درست کنید اگه توی مثلا ویندوز درست کنید با فرمت داس ذخیرش میکنه و توی لینوکس قابل خواندن نیست برای تبدیلش میتونید از دستور `dos2unix` استفاده کنید

بله مشکل همین بود و الان درست شده
ممنونم
