### ISSUE TITLE
Instructions about how to use personal domain to CNAME on default domain

### ISSUE THREAD

**Issue by armanshahrisa** [MortezaBashsiz/CFScanner#337]
Thank you very much for developing this program. I can't thank you enough for it.

I think the default domain address is blocked in my area. I couldn't find the actual address that is used to test IP addresses. If I know the host domain, I could use my own domain to redirect to the default server hostname. This would help me to get the working IP addresses even if the default domain is blocked.

**Comment by MortezaBashsiz** [comment]
Please give us more details
Which distro are you using?
What is your issue with the script?
What you mean by default domain?

**Comment by armanshahrisa** [comment]
Sorry, I should have mentioned more details. I'm using the windows version. To connect to Cloudflare CDN, one would need a domain name and a working IP address from Cloudflare. I think "815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net" is the address that the software uses. If it is blocked one day, I could redirect an address such as "freeinternet.tk" to "815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net" using a CNAME entry and then scan IP adresses with "freeinternet.tk" instead. Am I right?

**Comment by MortezaBashsiz** [comment]
Hi
Thanks
But it will not work since we only accept *.shcree.net domain

**Comment by armanshahrisa** [comment]
You should receive data on *.shcree.net because the personal domain doesn't do anything but redirect everything to *.shcree.net. The only benefit is that my ISP thinks I'm connecting to another website. But behind the scene, the Cloudflare DNS converts the personal address to *.shcree.net and then tries to contact it. Wouldn't it work?

**Comment by MortezaBashsiz** [comment]
Strongly suggest to read this article 
https://www.cloudflare.com/learning/dns/dns-records/dns-cname-record/
```
A frequent misconception is that a CNAME record must always resolve to the same website as the domain it points to, but this is not the case. The CNAME record only points the client to the same IP address as the root domain. Once the client hits that IP address, the web server will still handle the URL accordingly. So for instance, blog.example.com might have a CNAME that points to example.com, directing the client to example.com’s IP address. But when the client actually connects to that IP address, the web server will look at the URL, see that it is blog.example.com, and deliver the blog page rather than the home page.
```
