### ISSUE TITLE
Rarallel Error 

### ISSUE THREAD

**Issue by HoseinGhadiri** [MortezaBashsiz/CFScanner#35]
I got this error on Ubuntu 22.04 and 20.4 after run bash command. 

Unknown option: ll
Usage:

parallel [options] [command [arguments]] < list_of_arguments
parallel [options] [command [arguments]] (::: arguments|:::: argfile(s))...
cat ... | parallel --pipe [options] [command [arguments]]

-j n            Run n jobs in parallel
-k              Keep same order
-X              Multiple arguments with context replace
--colsep regexp Split input on regexp for positional replacements
{} {.} {/} {/.} {#} {%} {= perl code =} Replacement strings
{3} {3.} {3/} {3/.} {=3 perl code =}    Positional replacement strings
With --plus:    {} = {+/}/{/} = {.}.{+.} = {+/}/{/.}.{+.} = {..}.{+..} =
                {+/}/{/..}.{+..} = {...}.{+...} = {+/}/{/...}.{+...}

-S sshlogin     Example: foo@server.example.com
--slf ..        Use ~/.parallel/sshloginfile as the list of sshlogins
--trc {}.bar    Shorthand for --transfer --return {}.bar --cleanup
--onall         Run the given command with argument on all sshlogins
--nonall        Run the given command with no arguments on all sshlogins

--pipe          Split stdin (standard input) to multiple jobs.
--recend str    Record end separator for --pipe.
--recstart str  Record start separator for --pipe.

See 'man parallel' for details

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

**Comment by KourosZanbouri** [comment]
discussed in #34 

Parallel Official Version ( GNU parallel version 20210822 ) has no "--ll" parameters.

You have two options:
1- remove "--ll" from the code ( Line 238):
`parallel --bar -j "$threads" fncCheckSubnet ::: "$ipList" ::: "$progressBar" ::: "$resultFile" ::: "$scriptDir" ::: "$configId" ::: "$configHost" ::: "$configPort" ::: "$configPath" ::: "$configServerName" ::: "$osVersion"`


2- install parallel community maintained packages ( Parallel 20230122):
https://build.opensuse.org/package/show/home:tange/parallel

**Comment by KourosZanbouri** [comment]
discussed in #34 ,

Update your parallel package:
https://ftpmirror.gnu.org/parallel/parallel-latest.tar.bz2
