### ISSUE TITLE
Repeated searching of subnets

### ISSUE THREAD

**Issue by behnam8612** [MortezaBashsiz/CFScanner#356]
In the new version of Linux, when we give a subnet as an input, it searches it twice as if it is in a loop.

**Comment by MortezaBashsiz** [comment]
Thanks
Could you plz share your command how you execute?

**Comment by behnam8612** [comment]
[~/CFScanner/bash]>$ bash cfScanner.sh -vpn YES -m SUBNET -t UP -thr 8 -try 4 -c config.real -s 100 -f mycustom.subnets
example mycustom.subnets is: 45.85.118.0/23

**Comment by MortezaBashsiz** [comment]
It will split the subnet /23 to two subnet /24
I think this is the reason that you feel it is twice
Could you test it with one /24 subnet?

**Comment by behnam8612** [comment]
thank you
It works correctly only in the case that the subnet is 23/, and in the rest of the cases, it rescans the first subnet in a repeated loop. I also did the clone operation from the beginning, I even used my personal config, but The scan was like this

**Comment by MortezaBashsiz** [comment]
Thanks
Fixed
