### ISSUE TITLE
E: Unable to locate package ...

### ISSUE THREAD

**Issue by statueliberty** [MortezaBashsiz/CFScanner#358]
![error](https://user-images.githubusercontent.com/43316127/229502434-d7952e69-4d17-4236-aab5-8beadf43089d.png)
Hi ,
I attempted to install the recommended packages for CFScanner on Ubuntu, however an error occurred when I attempted to install "getopt," "tput," and "shuf."

The other packages installed correctly.
I was wondering if someone could assist me.

Greetings and thank you.

**Comment by MortezaBashsiz** [comment]
Hi

At first try to run the script, it will alert you which packages are not installed
but for tput you need to install ncurses-bin
please Google how to install your dependencies
