### ISSUE TITLE
assigen delay 0 when target speed is off.

### ISSUE THREAD

**Issue by DgithubA** [MortezaBashsiz/CFScanner#359]
سلام و ممنون از زحمات شما آقای باشسیز عزیز.
من با کانیفیگی که خودم ساختم و import کردم وقتی target speed رو میزارم روی no speed test پینگ ایپی های پیدا شده رو 0 میده. و نمیگه چه پینگی دارن. همه 0 میشن. ولی وقتی Target speed میزارم درست کار میکنه و مشکلی نداره
![Screenshot 2023-04-03 152402](https://user-images.githubusercontent.com/56259646/229502012-26cd958c-f2c3-4df7-98e1-acd22377e917.png)

**Desktop (please complete the following information):**
 - OS:WINDOWS 11
 - Version 11

**Comment by goingfine** [comment]
اسمش هست No download لذا چیزی دانلود نمیکنه که بخواد تاخیرش رو نشون بده. تو این حالت فقط تست فرانتینگ انجام میشه و سرعت و تاخیری محاسبه نمیشه
