### ISSUE TITLE
عدم تغییر رنج برای اسکن

### ISSUE THREAD

**Issue by retina20** [MortezaBashsiz/CFScanner#360]
در نسخه bash در اپدیت اخر اسکریپت زمانی که یک رنج ای پی را اسکن کرد و تمام شد دوباره همان رنج را اسکن میکند. همچنین با دستور CTRL+C رنج اسکیپ نمیشود و دوباره همان رنج قبلی را اسکن میکند.

**Comment by MortezaBashsiz** [comment]
Duplicated #356
