### ISSUE TITLE
مشکل محاسبه آپلود و دانلود اسپید نسخه پایتون

### ISSUE THREAD

**Issue by retina20** [MortezaBashsiz/CFScanner#363]
در نسخه پایتون زمانی که مقادیر آپلود و دانلود تست وارد میشود. بعد از اسکن ای پی ها , مقدار ها را به اشتباه قیاس میکند(پیوست عکس مشخص میکند که مقدار 50 برای اپلود تنظیم شده و در صورتی که ای پی عدد بالاتری را برای دانلود داده ولی به اشتباه ان ای پی را نادیده میگیرد.)

https://pasteboard.co/ICIkUvc8YZ0T.png

**Comment by tempookian** [comment]
درود. سپاس بابت اطلاع‌رسانی. مشکل در پرینت بود و در نسخه جدید بایستی برطرف شده باشه. اگر این‌طور نبود ممنون می‌شم مجددا issue بذارید
