### ISSUE TITLE
 پیدا نکردن ip پس از اپدیت رفع خطای اسکن چندین باره سابنت ها در نسخه bash

### ISSUE THREAD

**Issue by retina20** [MortezaBashsiz/CFScanner#366]
در نسخه جدید پس از رفع مشکل لوپ در سابنت ها , اسکریپت دچار اختلال شده و هیچگونه ای پی پیدا نمیکند.
برای اطمینان از مشکل اسکریپت در نسخه جدید ؛ با نسخه قبل همان سابنت را بررسی کردم و ای پی ها سالم پیدا شد.
همچنین برای اطمینان بیشتر با چند isp در سابنت هایی که در حال حاظر بدون مشکل فعال است ؛ نسخه اخر را بررسی کردم و هیچگونه ای پی پیدا نکرد.
با تشکر

**Comment by MortezaBashsiz** [comment]
درود
تغییری در اون قسمت اتفاق نیفتاده و من همین الان تست گرفتم کار میکنه
حتی همین الان هم خیلیا دارن استفاده میکنن
شما با کانفیگ خودتون تست می‌گیرید یا با کانفیگ پیش‌فرض اسکریپت؟
لطفا دستورتون رو رنج آی پی هایی که اسکن میکنید رو هم بگید

**Comment by MortezaBashsiz** [comment]
چون خبری نشد
تیکت رو میبندم
اگه مشکلی داشتید مجدد بازش کنید
