### ISSUE TITLE
نسخه ویندوز مشکل عدم اسکن 

### ISSUE THREAD

**Issue by HamidOffline** [MortezaBashsiz/CFScanner#368]
سلام من هرچی اسکن رو میزنم هیچ آی پی پیدا نمیکنه برام |:

**Comment by MortezaBashsiz** [comment]
درود
یکم توضیحات بیشتری بدید که با چه پارامترایی اجرا میکنید
کدوم سابنت‌ها رو اسکن میکنید
کدوم اوپراتور اینترنت رو دارید
و این نکته رو هم در نظر بگیرید که ممکنه دامنه پیشفرض برای شما فیلتر باشه

**Comment by goingfine** [comment]
همین بالایی و اینکه نتیجه تست دیاگنوس خودتون رو بزارید
راهنما: https://github.com/MortezaBashsiz/CFScanner/discussions/331

**Comment by hamidv** [comment]
سلام مرتضی جان ممنون بابت همه ی زحماتت. من قبلا با اسکنر شما می تونستم آی پی پیدا کنم. ولی اخیرا اصلا خروجی نمیده. از کانفیگ شخصی استفاده میکنم. با ایرانسل و همراه اول هم چک کردم.

**Comment by HamidOffline** [comment]
سلام دوباره 

مرتضی جان من روی همه اوپراتور ها تست گرفتم هیچ خروجی آی پی نداره یعنی هیچ آی پی پیدا نمیکنه 

دامنه پیشفرض فیلتر نیست برام اما من دامنه رو هم تغییر دادم بازم  هیچ آی پی برام پیدا نمیکنه

**Comment by PERSIA-MISI** [comment]
سلام
من تا 5-6 روز پیش به راحتی با اسکنر ویندوز برای همه اپراتورها و کانفیگهای شخصی و رایگانم آی پی تمیز پیدا میکردم اما الان 5-6 روزه با هیچ کانفیگی نمیتونم حتی یه آی پی برای همرا اول از نرم افزار خروجی بگیرم اگر هم بعد 3 ساعت یکی دو تا پیدا کنه عملا اینقدر پینگشون بالاست که تقریبا کار نمیکنن اما ایرانسل و بقیه بدون مشکل هست هنوز چی شده این چند روز که چند نفر اینجا مشکل منو تا حدود زیادی دارن؟
با آپدیت میشه حلش کنید؟ضمنا دامنه هام سالمه چون با آی پی که از دوستان گرفتم همراه اولم وصل میشه

**Comment by goingfine** [comment]
وقتی فرانتیگ انجام میشه یعنی دامنه تست فیلتر نیست

**Comment by PERSIA-MISI** [comment]
کسی نیست یه جواب درست بده مشکل ما حل بشه ؟

**Comment by MortezaBashsiz** [comment]
درود
وقتی که روی نت همراه اول جواب نمیده ولی روی بقیه نت ها جواب میده یعنی اینکه اسکنر مشکل نداره
ممکنه شما یه جایی رو اشتباه رفته باشید
ممکنه دامنه فیلتر شده باشه
ممکنه که اون مدلی که ما تست میگیریم اختلال روش اومده باشه
خیلی دلایل دیگه میتونه داشته باشه

**Comment by PERSIA-MISI** [comment]
سلام و عرض تشکر
آقا مرتضی من از اولی که این اسکنرو ریلیز کردید بارها و بارها با این اسکنر با کانفیگها و دامنه ها و اپراتورهای مختلف کار کردم و همه زیر و بمشو میدونم و کامل دستم اومده چطور باید باهاش کار کنم و تا ده روز پیش خوب کار میکرد همه جور کانفیگ و دامنه چه شخصی و رایگان روش تست کردم اما اصلا همراه اول دیگه آی پی نمیده البته اینم بگم با کانفیگ پیش فرض اسکنر هم تست کردم و از فایل دباگ فهمیدم وقتی همراه اول میخواد تست دانلود بگیره این آدرس که روی اسکنر ست شده فیلتر شده:
https://speed.cloudflare.com
روی ایرانسل هم چند روزه داره بازی در میاره اما همراه اول حداقل توی شهر من این آدرسو کلا بسته همینطوری هم میزنم این آدرس باز نمیشه!
میشه چیزی جایگزینش کنید و از فیلترچی مخفیش کنید؟
جالب اینجاست با پایتون هم وقتی تست میگیرم برای همراه اول هیچی پیدا نمیکنه اگر آدرسی که ازش تست میگیرن همینه مشکل از همینجاست!
اگر امکانش هست یه کاری برای این مشکل بکنید من با هیچ روش دیگه ای نتونستم به دقیقی اسکنر شما آی پی تمیز بگیرم.
با سپاس

**Comment by PERSIA-MISI** [comment]
سلام و عرض تشکر
آقا مرتضی من از اولی که این اسکنرو ریلیز کردید بارها و بارها با این اسکنر با کانفیگها و دامنه ها و اپراتورهای مختلف کار کردم و همه زیر و بمشو میدونم و کامل دستم اومده چطور باید باهاش کار کنم و تا ده روز پیش خوب کار میکرد همه جور کانفیگ و دامنه چه شخصی و رایگان روش تست کردم اما اصلا همراه اول دیگه آی پی نمیده البته اینم بگم با کانفیگ پیش فرض اسکنر هم تست کردم و از فایل دباگ فهمیدم وقتی همراه اول میخواد تست دانلود بگیره این آدرس که روی اسکنر ست شده فیلتر شده:
https://speed.cloudflare.com
روی ایرانسل هم چند روزه داره بازی در میاره اما همراه اول حداقل توی شهر من این آدرسو کلا بسته همینطوری هم میزنم این آدرس باز نمیشه!
میشه چیزی جایگزینش کنید و از فیلترچی مخفیش کنید؟
جالب اینجاست با پایتون هم وقتی تست میگیرم برای همراه اول هیچی پیدا نمیکنه اگر آدرسی که ازش تست میگیرن همینه مشکل از همینجاست!
اگر امکانش هست یه کاری برای این مشکل بکنید من با هیچ روش دیگه ای نتونستم به دقیقی اسکنر شما آی پی تمیز بگیرم.
با سپاس

**Comment by HamidOffline** [comment]
بالاخره با کانفیگ شخصی مشکلم حل شد 
مرسی بزرگوار  .. همه اوپراتور ها تست کردم اسکن میکنه

**Comment by MortezaBashsiz** [comment]
> سلام و عرض تشکر آقا مرتضی من از اولی که این اسکنرو ریلیز کردید بارها و بارها با این اسکنر با کانفیگها و دامنه ها و اپراتورهای مختلف کار کردم و همه زیر و بمشو میدونم و کامل دستم اومده چطور باید باهاش کار کنم و تا ده روز پیش خوب کار میکرد همه جور کانفیگ و دامنه چه شخصی و رایگان روش تست کردم اما اصلا همراه اول دیگه آی پی نمیده البته اینم بگم با کانفیگ پیش فرض اسکنر هم تست کردم و از فایل دباگ فهمیدم وقتی همراه اول میخواد تست دانلود بگیره این آدرس که روی اسکنر ست شده فیلتر شده: https://speed.cloudflare.com روی ایرانسل هم چند روزه داره بازی در میاره اما همراه اول حداقل توی شهر من این آدرسو کلا بسته همینطوری هم میزنم این آدرس باز نمیشه! میشه چیزی جایگزینش کنید و از فیلترچی مخفیش کنید؟ جالب اینجاست با پایتون هم وقتی تست میگیرم برای همراه اول هیچی پیدا نمیکنه اگر آدرسی که ازش تست میگیرن همینه مشکل از همینجاست! اگر امکانش هست یه کاری برای این مشکل بکنید من با هیچ روش دیگه ای نتونستم به دقیقی اسکنر شما آی پی تمیز بگیرم. با سپاس


حتی اگه اون دامنه رو هم فیلتر کرده باشن بازم نباید مشکلی باشه
چون ما خودمون اون دامنه رو دستی ریزالو میکنیم به آی‌پی مورد نظر و تست رو میگیریم
یعنی اصلا برای ریزالو دامنه هم سمت دی ان اس سرور نمیریم که فیلتر بشه
من به نظرم مشکل جای دیگریست
شاید همراه اول یه حرکتی زده

**Comment by goingfine** [comment]
@PERSIA-MISI 
توی لاگی برای همراه اول که گذاشتین داره فرانتینگ در هر دو حالت ریزالو و غیر ریزالو داره انجام میشه پس این ادرس speed براتون فیلتر نیست. چطور میگید فیلتره؟
