### ISSUE TITLE
randomness issue 

### ISSUE THREAD

**Issue by hamidrezaka** [MortezaBashsiz/CFScanner#369]
سلام رندومنس در مک کار نمی‌کند 
bash cfScanner.sh -v YES -m SUBNET -t BOTH -p 16 -r 1 -d 1000 -c config.real -s 100

لطفا راهنمایی کنید 
من از command بالا برای ران کردن اسکریپت استفادهع می‌کنم

**Comment by MortezaBashsiz** [comment]
درود
شما نباید رندومنس رو بیشتر از ۲۵۶ بگذارید
وقتی که اسکنر کار میکنه سابنت ها رو میشکنه به /۲۴ و داخل اونها رندومنس عمل میکنه
حالا توی هر سابنت /۲۴ تعداد ۲۵۶ عدد آی پی هست و وقتی شما رندومنس رو میزارید ۱۰۰۰ یعنی اینکه توی هر سابنت که ۲۵۶ تا آی پی داره به صورت رندوم ۱۰۰۰ عدد آی پی رو انتخاب کن که از نظر لاجیک عملا کار نخواهد کرد
پشنهادم اینه که رندومنس رو زیر ۲۰ بزارید در هر صورت

ممنونم که این موضوع رو مطرح کردید و باید حتما فایل توضیحات برنامه رو ویرایش کنم و این نکته رو لحاظ کنم که رندومنس نباید بیشتر از ۲۵۶ باشه
