### ISSUE TITLE
درصد پیشرفت در حالت لیست آی‌پی در نسخه بش

### ISSUE THREAD

**Issue by pulsarice** [MortezaBashsiz/CFScanner#370]
با سلام و تشکر
امکانش هست در حالت لیست آی‌پی، درصد پیشرفت هم نمایش داده بشه؟
(در نسخه بش)

**Comment by MortezaBashsiz** [comment]
درود
متاسفانه این قابل حل شدن نیست و در حال حاضر هم برنامه ای برای انجامش نداریم
ولی میتونید با رنگی شدن نوار پایین صفحه ببینید که چند درصد کل آی پی ها اوکی شده
سپاس
