### ISSUE TITLE
درخواست اضافه شدن Check Point برای ادامه جستجو بعد بستن برنامه

### ISSUE THREAD

**Issue by mohsen-armoun** [MortezaBashsiz/CFScanner#371]
**درخواست اضافه شدن قابلیت ذخیره  **
سلام لطفا اگه امکانش هست قابلیت ذخیره تعداد IP اسکن شده رو بزارین که بشه بعد بستن برنامه دوباره از چک پوینت قبلی شروع کرد و اسکن رو ادامه داد و هربار از اول دوباره جستوجو نکنه، به نظرم کاربردی هست

**Comment by MortezaBashsiz** [comment]
درود
مشخص کنید لطفا که از کدوم توزیع استفاده میکنید
بش و ویندوز و پایتون و .... ؟

**Comment by mohsen-armoun** [comment]
سلام مرتضی جان، خسته نباشی، نسخه ویندوز 32bit

**Comment by goingfine** [comment]
از حالت pause میتونید استفاده کنید
حالت مورد نظرتون تو برنامه مون نیست
