### ISSUE TITLE
نتیجه همواره فیل در مک ام ۲

### ISSUE THREAD

**Issue by hamidrezaka** [MortezaBashsiz/CFScanner#374]
سلام آیپی اسکنر دربرای مک ام ۲ کار نمی‌کند (یک آیپی تمیز را بصورت کاستوم تست می‌کنم ولی نتیجه رد حاصل می‌شود)

**Comment by MortezaBashsiz** [comment]
درود
لطفا بدون vpn هم تست بگیرید ببینید آیا همه فیل هست یا نه؟
و نتیجه را اینجا اطلاع بدید
سپاس

**Comment by hamidrezaka** [comment]
سلام وقتی وی پی ان را NO ست می‌کنم(v NO-) همان آیپی که مطمین هستم سالم است اوکی(سبز) می‌شود
@MortezaBashsiz

**Comment by MortezaBashsiz** [comment]
پس اسکریپت مشکلی نداره
دامنه توی کانفیگ پیشفرض برای شما فیلتر شده متاسفانه

**Comment by hamidrezaka** [comment]
سلام مجدد 
من دارم از کانفیگ خودم که برای لیت آیپی کار می‌کنه استفاده می‌کنم 
آیا روشن بودن وی پی ان (یعنی v yes-) برای نتیجه  تست اهمیت داره یا نه ؟ چون بدون با خاموش بودن وی پی ان هم می‌توانم تست کنم و بنظر اوکی است

**Comment by hamidrezaka** [comment]
@MortezaBashsiz لطفا راهنمایی بفرمایید

**Comment by MortezaBashsiz** [comment]
درود
ممکنه که کلا برای شما باینری موجود کار نکنه
۱. خودتون با باینری داخل اسکریپت و کانفیگ خودتون پورت بیارید بالا و با ساکس روی بروزر تست کنید ببینید کار میکنه یا نه
۲. اگه یک کار نکرد باینری رو باید عوض کنید
