### ISSUE TITLE
باگ در اسکن نسخه bash

### ISSUE THREAD

**Issue by admiraltidebringer** [MortezaBashsiz/CFScanner#376]
با سلام و خسته نباشید
نسخه آخر ورژن bash باگ داره. چند بار هم تست کردم. بعد یه مدت کار کردن به شکل درست به این وضع در میاد:(هیچ مشکل و ایرادی در اتصال به اینترنت و کانفیگ نیست. در ورژن قبلی این مشکل رو نداشتم.)

FAILED 104.30.24.252
FAILED 104.30.24.253
FAILED 104.30.24.254
| Progress bar of main IPs: [>                               ] 1.90%                               
| Progress bar of main IPs: [>                               ] 1.95%                               
| Progress bar of main IPs: [>                               ] 2.00%                               
| Progress bar of main IPs: [>                               ] 2.05%                               
| Progress bar of main IPs: [>                               ] 2.10%                               
| Progress bar of main IPs: [>                               ] 2.15%                               
| Progress bar of main IPs: [>                               ] 2.20%                               
| Progress bar of main IPs: [>                               ] 2.25%                               
| Progress bar of main IPs: [>                               ] 2.30%                               
| Progress bar of main IPs: [>                               ] 2.35%                               
| Progress bar of main IPs: [>                               ] 2.40%                               
| Progress bar of main IPs: [>                               ] 2.45%                               
| Progress bar of main IPs: [>                               ] 2.50%                               
| Progress bar of main IPs: [>                               ] 2.55%                               
| Progress bar of main IPs: [>                               ] 2.60%                               
| Progress bar of main IPs: [>                               ] 2.65%                               
| Progress bar of main IPs: [>                               ] 2.70%                               
| Progress bar of main IPs: [>                               ] 2.75%                               
| Progress bar of main IPs: [>                               ] 2.80%                               
| Progress bar of main IPs: [>                               ] 2.85%                               
| Progress bar of main IPs: [>                               ] 2.90%                               
| Progress bar of main IPs: [>                               ] 2.95%                               
| Progress bar of main IPs: [>                               ] 3.00%                               
| Progress bar of main IPs: [>                               ] 3.05%                               
| Progress bar of main IPs: [>                               ] 3.10%                               
| Progress bar of main IPs: [>                               ] 3.15%                               
| Progress bar of main IPs: [>                               ] 3.20%                               
| Progress bar of main IPs: [=>                              ] 3.25%                              
| Progress bar of main IPs: [=>                              ] 3.30%                              
| Progress bar of main IPs: [=>                              ] 3.35%                              
| Progress bar of main IPs: [=>                              ] 3.40%                              
| Progress bar of main IPs: [=>                              ] 3.45%                              
| Progress bar of main IPs: [=>                              ] 3.50%                              
| Progress bar of main IPs: [=>                              ] 3.55%                              
| Progress bar of main IPs: [=>                              ] 3.60%                              
| Progress bar of main IPs: [=>                              ] 3.65%                              
| Progress bar of main IPs: [=>                              ] 3.70%                              
| Progress bar of main IPs: [=>                              ] 3.75%                              
| Progress bar of main IPs: [=>                              ] 3.80%                              
| Progress bar of main IPs: [=>                              ] 3.85%                              
| Progress bar of main IPs: [=>                              ] 3.90%                              

و این رویه تا صد درصد شدن بدون اینکه اسکنی انجام بشه ادامه پیدا می کنه.

**Comment by MortezaBashsiz** [comment]
درود
متاسفانه این باگ از سمت ما نیست که درست بشه
حتما تغییری یا آپدیتی سمت شما بوده
نمایش پروگرس به این صورت ممکنه بخاطر تغییر در سایز ترمینال شما باشه
امیدوارم که بتونید حلش کنید
