### ISSUE TITLE
سوال / درخواست

### ISSUE THREAD

**Issue by mohsen-armoun** [MortezaBashsiz/CFScanner#380]
سلام و خسته نباشید 
چطور میشه تعداد تست روی آی پی رو تغییر داد ؟ میزان تاخیر رو با دانلود حساب میکنین ؟ 
آیا امکانش هست حالتی اضافه بشه که بسه چندبار تست رو انجام بده روی آی پی ؟ 
چون بعضی ip ها هستن مقطعی لحظه ای پینگ پایین دارن ولی در عمل پینگ بالا

**Comment by MortezaBashsiz** [comment]
درود
لطفا مشخص کنید از کدوم توزیع استفاده میکنید؟
بش ویندوز پایتون گو ....؟

**Comment by mohsen-armoun** [comment]
درود، نسخه ویندوز

**Comment by MortezaBashsiz** [comment]
این مورد همین الانم موجوده
میتونید لیست خودتون رو بدید و مشخص کنید که لیستتون رو چند بار انجام بده
و اینکه در برنامه هامون هست در آینده از ابتدا تست رو با تعداد انجام بده
