### ISSUE TITLE
مشکل اسکن در ویندوز

### ISSUE THREAD

**Issue by MasoodGharahi** [MortezaBashsiz/CFScanner#381]
سلام و خسته نباشید خدمت آقا مرتضی و بقیه دوستان. 
ممنونم از زحماتتون
چند روزی میشه توی ویندوز نمیتونم آی پی پیدا کنم
آی پی های سالمی هم که دارم رو توی قسمت Test a single Ip یا توی Diagnose و With Specific Ip Address وارد میکنم خطا میده و Now Working میزنه.
توی Diagnose خروجی Fronting  و v2ray.exe Execution مقدار Success هست ولی Download  مقدار Fail داره.
هم از کانفیگ دیفالت و هم از کانفیگ شخصی خودم تست کردم همینطور هست.
سلام و خسته نباشید خدمت آقا مرتضی و بقیه دوستان. 
ممنونم از زحماتتون
چند روزی میشه توی ویندوز نمیتونم آی پی پیدا کنم
آی پی های سالمی هم که دارم رو توی قسمت Test a single Ip یا توی Diagnose و With Specific Ip Address وارد میکنم خطا میده و Now Working میزنه.
توی Diagnose خروجی Fronting  و v2ray.exe Execution مقدار Success هست ولی Download  مقدار Fail داره.
هم از کانفیگ دیفالت و هم از کانفیگ شخصی خودم تست کردم همینطور هست.
![image](https://user-images.githubusercontent.com/72644643/230718110-c77f958a-ca08-4188-8aad-9f416957283e.png)

**Comment by peymanmohajer** [comment]
دقیقا من هم همین مشکل رو دارم ولی نکته ای که متوجه شدم اینه که تو فایل log که داخل فولدر برنامه هست اسکن آی پی ها نمایش داده میشه

**Comment by MasoodGharahi** [comment]
بله آی پی ها اسکن میشن ولی هیچکدوم آی پی سالم تشخیص داده نمیشه.

**Comment by goingfine** [comment]
گزینه دنلود تایم اوت رو از منوی tools روی عددهای بالاتر بزارید ببنید تغییری میکنه؟

احتمالا دارن روی نت مشکل ایجاد میکنن

**Comment by goingfine** [comment]
دامینمون هم فیلتر شده بود برای همین کار نمیکرد. بچه ها درست کردن. گزینه Update ClientConfig رو از منوی تولز بزنید
