### ISSUE TITLE
Proposal for an organised directory structure of the project

### ISSUE THREAD

**Issue by shobeira** [MortezaBashsiz/CFScanner#383]
It sounds more robust design if all the configuration files (such as custom.subnets, custom.ips, cf.local.iplist, and ClientConfig.json currectly located at https://github.com/MortezaBashsiz/CFScanner/tree/main/bash directory) move to a single "Configurations" directory rather than being in the bash directory. The bash directory could contain bash script and bash related files only, like what the purpose of the Golang, Python, and Docker directories is.

**Comment by MortezaBashsiz** [comment]
Thanks

We will try to refactor the structure later
