### ISSUE TITLE
on irancell the domains are filtered

### ISSUE THREAD

**Issue by SBK79** [MortezaBashsiz/CFScanner#4]
on irancell the shell returns an empty file, whats your solution for this?!

**Comment by SBK79** [comment]
the domains that you check with is filtered on irancell i think

**Comment by MortezaBashsiz** [comment]
What you got as an error?
Could you give me some more information?
Did you tried to open the url by yourself ?

**Comment by MortezaBashsiz** [comment]
Issue Closed
Feel free to reopen it
