### ISSUE TITLE
درخواست قراد دادن uTLS در اسکریپت لینوکس

### ISSUE THREAD

**Issue by xJuniorProgrammer** [MortezaBashsiz/CFScanner#405]
سلام
با توجه به اینکه در حال حاضر uTLS در بررسی آیپی تمیز تاثیر گذار هست درخواست قرار دادن  تنظیمات مربوط به utls را در اسکریپت لینوکس دارم مثلا randomized یا firefox_auto الان خوب کار میکنن. ولی Chrome ظاهرا مسدود شده

**Comment by MortezaBashsiz** [comment]
درود
سپاس
حتما بررسی میکنم
