### ISSUE TITLE
اسکن تصادفی

### ISSUE THREAD

**Issue by admiraltidebringer** [MortezaBashsiz/CFScanner#408]
درود آقا مرتضی ارادت
قابلیت shuffle تو نسخه آخر bash اضافه شده، می خواستم اگه براتون مقدوره یه flag اضافه کنید که این shuffle شدن اختیاری بشه.  می تونه برا مواقعی که اسکن رو تو چند بازه انجام می دیم کمک کنه.

**Comment by MortezaBashsiz** [comment]
درود
الان اختیاری هست و وقتی که ندید دیگه مثل قبل اسکن میکنه
ممکنه بیشتر توضیح بدید؟
