### ISSUE TITLE
v2ray -config

### ISSUE THREAD

**Issue by moslem7342** [MortezaBashsiz/CFScanner#41]
### این فایل های کانفیگ بدست اومده است:

![Screenshot from 2023-02-13 01-37-44](https://user-images.githubusercontent.com/31491742/218340723-2b64df24-5e65-4014-a3d5-34e494d53969.png)

### **که اولین مورد رو میخوام تست کنم : 34.43.179.1**

![Screenshot from 2023-02-13 01-36-07](https://user-images.githubusercontent.com/31491742/218340804-03163e0d-a319-449d-88c0-d1a6f6101d9a.png)

### طبق یک آموزش که از گیت هاب v2ray دیدم هاست و پورت رو از کانفیگ مورد نظر برداشتم و در تنظیمات پروکسی فایرفاکس قرار دادم

![Screenshot from 2023-02-13 01-38-39](https://user-images.githubusercontent.com/31491742/218341457-0ef7eedb-4558-4fed-8774-4ba8f681ddbd.png)

![Screenshot from 2023-02-13 01-37-20](https://user-images.githubusercontent.com/31491742/218341565-557545e1-f4ab-409d-a39a-ba0a64ad63c5.png)

بعد که میخوام یک سایت رو باز کنم ، خطای درون shell اتفاق می افتد و از حالت started خارج می شود.
--------------------
ممنون میشم طریقه ی استفاده از آی پی ها را در لینوکس بگید.
ممنون از کار ارزشمندتون . من فقط علاقه مند به لینوکس هستم و دانشی ندارم

**Comment by MortezaBashsiz** [comment]
درود
این مشکل برای v2ray هست و من واقعا نمیتونم کاریش بکنم
سپاس از شما
