### ISSUE TITLE
سوال در مورد پیدا کردن آی پی ها

### ISSUE THREAD

**Issue by vahidghadim** [MortezaBashsiz/CFScanner#410]
سلام دادا. اول ازت تشکر میکنم بابت این همه زحمت که برامون کشیدی و جرفه اول رو روشن کردی تا اینترنت داشته باشبم واقعا دمت گرم.
دوم یه سوالی داشتم، ما برای اسکن نیاز به اینترنت اون شبکه داریم، یعنی چی؟
مثلا ای پی ایرانسل بخواهیم باید به نت ایرانسل دسترسی داشته باشیم. یا از ای دی اس ال های خانگی بخواهیم اونم همینطور باید از اون شبکشون یه نتی وجود داشته باشه. حالا سوالم اینجاست میشه بدون دسترسی به اینترنت های مختلف برای اونا ای پی نمیزی بدست اورد؟ کاری که خودت اون اوایل کرده بودی؟

**Comment by MortezaBashsiz** [comment]
درود
بله باید اسکریپت از پشت اون اینترنت ران بشه
و اون کاری هم که قبلا کرده بودم این بود که اسکریپت رو بچه ها از پشت اینترنت مختلف اجرا میکردن

**Comment by vahidghadim** [comment]
اوکی دمت گرم دادا
