### ISSUE TITLE
اضافه کردن چند رنج آی پی

### ISSUE THREAD

**Issue by HosseinCods** [MortezaBashsiz/CFScanner#419]
چندین رنج آی پی به صورت پیشفرض در اسکنر نیستن که آی پی های تمیز خوبی داخلشون  پیدا میشه.
لیست پروژه [ircfspace](https://github.com/ircfspace/scanner) نسبتا کامله.

**Comment by MortezaBashsiz** [comment]
درود
لطفا اون رنجهایی که نیستن رو بگید

**Comment by HosseinCods** [comment]
من کامل مقایسه و تست و بررسی نکردم، اما این دو رنج رو خودم دارم استفاده میکنم، مخصوصا امروز روی ایرانسل که موارد قبلی از کار افتادن:
172.64.145.0/24
192.200.160.0/24

**Comment by MortezaBashsiz** [comment]
مرسی
این آي‌پی ها برای وایت‌لیست کلادفلر هست
سعی میکنیم اینارو هم اضافه بکنیم
https://www.cloudflare.com/ips-v4

**Comment by Yaghobbighob** [comment]
سلام. اسکنر صفا صفری هم رنج آی‌پی هایی داره که تو لیست شما نیست. لینک پروژه
https://github.com/SafaSafari/ss-cloud-scanner
لینک آی‌پی هاش
https://github.com/SafaSafari/ss-cloud-scanner/blob/main/ips.txt
