### ISSUE TITLE
The SSL connection could not be established

### ISSUE THREAD

**Issue by DgithubA** [MortezaBashsiz/CFScanner#422]
سلام دلیل ارور زیر چیست؟
```
Top Download Errors: (10)
9 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)
1 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)
```
کانفیگ شخصی هم زدم

**Comment by goingfine** [comment]
این الزاما خطانیست و خیلی از ip هایی که کار نمیکنن این خطا رو میدن

**Comment by goingfine** [comment]
از منوی تولز گزینه Update ClientConfig رو بزنید

اگر بازم پیدا نکرد گزینه time out رو هم روی عدد بالاتر بزارید. از همون منوی تولز
