### ISSUE TITLE
ارور نسخه جدید bash

### ISSUE THREAD

**Issue by ashaghal** [MortezaBashsiz/CFScanner#425]
environment: line 112: upTotalTime/upSuccessedCount : division by 0 (error token is "upSuccessedCount ")
![image](https://user-images.githubusercontent.com/39614484/231723446-cb23abad-8e36-4757-b52d-a9e0a9edf393.png)

**Comment by ashaghal** [comment]
> درود کامندتون رو چطوری ران میکنید لطفا بنویسید دستور کاملتون رو

bash cfScanner.sh -v YES -m SUBNET -t DOWN -p 8 -n 8 -s 100 -d 5 -u 0 -f my.subnets
در صورتی که -u رو برار 1 قرار بدم کد ران میشه. اما مسئه ای که هست که قبل از این آپدیت هم هیچوقت گزینه آپلود رو در تست ها فعال نمیکردم چون همیشه آپلود ها 0 نشون داده میشدن. اما الان اگر با دستور زیر هم اجرا کنم باز همین ارور رو دریافت میکنم.
bash cfScanner.sh -v YES -m SUBNET -t DOWN -p 8 -n 5 -s 100 -d 2  -f my.subnets

**Comment by MortezaBashsiz** [comment]
درود
این برطرف شد
لطفا آپدیت کنید نتیجه رو اطلاع بدید
سپاس
