### ISSUE TITLE
problem with vpn mode

### ISSUE THREAD

**Issue by navid221** [MortezaBashsiz/CFScanner#439]
سلام ببخشید میشه توضیح بفرمایید وقتی فایل json رو در روش لینوکسی به اسکریپت میدیم فرمتش باید چجوری باشه؟ من از همون روشی که سگارو توضیح داد رفتم جلو ولی هیج کدوم از آیپی های به دست اومده رو کانفیگ کار نمیکردن در حالی که مطمئن هستم بعضیاش کار میکنه. ممنون میشم یه ویدیو در مورد این موضوع بسازید

**Comment by MortezaBashsiz** [comment]
درود
فرمتش دقیقا شبیه فرمت فایل زیر باشه
مقادیر خودتون رو جایگذاری بکنید
https://github.com/MortezaBashsiz/CFScanner/blob/main/config/ClientConfig.json
سپاس
