### ISSUE TITLE
عدم عملکرد صحیح اسکن در حالت آی پی

### ISSUE THREAD

**Issue by mrmemrmemrme** [MortezaBashsiz/CFScanner#440]
سلام و درود
خسته نباشید
وقتی یک لیست آی پی جهت اسکن به نسخه Bash بدهیم، یا همه Faild میشوند یا فقط آخرین آی پی نتیجه صحیح در پی خواهد داشت.
با تشکر

**Comment by MortezaBashsiz** [comment]
درود
این خیلی بستگی به پارامترا هم داره
لطفا با آرگومانهای سبک ران کنید
و اینکه برای اینکه مطمین بشید که اسکریپت درست کار میکنه با وی پی ان خاموش تست کنید

![image](https://user-images.githubusercontent.com/19620677/231946108-ea3f2314-69f5-4bde-a077-50365f6591a7.png)

**Comment by mrmemrmemrme** [comment]
درود مجدد
با VPN خاموش و روشن تست کردم همینطوره
bash cfScanner.sh -c config.real -v YES -m IP -t UP -p 1 -n 1 -s 1 -f 222.iplist
ساب نت ها رو اسکن میکنم اوکی هست و همه ی آرگومان ها به درستی کار میکنند. فقط وقتی SUBNET رو تبدیل به IP میکنم و فایل آی پی بهش میدم، همه Faild میشن و آخرین آی پی لیست پاسخ درست میده. هر آی پی رو که بگذارم آخر لیست جوابش درست میشه ولی بقیه همه Faild میشن.
با تشکر

**Comment by MortezaBashsiz** [comment]
چرا سرعت رو ۱ گذاشتید؟
این غیرمنطقی هست بخاطر همین
لطفا سرعت رو بیشتر کنید بزارید مثلا ۱۰۰ تست بگیرید

**Comment by mrmemrmemrme** [comment]
![Screenshot (297)](https://user-images.githubusercontent.com/127270912/232018348-f4277070-9c5e-4f7a-ab6a-6e916fac28ae.png)

**Comment by MortezaBashsiz** [comment]
لطفا عین فایل iplist رو اینجا آپلود کنید

**Comment by mrmemrmemrme** [comment]
[cf.local2.txt](https://github.com/MortezaBashsiz/CFScanner/files/11231793/cf.local2.txt)
اینجا که خواستم آپلود کنم پسوندش رو ساپورت نمیکنه و اجازه آپلود نمیده. پسوند فایل رو به txt تغییر دادم تا بتونم آپلودش کنم. لطفا خودتون پسوندش رو بعد از دانلود به iplist تغییر بدید.

**Comment by mrmemrmemrme** [comment]
اینجا که خواستم آپلود کنم پسوندش رو ساپورت نمیکنه و اجازه آپلود نمیده. پسوند فایل رو به txt تغییر دادم تا بتونم آپلودش کنم. لطفا خودتون پسوندش رو بعد از دانلود به iplist تغییر بدید.

**Comment by MortezaBashsiz** [comment]
مشکل فرمت فایل شماست که با ویندوز درست شده
میتونید با کامند dos2unix تبدیلش کنید
توی عکس مشخصه
ایشو رو میبندم
موفق باشید

![image](https://user-images.githubusercontent.com/19620677/232026635-cf3472d5-e259-4834-8f63-4ec9a420f5b0.png)
