### ISSUE TITLE
Syntax error in termux (bash)

### ISSUE THREAD

**Issue by alefra1181** [MortezaBashsiz/CFScanner#441]
/data/data/com.termux/files/home/CFScanner/bash/../bin/v2ray[2]: syntax error: unexpected '('
درود آقا مرتضی برقرار باشی
تو ترموکس در حالت
-v YES
ارور بالارو میگیرم
ولی در حالت خاموشش این ارور نمیاد
دسترسی chmod رو هم دادم

cfScanner.sh: line 715: /tmp/adaspolo: No such file or directory

اینم هست

**Comment by MortezaBashsiz** [comment]
درود
مورد اول رو ما کاری نمیتونیم بکنیم
باینری v2ray توی ترموکس درست کار نمیکنه
مورد دوم رو امروز برطرف میکنیم
