### ISSUE TITLE
فیلتر شدن آدرس تست سرعت دانلود اسکنر ویندوز

### ISSUE THREAD

**Issue by PERSIA-MISI** [MortezaBashsiz/CFScanner#442]
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/11228428/debug.txt)
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/11228433/debug.txt)
سلام
آقا مرتضی میشه جواب بدید چرا ده روز هست من صد جور کانفیگ شخصی و رایگان با دامنه های مختلف با این اسکنر تست زدم روی همراه اول اما هیچ آی پی تمیزی پیدا نمیکنه در صورتی که ایرانسل و بقیه نتها با همین اسکنر و همین کانفیگها صد جور آی پی میتونم پیدا کنم!
جالب اینجاست مثلا آی پی تمیز میارم به صورت تکی هم با اسکنر روی همراه اول تست میکنم اما اصلا پینگ نمیده در صورتی که همین آی پی میبرم تو کانکشن V2rayng به خوبی کار میکنه!
احیانا میتونه این اسکنر شما از سمت همراه اول کار کردش مختل شده باشه؟
ضمنا با چندتا نت همراه اول و کامپیوتر هم تست کردم مطمئنم مشکل از سیستم یا نت موبایل خاصی نیست هر مشکلی هست در مورد ارتباط بین همراه اول و این اسکنر باید باشه لطفا اگر میشه یه کاری بکنید.
فایلهای دباگ هم ضمیمه کردم اولی برای همراه اول دومی برای مخابرات که همراه اول گزینه دانلودش خطا میده که من فکر میکنم همراه اول آدرس کلود فلری که اسکنر ازش تست دانلود میگیره رو فیلتر کرده برای همین تستش فیلد میشه اما در فایل دوم با همون کانفیگ با نت مخابرات همه 3 تا تست موفقیت آمیزه فکر کنم اگر اون آدرس که تست دانلود روش انجام میشه عوض بشه و بعد یه جوری از دید فیلترچی مخفی بشه مشکل حل میشه!
با سپاس

**Comment by MortezaBashsiz** [comment]
اونجا هم پرسیدید
#368
