### ISSUE TITLE
سوال در مورد استفاده از ورژن جدید

### ISSUE THREAD

**Issue by aliamg1356** [MortezaBashsiz/CFScanner#446]
با سلام و خسته نباشید  بنده از ورژن قبلی ویندوز استفاده میکردم ولی انکار ورژن جدید بر اساس زبان go نوشته شده و بصورت عادی در ویندوز اجرا نمیشه  میشه پکیجهای مورد نیاز و نحوه استفاده از ورژن جدید رو بفرمایید؟

**Comment by tempookian** [comment]
for accessing the latest Windows version of CFScanner use this release :
https://github.com/MortezaBashsiz/CFScanner/releases/tag/v1.1.8489.35707
