### ISSUE TITLE
مشکل کانفیگ

### ISSUE THREAD

**Issue by iamfarhad** [MortezaBashsiz/CFScanner#447]
سلام

من نسخه ویندوز رو اوکی کردم

کانفیگ رو اوکی کردم توی مرحله اخر پیام زیر و میگیرم

Fronting  Result:    FAILED
v2ray.exe Execution: SUCCESS
Download  Result:    FAILED

هیچ ip پیدا نمیکنه

**Comment by goingfine** [comment]
از منوی تولز گزینه Update ClientConfig رو بزنید

اگر بازم پیدا نکرد گزینه time out رو هم روی عدد بالاتر بزارید. از همون منوی تولز

**Comment by goingfine** [comment]
خب شما یه مشکل اساسی تر انگار دارید توی اینترنتتون یا ...
فیلتر شکن اگر روشنه خواموش کنید
ضمنا یه بار هم دیاگنوس انجام بدید نتیجه اش رو اینجا بزارید

**Comment by iamfarhad** [comment]
> خب شما یه مشکل اساسی تر انگار دارید توی اینترنتتون یا ... فیلتر شکن اگر روشنه خواموش کنید ضمنا یه بار هم دیاگنوس انجام بدید نتیجه اش رو اینجا بزارید

Start diagnosing for 162.158.126.178 at 4/14/2023 9:04:07 PM...
Starting scan engine with target speed: 100,000, dl timeout: 2, config: 'Default' => Default...

------------ Start IP Check ------------
IP: 162.158.126.178

----- Fronting Test -----
Start fronting check, timeout: 1, Resolver IP: 162.158.126.178, withCustumDNSResolver: True
Fronting check with url: https://speed.cloudflare.com/__down?bytes=1000
Fronting timed out.

----- Running v2ray.exe -----
Starting v2ray.exe with arg: run -config="v2ray-config/generated/config.162.158.126.178.json"
v2ray.exe executed success: True

----- Download Test -----
Start check dl speed, proxy port: 3624, timeout: 2 sec, target speed: 100,000 b/s
Starting dl url: https://speed.cloudflare.com/__down?bytes=200000
Download timed out.

Fronting  Result:    FAILED
v2ray.exe Execution: SUCCESS
Download  Result:    FAILED

------------ End IP Check ------------

**Comment by goingfine** [comment]
گزینه target speed رو بزارید روی no speed test و اسکن کنید ببینید چیزی پیدا میکنه

**Comment by goingfine** [comment]
محتوای این فایلم بندازید توی شاخه v2ray-config چونکه اتومات نمیتونید اپدیت کنید اینجوری دستی اپدیت کنید بعد برنامه رو ببندید و مجدد باز کنید
[ClientConfig.zip](https://github.com/MortezaBashsiz/CFScanner/files/11235067/ClientConfig.zip)

**Comment by iamfarhad** [comment]
این فایل رو توی پوشه v2ray-config دارم از قبل

دیتاهاشو باید ادیت کنم با دیتای خودم؟

**Comment by goingfine** [comment]
اینو جایگزین قبلی کنید

**Comment by iamfarhad** [comment]
انجام دادم اما فایده نداشت


ویندوز 11 هستم شاید مسکل از این باشه

**Comment by iamfarhad** [comment]
بله
ولی چیزی پیدا نکرد

**Comment by goingfine** [comment]
مشکل از ویندوز با اینترنت و... است

**Comment by iamfarhad** [comment]
کلا توی ویندوز 11 این مشکل هست

Failed to update client config. check your Internet connection or maybe client config url is blocked by your ISP!

@MortezaBashsiz

**Comment by omidmj** [comment]
یک سوال برای تارگت اسپید رو چه عددی باشه جواب بهتری میده ؟
