### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by navid221** [MortezaBashsiz/CFScanner#451]
سلام وقتی تعداد ip های سالم به دست امده در حالت بدون vpn زیاد باشه اگه بخوای همون تعداد ایپی رو در حالت vpn تست کنی این خطا رو میده و مجبور شدم در 3 قسمت مساوی ایپی ها رو به اسکریپت بدم. این مشکل رو برطرف بفرمایید
making upload file by size 204800 Bytes in /home/kali/df/CFScanner/bash/tempConfig/upload_file
cfScanner.sh: line 647: /usr/bin/parallel: Argument list too long

**Comment by MortezaBashsiz** [comment]
درود
این مشکل اسکریپت نیست
محدودیت بش هست
بشکنید توی فایلهای متفاوت
نهایت هر فایل ۴ هزارتا
