### ISSUE TITLE
نسخه جدید ویندوز انگار مشکل داره

### ISSUE THREAD

**Issue by shaahin99** [MortezaBashsiz/CFScanner#452]
سلام
بنده نسخه جدید ویندوز رو دانلود میکنم که دو تا فایل داخل فایل فشرده هست. اولی که اپلیکیشن هست رو باز میکنم ولی باز نمیشه هرچقدر میزنم.
اگه فایل مشکل داره که لطفا اصلاح کنید. اگه هم مشکل از سمت منه و پیش نیازی برای نسخه جدید نیازه و ... ممنون میشم اطلاع بدید.
با تشکر

**Comment by goingfine** [comment]
اونی که دانلود کردین احتمالا نسخه ویندوزی گولنگ هست. اخرین نسخه ویتدوزیو ازینجا بگیرید
https://github.com/MortezaBashsiz/CFScanner/releases/tag/v1.1.8489.35707
