### ISSUE TITLE
پینگ دادن ای پی

### ISSUE THREAD

**Issue by Meytiz** [MortezaBashsiz/CFScanner#454]
من با ی موردی بر خوردم 

با کانفیگ شخصی vless + grpc + tls به یه رنج ای پی وصل میشم با برنامه v2rayng اما همون رنج ای پی رو با اسکنر چک میکنم با نت مخابرات پینگ نمیده ! نمیدونم باگه یا نه ولی اگه دوستان اطلاعی دارید بگید

**Comment by tempookian** [comment]
سلام. لطفا بفرمایید

-  از چه نسخه‌ای استفاده می‌کنید و
-  این‌که آیا با کانفیگ شخصی اسکن گرفتید یا با کانفیگ دیفالت
- اسکنر رو به‌روز کرده بودید قبل از اسکن یا خیر

**Comment by Meytiz** [comment]
اخرین ورژن اسکنر
کانفیگ شخصی

**Comment by tempookian** [comment]
ویندوز؟ پایتون؟ بش؟ ...

**Comment by Meytiz** [comment]
ویندوز

**Comment by goingfine** [comment]
تایم اوت رو بزارید روی عدد بالاتر و سرعت رو هم روی عدد پایین تر و با کانفیگ شخصی خودتون مجدد تست کنید
نتیجه دیاگنوس رو هم بزارید اینجا

ضمنا بزارید کلا یه مقدار تست کنه روی همه رنج ها و بگید چیزی پیدا میکنه یا نه

**Comment by Meytiz** [comment]
من از تو قسمت scan results وقتی ای پی که روی کانفیگم جواب میده رو ادد میکنم با کانفیگ شخصی تایم اوت میده ولی با کانفیگ دیفالت پینگ میده!

**Comment by Meytiz** [comment]
Start diagnosing for 205.233.181.16 at 4/15/2023 1:59:33 PM...
Starting scan engine with target speed: 100,000, dl timeout: 10, config: 'mkh.json' => {
    "inbounds": [{
      "port": "PORTPORT", 
      "listen": "127.0.0.1",
      "tag": "socks-inbound",
      "protocol": "socks",
      "set...

------------ Start IP Check ------------
IP: 205.233.181.16

----- Fronting Test -----
Start fronting check, timeout: 1, Resolver IP: 205.233.181.16, withCustumDNSResolver: True
Fronting check with url: https://speed.cloudflare.com/__down?bytes=1000
Fronting check done in 434 ms, content: '00000000000000000000000000000000000000000000000000'

----- Running v2ray.exe -----
Starting v2ray.exe with arg: run -config="v2ray-config/generated/config.205.233.181.16.json"
v2ray.exe executed success: True

----- Download Test -----
Start check dl speed, proxy port: 3635, timeout: 10 sec, target speed: 100,000 b/s
Starting dl url: https://speed.cloudflare.com/__down?bytes=1000000
Download had exception: One or more errors occurred. (The SSL connection could not be established, see inner exception.)

Fronting  Result:    SUCCESS
v2ray.exe Execution: SUCCESS
Download  Result:    FAILED

------------ End IP Check ------------

**Comment by goingfine** [comment]
یه مشکلی توی کانفیگ هست. من خیلی به جزیات کانفیگ ها مسلط نیستم اما احتمالا هرچی هست باید توی تغییر دادن کانفیگ وقت بزارید و همچنین ممکنه نسخه ایکه v2ray.exe ما هست با اونیکه توی v2rayN هست و میگید داره کار میکنه یکی نباشه و اون داره داستان درست میکنه لذا سعی کنید v2ray.exe توی فولدر ما رو با نسخه های دیگه جایگیزین و تست کنید

ضمنا بگید میزارید اسکن کلی بکنه IP پیدا میکنه یا نه

**Comment by goingfine** [comment]
یه چیز دیگم تست کنید. با v2rayN‌ پروکسی رو بالا بیارید و ببینید میتونید این رو توی مروگر و با پروکسی باز کنید و خطا نمیده؟

 https://speed.cloudflare.com/__down?bytes=100000

**Comment by Meytiz** [comment]
مورد اول من دقیق روشی که سگارو گفت رو انجام دادم .
اپ v2ray.exe رو چطوری جایگزین کنم خود اپ رو کپی پیست کنم توی پوشه اسکنر؟
و لیینک رو با پروکسی روشن میزنم روش دانلود میشه

**Comment by goingfine** [comment]
نسخه ویمدوزیش رو از گیتهابش دانلود کنید و رینم کنید به v2ray.exe رو جایگزین کنید
یا شاید توی فولدر v2rayN هم باشه ازونجا بردارید

**Comment by Meytiz** [comment]
بدتر شد که بهتر نشد !

**Comment by goingfine** [comment]
نمیدونم دیگه
