### ISSUE TITLE
نیاز به آپدیت لیست آی پی های کلاد فلیر

### ISSUE THREAD

**Issue by aliamg1356** [MortezaBashsiz/CFScanner#455]
با سلام  تعدادی از رنج آی پی ها ظاهرا برای بعضی اپراتورها کار میکنند که در لیست آی پی برنامه موجود نیستند  میشه بروز رسانی بفرمایید؟

**Comment by yaghobmn** [comment]
سلام. در راستای این درخواست، اسکنر صفا صفری هم رنج آی‌پی هایی داره که تو لیست شما نیست. لینک پروژه
https://github.com/SafaSafari/ss-cloud-scanner
لینک ساب نت هاش
https://github.com/SafaSafari/ss-cloud-scanner/blob/main/ips.txt

**Comment by MortezaBashsiz** [comment]
درود
آپدیت آی‌پی ها انجام میشه
دیگه کلا همه رو میزاریم توی لیست
