### ISSUE TITLE
اسکنر Bash

### ISSUE THREAD

**Issue by erfanpirhadi** [MortezaBashsiz/CFScanner#456]
config file is not available https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/config/ClientConfig.json
use your own
 وقتی اسکریپت رو ران میکنم داخل لینوکس این ارور رو میده تا دیروز اوکی بودش

**Comment by MortezaBashsiz** [comment]
درود
ساب دامنه راو موقت فیلتر شده بود مثل اینکه
ولی الان باز شده
تست کنید لطفا
