### ISSUE TITLE
تست آپلود

### ISSUE THREAD

**Issue by shaahin99** [MortezaBashsiz/CFScanner#457]
با سلام
در فیلترینگ جدید هم دانلود میده و هم پینگ میده ولی آپلود اکثر آی پی های پیدا شده صفره و واقعا پیدا کردن آپی تمیز با کلی تست دونه ای سخته.
لطفا گزینه ای برای تست سرعت آپلود نیز در نظر بگیرید که هم بشه همزمان آپلود و دانلود رو تست کرد و هم به صورت جداگانه.

**Comment by MortezaBashsiz** [comment]
درود
در مورد کدام نسخه؟
ویندوز
بش
پایتون
گولنگ

**Comment by shaahin99** [comment]
> درود در مورد کدام نسخه؟ ویندوز بش پایتون گولنگ

بنده در ویندوز استفاده میکنم

**Comment by MortezaBashsiz** [comment]
تست آپلود در برنامه هست
اطلاع رسانی میشه
سپاس
