### ISSUE TITLE
سوال درباره اسکنر ویندوز 

### ISSUE THREAD

**Issue by omidmj** [MortezaBashsiz/CFScanner#458]
سلام به مرتضی باشیز عزیز و تمام همکاران مرتضی عزیز  که در داشتن اینترنت ازاد تلاش میکنند خیلی ازتون ممنون هستیم من چند تا سوال داشتم در مورد اسکنر ویندوز :
سوال1: من چند روزی وقتی با کانفیگ شخصی تست میگیرم ای پی سالم رو برام میاره اما وقتی میام دیاگنوس بگیرم بعضی ای پی ها v2ray موفقیت امیز و دو تا گزینه دیگه فیلد میشه باز بعضی ای پی ها فرانت و v2ray موفقیت امیز دانلود فیلد میشه ایا این خطا باید بهش استناد کرد یا خیر؟
سوال دوم : در قسمت تارگت اسپید چه سرعتی عملکرد بهتری خواهد داشت چون به صورت پیش فرض بر روی 100 قرار دارد ایا بر روی 200 یا 500 قرار بدهیم نتایج بهتری ممکنه بگیرم و ایا ارتباط به سرعت دانلود خواهد داشت یا خیر؟
سوال3: از کجا بفهیم ای پی که برامون پیدا کرده سرعت دانلود و اپلود خوبی داره ؟
سوال 4: برای من به هنگام اسکن این خطا رو میده   One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).) مشکل از کانفیگ من هست یا خیر 
پیشنهاد: امکانش هست در نسخه ویندوز یک فایل 1 مگ براش تعریف کنید که برامون تایم دانلودش رو بزنه که مثلا چقدر طول کشید این فایل رو دانلود کرد و همچین برای اپلودش یا امکانش نیست  
  مرتضی جان و همکاران عزیزش بابت تمام زحمات شبانه روزی اتون تشکر میکنم امیدوارم قشنگ ترین اتفاقات در انتظارتون باشه

**Comment by goingfine** [comment]
1- هردفعه که اسکن میکنید بر اساس تنظیمات ممکنه یک آی پی دانلدوش مثبت یا منفی بشه چون سرعت اینترنت متغیره و ممکنه به اون حد مورد نظر نرسه و Fail بشه. ضمنا از گزینه دیاگنوس معمولا فقط برای زمانی استفاده میکنیم که ایرادی باشه بخوایم بررسی کنیم

۲- بستگی به سرعت اینترنتتون داره هرچی بالاتر بزارید امکان از دست دادن آی پی ها بیشتر میشه اما به جاش آی پی های پر سرعت تر رو پیدا میکنید

۳- هرچی delay کمتر باشه سرعت دانلود بیشتر و بهتره
۴- نمیدونم اما احتمالا از سرورتون باشه

تو برناممون هست تست سرعت رو بزاریم

**Comment by omidmj** [comment]
> 1- هردفعه که اسکن میکنید بر اساس تنظیمات ممکنه یک آی پی دانلدوش مثبت یا منفی بشه چون سرعت اینترنت متغیره و ممکنه به اون حد مورد نظر نرسه و Fail بشه. ضمنا از گزینه دیاگنوس معمولا فقط برای زمانی استفاده میکنیم که ایرادی باشه بخوایم بررسی کنیم
> 
> ۲- بستگی به سرعت اینترنتتون داره هرچی بالاتر بزارید امکان از دست دادن آی پی ها بیشتر میشه اما به جاش آی پی های پر سرعت تر رو پیدا میکنید
> 
> ۳- هرچی delay کمتر باشه سرعت دانلود بیشتر و بهتره ۴- نمیدونم اما احتمالا از سرورتون باشه
> 
> تو برناممون هست تست سرعت رو بزاریم

ممنون از پاسخگویی خوبتون برای سوال 4 اخه رو همون سرور بعضی ای پی ها رو میاره رو بعضی ای پی ها این خطا رو میده

**Comment by goingfine** [comment]
نه این مربوط به کامپیوترتونه که میگه روی پورت 3403 یه برنامه در حال listen کردنه
