### ISSUE TITLE
رنج آی پی غیر از کلادفلر

### ISSUE THREAD

**Issue by mrmemrmemrme** [MortezaBashsiz/CFScanner#459]
سلام و درود
بصورت اتفاقی متوجه رنج آی پی شدم که متعلق به کلادفلر نیست ولی جواب میداد. مانند آی پی 192.200.160.160 که ظاهرا متعلق به BIGCOMMERCE هستش و حتی توی اسکن شما هم نتیجه مثبت میداد. البته الان این آی پی قطع شده. آیا رنج آی پی BIGCOMMERCE یا امثال این، امن هستش؟

**Comment by MortezaBashsiz** [comment]
درود
ما نمیتونیم بگیم امنه یا نه
ما فقط رنجهای مطمین رو داریم
سپاس
