### ISSUE TITLE
Specific IP Addresses

### ISSUE THREAD

**Issue by NadiaGarcia6** [MortezaBashsiz/CFScanner#46]
How can I scan specific IP address ranges? 
For example, I want to scan the IP addresses which are in the result file again and not the whole of Cloudflare's IP Addresses.

**Comment by MortezaBashsiz** [comment]
I will add it as an feature in next updates

**Comment by Argo160** [comment]
> How can I scan specific IP address ranges? For example, I want to scan the IP addresses which are in the result file again and not the whole of Cloudflare's IP Addresses.

In a meantime till the next update of this repository gets ready, this forked one might help you. this is solo ip ranged scanning. but also comes with an extra speed test scan process.
https://github.com/Argo160/Solo-CFScanner
and all thanks to dear Bashsiz

**Comment by MortezaBashsiz** [comment]
With the latest update you can give your costume subnets to script

**Comment by Recoba86** [comment]
in a custom subnet, it requires ip range!
when I give specific IP in the result file it shows an error like this
cfFindIP.sh: line 350: 45.87.175.165: syntax error: invalid arithmetic operator (error token is ".87.175.165")
we cant give a list of IP to script

**Comment by Recoba86** [comment]
> With the latest update you can give your costume subnets to script

in a custom subnet, it requires ip range!
when I give specific IP in the result file it shows an error like this
cfFindIP.sh: line 350: 45.87.175.165: syntax error: invalid arithmetic operator (error token is ".87.175.165")
we cant give a list of IP to script
