### ISSUE TITLE
ساختار و منطق اسکنر کلادفلر

### ISSUE THREAD

**Issue by mrmemrmemrme** [MortezaBashsiz/CFScanner#460]
سلام و درود
اگر درست متوجه شده باشم. نحوه کار به دو شکل کلی هستش، اول با کانفیگ که لازمه ش داشتن آی پی سالم از قبل هستش تا بتونه اسکن کنه، دوم بدون کانفیگ.
وقتی نتایج بدست آمده بدون کانفیگ رو بخوایم تست کنیم باز باید کانفیگی داشته باشیم که از قبل آی پی سالم داشته باشه.
اگر توضیحاتم درست نیست لطفا راهنمایی کنید. اگرم درست عرض میکنم که پیشنهاد میشه در فایل کانفیگ، قسمت serverName رو خالی بگذاریم و اسکنر کلادفلر دونه دونه آی پی های کلادفلر رو در قسمت serverName کانفیگ قرار بده و توسط کانفیگ تست کنه ببینه جواب میدن یا خیر. اینجوری مجبور نیستیم هزاران آی پی رو بصورت دستی و دونه دونه جایگذاری کنیم.

**Comment by MortezaBashsiz** [comment]
درود
نحوه کارش اینطوریه که
بدون وی پی ان مستقیم خود آی پی رو تست میگیره
با وی پی ان کانکشن وی تو ری میسازه به اون آی پی
پیشنهاد میکنم برید نسخه بش رو که ساده‌ترینش هست بخونید تا کامل متوجه بشید
سپاس
