### ISSUE TITLE
Bash

### ISSUE THREAD

**Issue by Amirands** [MortezaBashsiz/CFScanner#461]
سلام مشکل چیه وقتی با کانفیگ خودم اسکن میکنم این خطا رو میده syntax error: unexpected

**Comment by Amirands** [comment]
درواقع تست میکنه ip ها رو ولی چندین خط سریع این ارور رو میده بعد دوباره شروع به اسکن میکنه

**Comment by MortezaBashsiz** [comment]
درود
کانفیگتون دقیقا باید مثل کانفیگ پیشفرض باشه

**Comment by Amirands** [comment]
ممنون بابت راهنمایی لطف کردین
