### ISSUE TITLE
دستور مرتب کردن بر اساس سرعت دانلود

### ISSUE THREAD

**Issue by navid221** [MortezaBashsiz/CFScanner#464]
سلام وقت بخیر
وقتی ایپی های به دست امده رو توی مد vpn تست میکنیم و در نهایت مطمئن میشیم که این آیپی ها رو کانفیگمون کار میکنن با چه دستوری میشه ایپی های به دست اومده رو بر اساس سرعت دانلود مرتب کرد؟
و سوال بعدی ایا میشه به اسکریپت امکان اینو اضافه کنید که در کنار سرعت دانلود پینگ ip رو هم بهمون بده؟

**Comment by MortezaBashsiz** [comment]
درود
میتونید با دستورات لینوکسی مثل sort استفاده کنید
سرچ کنید توی اینترنت پیدا میشه
نخیر دادن پینگ برای نتیجه تاثیری نداره و کار بیهوده‌ای هست
سپاس
