### ISSUE TITLE
مشکل در نحوه تست نسخه ویندوزی بدون کانفیگ 

### ISSUE THREAD

**Issue by megasoheilsh** [MortezaBashsiz/CFScanner#467]
سلام اسکنر نسخه ویندوزی هر ایپی که پورت 443 در حال listen باشه رو به عنوان ایپی سالم لیست میکنه
درصورتیکه نسخه لینوکسی واقعا تست سرعت میگیره و ایپی واقعیه

**Comment by megasoheilsh** [comment]
نمونه سابنت جهت تست 37.152.176.0/24

**Comment by goingfine** [comment]
خیر اینطور نیست. دقیق تر توضیح بدین

**Comment by megasoheilsh** [comment]
> خیر اینطور نیست. دقیق تر توضیح بدین

دوست گرامی ، هر ایپی که پورت 443 آن باز باشه اسکنر لیستش میکنه .  در صورتیکه هیچ ارتباطی به کلودفلر یا ارتباطی با ادج کلودفلر نداره 

[URL=https://uupload.ir/][IMG]https://s8.uupload.ir/files/23123_xz7d.jpg[/IMG][/URL]

**Comment by goingfine** [comment]
عکس رو همینجا بزارید
اگر منظورتون حالت no speed test هست در اون حالت فقط تست فرانتینگ انجام میشه و بدون vpn

**Comment by MortezaBashsiz** [comment]
درود
من فکر کنم شما توی سرور‌هاتون یه جایی رو درست کانفیگ نکردین چون وقتی که کامند زیر رو میزنیم از آی پی های شما پاسخ میگیریم

`
curl -k -s -w "%{http_code}\n" --tlsv1.2 -H "Host: speed.cloudflare.com" --resolve "speed.cloudflare.com:443:37.152.176.191" "https://speed.cloudflare.com/__down?bytes=1000"
`
یعنی نتیجه این دستور اوکی میشه بخاطر همینه که این آی‌پی ها رو اوکی میده
چون ما فقط هدر و ریسپانس رو چک میکنیم
من توی بش هم اسکن گرفتم و نتیجه برای آی‌پی های شما اوکی شد

![image](https://user-images.githubusercontent.com/19620677/233581818-951f3e6e-f264-48c3-a4ec-945a8b6797bd.png)
![image](https://user-images.githubusercontent.com/19620677/233581524-b39f09e0-a061-4c28-bb0f-aaa554929656.png)

**Comment by MortezaBashsiz** [comment]
این ایشو را باز نگه میداریم تا مشکل رو برطرف کنیم
ما باید محتوای بازگشتی رو ولیدیت کنیم

**Comment by megasoheilsh** [comment]
> درود من فکر کنم شما توی سرور‌هاتون یه جایی رو درست کانفیگ نکردین چون وقتی که کامند زیر رو میزنیم از آی پی های شما پاسخ میگیریم
> 
> `curl -k -s -w "%{http_code}\n" --tlsv1.2 -H "Host: speed.cloudflare.com" --resolve "speed.cloudflare.com:443:37.152.176.191" "https://speed.cloudflare.com/__down?bytes=1000"` یعنی نتیجه این دستور اوکی میشه بخاطر همینه که این آی‌پی ها رو اوکی میده چون ما فقط هدر و ریسپانس رو چک میکنیم من توی بش هم اسکن گرفتم و نتیجه برای آی‌پی های شما اوکی شد
> 
> ![image](https://user-images.githubusercontent.com/19620677/233581818-951f3e6e-f264-48c3-a4ec-945a8b6797bd.png) ![image](https://user-images.githubusercontent.com/19620677/233581524-b39f09e0-a061-4c28-bb0f-aaa554929656.png)

سلام ، این ها ایپی های عمومی هستش و سرور های من نیست ، هر ایپی رو اسکن میکنیم همین نتیجه رو میدهد

**Comment by MortezaBashsiz** [comment]
بله این مشکل روی بش حل شد
و اینکه روی بقیه نسخه ها هم برطرف میشه در آپدیت بعدی
مرسی بابت همراهی

**Comment by megasoheilsh** [comment]
با تشکر از زحمات شما دوستان

**Comment by megasoheilsh** [comment]
امشب تونستم تستش کنم بسیار دقیق و عالی شد . اگر امکانش هست نسخه ویندوزی رو هم زحمتشو بکشید . ممنون از زحمات شما عزیزان
