### ISSUE TITLE
cf.local.iplist has overlapping subnets

### ISSUE THREAD

**Issue by pulsarice** [MortezaBashsiz/CFScanner#468]
for example 
103.21.244.0/24
103.21.244.0/22

103.22.200.0/22
103.22.201.0/24
103.22.202.0/23

108.162.192.0/18
108.162.192.0/20

Only the largest subnet of each group should be included in the list.

**Comment by MortezaBashsiz** [comment]
Hi
Thanks
We are working on it
Will keep this issue open till resolved

**Comment by MortezaBashsiz** [comment]
Now it is resolved
You can check it here
https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/config/cf.local.iplist
