### ISSUE TITLE
Packet Loss Metric

### ISSUE THREAD

**Issue by theonlyfoxy** [MortezaBashsiz/CFScanner#469]
Hi.
It seems some ISPs are having heavy packet loss for some IP ranges, Therefore I suggest implementing a metric feature to measure each IP's packet loss alongside delay.
Also another metric for measurement of average delay could be handy.

Regards.

**Comment by MortezaBashsiz** [comment]
Hi
Which scanner are you using
Windows, Bash, Python, Go ?

**Comment by theonlyfoxy** [comment]
I use both Windows & Bash version.

**Comment by MortezaBashsiz** [comment]
Hi
AVG of response time is available in Bash, Python, Golang
About packet loss, it could not have any additional advantage for who want to find good IP. On the other hand you can try each IP several times while you are scanning to make sure that this IP is stable or not
