### ISSUE TITLE
Wrong IP Ranges

### ISSUE THREAD

**Issue by NadiaGarcia6** [MortezaBashsiz/CFScanner#47]
As far as I know Cloudflare's IP ranges are listed on https://www.cloudflare.com/ips/ but CFScanner scans other IPs which are not related to the Cloudflare company.

For instance: 154.84.21.39 You can visit this http://154.84.21.39/

![image](https://user-images.githubusercontent.com/119847856/218473783-076c11f9-7c7f-4072-826b-d30e3a77f278.png)

**Comment by MortezaBashsiz** [comment]
I have used all the Cloudflare BGP ip addresses with AS209242 which is better than scanning only Cloudflare whitelist IPs

**Comment by NadiaGarcia6** [comment]
Do you find any useable IP addresses from Cloudflare BGP IP ( AS209242 ) except this range "https://www.cloudflare.com/ips-v4 " for using Cloudflare CDN service?

As I scanned with your script only the IP addressed which are announced on URL above work.
