### ISSUE TITLE
تست کانفیگ

### ISSUE THREAD

**Issue by amirreza1028** [MortezaBashsiz/CFScanner#473]
با سلام
از کجا بفهمم کانفیگی که قراردادم درست کار میکنه
آخه الان وقتی پارامتر v رو برروی NO قرار میدم تعدادی ip پیدا میشه ولی وقتی فعال میکنم هیچی پیدا نمیشه
ممکنه کانفیگ مشکل داشته باشه؟ میشه تست کرد؟

**Comment by MortezaBashsiz** [comment]
درود
من این مورد رو میزارم توی برنامه‌هام که حتما بنویسمش
ایشو را باز میزارم تا تکمیل بشه

**Comment by MortezaBashsiz** [comment]
متاسفانه امکان نوشتنش برام  فراهم نیست
