### ISSUE TITLE
امکان سرچ آیپی با سابنت و تیک زدن رنج دلخواه با یک دکمه

### ISSUE THREAD

**Issue by randomguy-on-internet** [MortezaBashsiz/CFScanner#475]
سلام.
اگر میشه توی اسکنر نسخه ویندوزی امکان سرچ رنج آیپی رو با سابنت یا هرجور دیگه بزارید و امکان انتخاب همه رو برای سرچ فعال کنید.
یه مثال هم واسه شفاف سازی میزنم.
مثلا من میخوام **تمام** آیپی های رنج 45 و 104 کلود فلر رو انتخاب کنم همه رو تیک بزنم، داخل نوارجستجو اول میزنم  و 45.0.0.0/8 ای پی های این رنج رو میاره و با سلکت آل همه رو انتخاب میکنم بعدش میخوام به همین ترتیب رنج 104 رو با 104.0.0.0/8 بگیرم.

و شاید من ندونم سابنت چیه و بخوام فقط با نوشتن 104.8.... این رنج رو برام بیاره.
اگر میشه این رو اضافه کنید یه آپدیت QoL خیلی خوبه.

خداقوت و سرافراز باشید.

**Comment by goingfine** [comment]
اگر فرصت شد چشم
