### ISSUE TITLE
1: ELF: not found 2: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by iCheg** [MortezaBashsiz/CFScanner#48]
I'm running this on an Ubuntu 22.04 ARM64 vm with Parallels Desktop 18 on Mac. 

I get only 2 kind of results, failed ips and other ones give this error :

FAILED 45.131.210.230
FAILED 45.131.210.229
/root/cftest/CFScanner/scripts/v2ray: 1: ELF: not found
/root/cftest/CFScanner/scripts/v2ray: 2: Syntax error: "(" unexpected

any suggestions about what I'm doing wrong?

**Comment by MortezaBashsiz** [comment]
Hi
This is related to v2ray binary file please use it on 20.04

**Comment by iCheg** [comment]
Hi Morteza 
Thank you very much for your reply and all the efforts,

I ran it on Ubuntu 20.04.5 ARM64 virtual machine  on mac m1 and unfortunately still getting the same errors.
your advice would be much appreciated.


FAILED 45.87.175.219
FAILED 45.87.175.228
FAILED 45.87.175.229
FAILED 45.87.175.223
/root/CFScanner/scripts/v2ray: 1: ELF: not found
/root/CFScanner/scripts/v2ray: 2: Syntax error: "(" unexpected
FAILED 45.87.175.222
/root/CFScanner/scripts/v2ray: 1: ELF: not found
/root/CFScanner/scripts/v2ray: 2: Syntax error: "(" unexpected
FAILED 45.87.175.225
/root/CFScanner/scripts/v2ray: 1: ELF: not found
/root/CFScanner/scripts/v2ray: 2: Syntax error: "(" unexpected
