### ISSUE TITLE
  تست سرعت و  تعداد ترد های همزمان

### ISSUE THREAD

**Issue by p3im4n** [MortezaBashsiz/CFScanner#482]
من با یه لپتاپ با این مشخصات:
core i5 gen 10  
ram 12 ddr4
ssd nvme 512
win10
اسکن رو با نسخه ویندوز انجام میدم و به دوتا مورد بر خوردم که عرض میکنم

مشکل اول:
متوجه شدم تعداد ترد ها بیشتر از 8 باعث میشه تو یه رنج مشخص آی پی پیدا نکنم یا خیلی کم پیدا کنم
  این در حالیه که وقتی با 32 ترد هم  انجام میدم درصد قابل توجهی از رم و سی پی یو استفاده نمیشه پس محدودیت سخت افزاری ندارم

مشکل دوم:
مقدار  سرعت  و که مشخص میکنم هیچی پیدا نمیکنه
در نتیجه مقدار نمیدم و نتیجه هایی با سرعت صفر رو یه بار دیگه با سرعت 20 اسکن میکنم و اینجوری جواب میگیرم که دوباره کاری میشه

خوشحال میشم دوستان تجربه مشترکشون رو اینجا مطرح کنن

**Comment by goingfine** [comment]
در تعیین تعداد ترد فقط مشخصات سخت افزاری ملاک نیست. ملاک اصلی سرعت و پینگ خط اینترنتتون هست.
تعداد ترد بیشتر نیاز به اینترنت بهتر داره وگرنه ip ها همونطور که گفتین از دست میرن.

**Comment by Amirziplin** [comment]
> من با یه لپتاپ با این مشخصات: core i5 gen 10 ram 12 ddr4 ssd nvme 512 win10 اسکن رو با نسخه ویندوز انجام میدم و به دوتا مورد بر خوردم که عرض میکنم
> 
> مشکل اول: متوجه شدم تعداد ترد ها بیشتر از 8 باعث میشه تو یه رنج مشخص آی پی پیدا نکنم یا خیلی کم پیدا کنم این در حالیه که وقتی با 32 ترد هم انجام میدم درصد قابل توجهی از رم و سی پی یو استفاده نمیشه پس محدودیت سخت افزاری ندارم
> 
> مشکل دوم: مقدار سرعت و که مشخص میکنم هیچی پیدا نمیکنه در نتیجه مقدار نمیدم و نتیجه هایی با سرعت صفر رو یه بار دیگه با سرعت 20 اسکن میکنم و اینجوری جواب میگیرم که دوباره کاری میشه
> 
> خوشحال میشم دوستان تجربه مشترکشون رو اینجا مطرح کنن

وقتی تعداد ترد ها بالا میره فقط آیپی هایی رو نشون میده که پینگ سریعتری دارن -در نتیجه بهترین آیپی اونه که با ترد 32 و سرعت 500 ک به دست میاد که خیلی امکانش کمه ، ولی معمولا سرعت رو روی 200 و ترد روی 8 باشه آیپی خوبی بدست میاد
