### ISSUE TITLE
اسکن ipv 6

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#483]
سلام
خسته نباشید
می خواستم بدونم با نسخه bash چطور می تونم ipv 6 رو اسکن کنم ؟ 
ممنونم

**Comment by MortezaBashsiz** [comment]
درود
امکانش فراهم نیست و فعلا هم در برنامه نیست چون فیچرای مهمتری هست که اول اونا باید ریلیز بشن
ولی در آینده حتما روش کار خواهیم کرد
