### ISSUE TITLE
ریالیتی

### ISSUE THREAD

**Issue by Amirziplin** [MortezaBashsiz/CFScanner#488]
پیشنهاد میکنم  همین نرم افزار رو برای پیدا کردن سایتهای مناسب  ریالیتی تغییر بدین ، چون عملا کلود فلر دیگه جواب نمیده . فکر میکنم با چندتا تغییر کوچک بشه اینکار رو انجام داد ، مثلا مقدار آدرس سرور ثابت بمونه و  بجاش دنبال sni  بگرده ، (برعکس کاری که  برای پیدا کردن آیپی کلودفلر انجام میده)
و بجای لیست آیپی های کلود فلر دنبال سایتهای بهتر بگرده .

با تشکر از زحمات شما

**Comment by MortezaBashsiz** [comment]
درود
فعلا برای این مرود برنامه ای نداریم
در آینده ممکنه که بهش بپردازیم
سپاس
