### ISSUE TITLE
ارور نسخه پایتون هنگام تست روی مک

### ISSUE THREAD

**Issue by akonil** [MortezaBashsiz/CFScanner#490]
<img width="736" alt="Screenshot 2023-04-20 at 11 15 49 AM" src="https://user-images.githubusercontent.com/128259098/233296838-1649cf0e-cfb9-44c2-90d1-c55cbab28620.png">

**Comment by tempookian** [comment]
لطفا محتویات فایل 

./log/20230420_111444.log
رو چک کنید و ببینید جزئیات بیشتری هست یا خیر. اگر بعد از ناشناس‌سازی بتونید فایل رو این‌جا قرار بدید عالی می‌شه

**Comment by tempookian** [comment]
یه سری تغییراتی دادم امیدوارم درست شده باشه. فقط در نظر داشته باشید که از این به بعد از این طریق بایستی نصب کنید.

```bash
pip install cfscanner --upgrade
```

**Comment by raminrez** [comment]
مشکل هنوز هست
با نسخه جدید تست کردم `pip install cfscanner --upgrade`

[20230420_225151.log](https://github.com/MortezaBashsiz/CFScanner/files/11289742/20230420_225151.log)

**Comment by tempookian** [comment]
با چه دستوری اجرا کردید؟

**Comment by raminrez** [comment]
`cfscanner  -c config.json -s ips.txt -DS 100 -t 8 -n 6`

**Comment by tempookian** [comment]
```bash
sort ips.txt | uniq -d
```

لطفا تایید می‌کنید که یک یا چند آیپی در خروجی این آیپی می‌بینید؟‌ اگر آره آیا عمدی آیپی‌ها رو تکرار کردید یا سهوا رخ داده. اگر عمدی بوده دلیلتون رو بگید که ببینم اگر منطقیه این امکان رو به کاربر بدم وگرنه قبل از اسکن سابنت‌های تکراری رو حذف کنم

**Comment by raminrez** [comment]
متاسفم٬ تکراری بودن آی‌پی هارو متوجه نشده بودم و سهوا بوده


تکراری هارو حذف کردم و اروری نبود

**Comment by tempookian** [comment]
دشمنتون. ایشو رو باز نگه می‌دارم تا تو کد هم حلش کنم.

**Comment by tempookian** [comment]
```bash
pip install cfscanner --upgrade
```

مشکل در نسخه 1.3.13 برطرف شد.
