### ISSUE TITLE
pkg_resources Module

### ISSUE THREAD

**Issue by yaghobmn** [MortezaBashsiz/CFScanner#492]
سلام نسخه پایتونی رو با pip نصب کردم موقع اجرا ارور میده که ماژول pkg_resources نصب نیست
این ماژول رو خواستم با دستور
pip install pkg_resources
و
pip install micropython-pkg_resources
نصب کنم ولی نشد.
چطوری میتونم این ماژول رو نصب کنم؟
![IMG_20230420_194528](https://user-images.githubusercontent.com/58794904/233410729-ff3e5108-3f40-447d-b831-acab6148b361.jpg)

**Comment by tempookian** [comment]
این رو امتحان کنید لطفا و نتیجه رو اطلاع بدید. سپاس:

```bash
pip install setuptools
```

**Comment by yaghobmn** [comment]
درست شد. تشکر

**Comment by tempookian** [comment]
سپاس که اطلاع دادید. setuptools به لیست پیش‌نیازها اضافه خواهد شد و بایستی دیگه بدون مشکل و نیاز به نصب دستی روی ترموکس هم ران بشه
