### ISSUE TITLE
تفاوت خروجی اسکریپت‌ها

### ISSUE THREAD

**Issue by raminrez** [MortezaBashsiz/CFScanner#494]
سلام و خسته نباشید

اسکریپت بش مدتیه که خروجی هاش ۱۰۰٪ نیستند. مثلا من با این متر اجرا میکنم. تعداد زیادی خروجی میگیرم ولی همچنان آی پی ها کار نمیکنند:
`bash cfScanner.sh -v YES -m IP -f ips.txt -c MYconfig.json -t BOTH -p 8 -n 20 -u 20 -d 20 -s 3000`

از طرفی همون لیست آی پی رو با نسخه گولنگ تست میکنم و هیچ آی پی رو تایید نمیکنه و خروجی نمیده. اسکریپت گولنگ:
`./CFScanner --config MYconfig.json  --threads 8 --tries 2 --subnets ips.txt --vpn --upload`

نسخه پایتون هم فعلا برای من ارور میده.
سیستم‌عامل: مک
اینترنت: ایرانسل

**Comment by MortezaBashsiz** [comment]
درود
مدتیه که خروجیاش صددرصد نیست منظورتون اینه که همش درست نیست اگه بیشتر توضیح بدید ممنون میشم

در مورد اینکه اسکنر به شما اوکی میده ولی آی‌پی ها کار نمیکنه خب ممکنه خیلی دلایل باشه و این رو هم درنظر بگیرید که این اسکنر فقط آی‌پی که احتمال داره اوکی باشه رو براتون پیدا میکنه و در نهایت خودتون باید تست بگیرید که اون آی پی کار میکنه یا نه
 در مورد اینکه آی پی های خروجی بش رو که اوکی هستند با گولنگ تست میگیرید نمیشه خب پارامتراتون با هم خیلی فرق داره توی بش دارید ۲۰ بار اسکن میکنید هر آی پی رو ولی توی گولنگ ۲ بار
 توی بش دارید هم دانلود هم آپلود رو تست میگیرید و توی گولنگ دارید فقط آپلود رو تست میگیرید
 و اینم در نظر بگیرید که شما دارید دو برنامه جداگانه رو که هم از نظر زبان برنامه نویسی و هم امکانات متفاوت هستند رو باهم مقایسه میکنید
 
 در مورد نسخه پایتون هم ارور رو بیشتر توضیح بدید و براش ایشو جداگانه بزنید لطفا

**Comment by tempookian** [comment]
یه نکته‌ای که هست شما اگر توی سایت speed.cloudflare.com هم برید و ببینید متوجه می‌شید که سرعت دانلود خیلی بستگی داره به سایز فایلی که برای تست انتخاب می‌کنید. توی نسخه پایتون و فکر کنم توی GO (مطمئن نیستم) این اندازه فایل بستگی داره به کمینه سرعت انتظاری (-DS) و بیشینه زمان مفید قابل قبول برای دانلود (-DT). در مرحله آخر که لیست آیپی‌ها رو به هر روشی محدود کردید یا کانفیگ کنید و با کلاینت تست بگیرید یا این‌که -DT رو ببرید بالا تا سرعتی که بهتون می‌ده به مقدار واقعی که از اسپید‌تست میاد یکی باشه. برای آپلود هم توضیحاتی که عرض کردم صدق می‌کنه
