### ISSUE TITLE
بررسی عملکرد

### ISSUE THREAD

**Issue by admiraltidebringer** [MortezaBashsiz/CFScanner#496]
سلام آقا مرتضی
وقت بخیر
خسته نباشید
من نسخه بش(نسخه یکی مانده به آخر) ویندوز(نسخه آخر) و پایتون(نسخه آخر) رو چند روز هست تست کردم و همگی به درستی کار می کنند
ممنون از زحمات شما که باعث شدید یک خانواده با یه سرور پایه و با حداقل هزینه بتونند به اینترنت آزاد دسترسی داشته باشند.
من نسخه آخر بش که امروز منتشر کردید رو هم تست کردم و مشکلی نداشت و از نظر عملکرد عین نسخه قبلی بود. چه زمان اجرا و چه نتایج خروجی. اگر از همون نسخه قبلی بش استفاده کنیم ایرادی نداره؟

**Comment by MortezaBashsiz** [comment]
درود
خب همیشه از آخری استفاده کنید
وقتی فرقی نمیکنه براتون از آخری استفاده کنید
