### ISSUE TITLE
لیست آیپی های شخصی

### ISSUE THREAD

**Issue by erfanpirhadi** [MortezaBashsiz/CFScanner#498]
سلام خسته نباشید. داخل نسخه های قبلی برنامه وقتی بهش لیست آیپی های خودم رو میدادم، برنامه درست کار میکردم و آیپی هامو چک میکرد ولی داخل نسخه جدید وقتی مثلا با دستور میزنم که آیپی هامو چک کنه
bash cfScanner.sh  -c ../config/ClientConfig.json -v YES -m IP -t BOTH -p 4 -n 4 -s 100 -f ip.list
با یه سرعت خیلی خیلی زیادی فقط لیست آیپی هام میاد پایین و همشون faild میشن من سرعت روی کمترین مقدار ممکن هم گذاشتم ولی باز دوباره با یه سرعت خیلی بالایی که مشخصه اصلا چک نمیکنه آیپی رو کارشو انجام میده و همه رو faild میزنه

**Comment by MortezaBashsiz** [comment]
درود قبلا ایراد داشت و الان دیگه با نسخه جدید حتما حتما اون آی‌پی باید ترافیک رو رد کنه تا اوکی باشه
الان برای آی‌پی های شخصی که ترافیک رو رد نمیکنن به کلادفلر دیگه کار نخواهد کرد
