### ISSUE TITLE
Signal 13 error

### ISSUE THREAD

**Issue by hoseinnikkhah** [MortezaBashsiz/CFScanner#5]
shell works fine but something that caught my eye is this error, which happens regularly after checking several IPs, I really don't know if this is the reason behind lots of failed attempts or not. I strongly believe it is broken pipe error and can be fixed. As far as I know it should not affect main code and it's nothing to worry about. 
```
xargs: echo: terminated by signal 13
environment: line 6: bc: command not found
```

**Comment by MortezaBashsiz** [comment]
The reason behind failed is not this issue
Do you have bc installed on your Linux?
How many threads you have and with how many parallel have you executed?

**Comment by hoseinnikkhah** [comment]
I have bc installed which is the reason why I am amazed by it, I will try it on my other machine.
I believe it was 16 parallel, I can't recall how many it was.
I'll update you once I check the shell on my other device

**Comment by hoseinnikkhah** [comment]
@MortezaBashsiz 
I checked on my other machine and noticed that this code runs fine, it was a CPU malfunction and good news, code ran successfully after I updated all my packages and upgrading my CPU, it seems like my other machine could not handle too many parallels and instead 16 I may entered 166 or less.
Anyway problem is fixed by a minor upgrade.
