### ISSUE TITLE
تست آپلود کنار دانلود

### ISSUE THREAD

**Issue by NabiKAZ** [MortezaBashsiz/CFScanner#50]
دیدم نوشته بودی تست سرعت دانلود هم اضافه کردی. این خیلی مفیده.
اما میخواستم بگم این روزها چیزی که بیشتر از دانلود اذیت میکنه حداقل روی آی‌پی‌های کلودفلیر، آپلوده.
یعنی اغلب آی‌پی‌ها دانلود خوبی میدن اما آپلود اونها زیر ۱ مگ هست.
گفتم شاید بخوای به عنوان یه فیچر، تست آپلود هم کنار دانلود داشته باشی.

**Comment by MortezaBashsiz** [comment]
درود
متاسفانه نمیتونم اینو اضافه کنم
مگر اینکه یه اسکریپت جدا براش بنویسم

**Comment by NabiKAZ** [comment]
موضوع برای قبل بوده ولی خب ظاهراً ناممکن رو ممکن کردی چون الان توی همین اسکریپت پیادش کردی ;-)
خسته هم نباشید (:
احتمالاً توی برنامتون هست که برای نسخه ویندوزی هم اضافه بشه.
راستی حس میکنم اینکه روی bash موندید یکم دست و پاتون بسته شده. البته قویه ولی شاید به اندازه یه زبان برنامه‌نویسی سطح بالا مثه پایتون یا گو نتونه باشه. برای اوایل خوب بود که کار مختصر بود ولی الان که داره شاخ و برگ پیدا میکنه و هر بار نیازها بیشتر میشه. شاید بد نباشه به مهاجرت فکر کنید (:
