### ISSUE TITLE
Termux problem while running bash version

### ISSUE THREAD

**Issue by ashaghal** [MortezaBashsiz/CFScanner#500]
سلام در نسخه های ابتدایی نسخه bash روی termux  قابل اجرا بود‌. اما بعد از مدتی ارور زیر دیده میشد. لازم به ذکر همچنان روی userland قابلیت اجرا داره روی اندروید اما روی termux این ارور داده میشه.
![IMG_20230422_120518.jpg](https://user-images.githubusercontent.com/39614484/233773131-03211732-1b93-45d1-b890-42cfccfc29e8.jpg)

**Comment by MortezaBashsiz** [comment]
درود این مشکل از اسکریپت نیست
عدم سازگاری باینری v2ray با ترموکس شماست
