### ISSUE TITLE
ایراد در اجرای برنامه در ویندوز

### ISSUE THREAD

**Issue by aboozar1368** [MortezaBashsiz/CFScanner#502]
main.py", line 15, in <module>
    from .args.parser import parse_args
ImportError: attempted relative import with no known parent package

**Comment by tempookian** [comment]
لطفا از این طریق نصب کنید
```bash
pip install cfscanner
```
یا
```bash
python -m pip install cfscanner
```


بعد از نصب برای اجرا:
```bash
cfscanner
```
یا
```bash
python -m cfscanner
```

ممنون می‌شم اگر نتیجه رو اطلاع بدید

**Comment by aboozar1368** [comment]
ممنون مشکل حل شد
