### ISSUE TITLE
فایل debug م

### ISSUE THREAD

**Issue by Hazily1536** [MortezaBashsiz/CFScanner#504]
اسکن با کانفیگ و بی کانفیگ کار نمیکنه! مشکل از کجاست؟
ممنون

[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/11302003/debug.txt)

**Comment by goingfine** [comment]
این رنج که کلا ظاهرا آی پی سالم نداره
او رنج های دیگه بگردید

**Comment by mobagheri** [comment]
با سلام. فایل دیباگ را خدمتتان ارسال میکنم تا اگر میشه کمک کنید مشکل عدم یافتن آی پی رو حل کنم. ممنون.
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/11324839/debug.txt)

**Comment by aliravaghi** [comment]
سلام ممنون بخاطر تلاش هایی که میکنید، جدیدا که اسکن میکنم معمولا ارور میده میخواستم بدونم این ارور ها بخاطر چیه؟ خودم از فایل debug.txt چیزی متوجه نشدم 
[debug.txt](https://github.com/MortezaBashsiz/CFScanner/files/11326074/debug.txt)

**Comment by goingfine** [comment]
@mobagheri  
تست فرانتینگ  شما هم خطا داره میده
فیلترشکنی چیزی اگه روشنه خاموش کنید و ضمنا ببینید این ادرس رو میتونید باز کنید
https://speed.cloudflare.com

**Comment by goingfine** [comment]
@aliravaghi 
شما هم همینطور

**Comment by aliravaghi** [comment]
> @aliravaghi شما هم همینطور

ممنون بخاطر پاسخگویی
لینک رو چک کردم باز شد، فیلترشکنی هم باز نبود و این مشکل فقط روی بعضی از رنج آی پی ها پیش میاد

**Comment by goingfine** [comment]
ممکنه اون رنج ها مشکل داشته باشن یا بلاک شده باشن. ضمنا به سرعت اینترنت هم بستگی داره. دانلود تایم اوت رو هم میتونید روی عدد بالاتر تنظیم کنید ببینید بهتر میشه یا نه
