### ISSUE TITLE
باگ: مشکل گیر کردن برنامه در زمان ساخت فایل آپلود

### ISSUE THREAD

**Issue by NabiKAZ** [MortezaBashsiz/CFScanner#507]
از CentOS 7.9.2009 استفاده میکنم.

به این قسمت میرسه و گیر میکنه:
```
You are testing download
You are testing upload
making upload file by size 102400 Bytes in /CFScanner/bash/tempConfig/upload_file
```

کد رو نگاه کردم و دیدم مربوط به dd بود.

دستی زدم که دیدم سرعت بسیار کم و در حد صفر است:
```
dd if=/dev/random of="aaa" bs=1024 count=100 status=progress
dd: warning: partial read (20 bytes); suggest iflag=fullblock
26 bytes (26 B) copied, 32.140036 s, 0.0 kB/s^C
```

روی چند سرور دیگر تست کردم نتیجه همین بود. البته روی یک سرور درست و سریع رد شد.

اینجا گفته شده از urandom استفاده بشه:
https://stackoverflow.com/a/4819457/1407491

تست کردم و دیدم نتیجه خوب بود:
```
dd if=/dev/urandom of="aaa" bs=1024 count=100 status=progress
100+0 records in
100+0 records out
102400 bytes (102 kB) copied, 0.00454256 s, 22.5 MB/s
```

اما میزان فایل ساخته شده متفاوت بود. حدس زدم باید تغییری در کد داده بشه.
به کد که نگاه کردم دیدم ضربدر ۱۰۲۴ میکنه تا با کیلوبایت کار کنه. مثال دستورات هم داریم:

```
dd if=/dev/random of="aaa" bs=1024 count=10000 status=progress
dd: warning: partial read (86 bytes); suggest iflag=fullblock
231036 bytes (231 kB) copied, 1.000256 s, 231 kB/s
0+10000 records in
0+10000 records out
357133 bytes (357 kB) copied, 1.55922 s, 229 kB/s

dd if=/dev/urandom of="aaa" bs=1024 count=10000 status=progress
10000+0 records in
10000+0 records out
10240000 bytes (10 MB) copied, 0.10041 s, 102 MB/s
```

خب مشخصه برای عدد 10000 حجم فایل باید 10240000 بایت باشه درحالی که در random این عدد 231036 محاسبه شده. اما در urandom درسته.
بنابراین به نظر میرسه با این تغییر علاوه بر مشکل سرعت و گیر کردن برنامه، مشکل محاسبه حجم فایل هم خود به خود حل میشه.

اگر در توزیع‌های دیگه مشکلی رخ نمیده من یه پول‌رکوئست میزنم جهت بررسی.

**Comment by NabiKAZ** [comment]
در ضمن این ضربدر ۲ رو درک نکردم. خواستم حذفش کنم گفتم قبلش بپرسم.

https://github.com/MortezaBashsiz/CFScanner/blob/b6aefab2dbfdf5b1e2ab5da073b2aa193feb442d/bash/cfScanner.sh#L874

**Comment by MortezaBashsiz** [comment]
درود
توی توزیع‌های دیگه مشکل وجود نداره
در خصوص اون ضربدر ۲ شدنش هم برای اینه که ما توی اسکریپت ۲ ثانیه زمان میدیم تا دانلود یا آپلود رو انجام بده
یعنی اگه طرف ۱۰۰ کیلوبایت در ثانیه میخواد تست بگیره فایل رو ۲۰۰ درست میکنیم و ۲ ثانیه زمان میدیم یعنی ۲۰۰ کیلوبایت بر ۲ ثانیه
نیازی هم به پول ریکوست نیست و این در توزیع‌های دیگه حتی مک هم درست کار میکنه
من حتی توی سنت او اس هم تست گرفتم اوکی بود
ولی به هر حال شما میتونید برای فورک خودتون تغییراتی که مد نظرتونه رو انجام بدید

**Comment by NabiKAZ** [comment]
و درمورد حجم فایل ساخته شده چطور؟ که bs=1024 count=10000 شده 357133 bytes

**Comment by MortezaBashsiz** [comment]
این فکر کنم مشکل از جای دیگری باشد
من که میزنم درسته

![image](https://user-images.githubusercontent.com/19620677/233932363-0565c009-2b3d-4e11-ae86-1aa2cf6c66fc.png)

**Comment by NabiKAZ** [comment]
درسته موضوع مفصل بود زیاد عمیق نشدم توش اما در نهایت برای راه‌حل همه جا پیشنهاد استفاده از urandom بجای random بود.

https://unix.stackexchange.com/questions/32988/why-does-dd-from-dev-random-give-different-file-sizes

https://superuser.com/questions/1388082/dd-is-producing-a-32-mb-random-file-instead-of-1-gb
