### ISSUE TITLE
مشکل اسکنر ویندوز

### ISSUE THREAD

**Issue by Obeid1375** [MortezaBashsiz/CFScanner#512]
با ارزوی موفقیت و خسته نباشید.

توی نسخه جدید اسکنر ویندور روی حالت آپلود تنها یا دانلود و آپلود میزارم هیچ نتیجه ای نمیده.

فقط با دانلود تنها.

نت آسیاتک.

**Comment by goingfine** [comment]
تارگ اسپید مربوط به اپلود رو روی سرعت پایین تری بزارید
