### ISSUE TITLE
Could not load scan result file from disk: 'E:\ip.txt'

### ISSUE THREAD

**Issue by kamiepic** [MortezaBashsiz/CFScanner#513]
سلام مشکل وارد کردن ایپیارو دارم
ورژن های قبلی اوکیه و ایپیارو راحت لود میکنه ولی این ورژن وقتی ایپیو بهش میدم این خطارو میده
اسکنر ویندوز ورژن v1.2.8515.31784-Windows-x64

**Comment by goingfine** [comment]
تو نسخه حدید یک تغییراتی توی ورودی خروجی ایجاد شده که ممکنه از خروجی نسخه قبلی نتونید توی این نسخه استفاده کنید

اگر مشکل از این نیست برنامه رو توی حالت دیباگ بالا بیارید و بعد فایل رو بدید به برنامه بعدش فایل debug.txt رو بزارید اینجا
https://github.com/MortezaBashsiz/CFScanner/discussions/331

**Comment by kamiepic** [comment]
سلام بله فایلو که ریختم درست شد,خیلی ممنون
