### ISSUE TITLE
باگ بش روی ابونتو

### ISSUE THREAD

**Issue by amirakrami852** [MortezaBashsiz/CFScanner#514]
سلام و خسته نباشید
وقتی bash رو روی ابونتو اجرا میکنم بعد از کارکرد 1 تا 10 درصدی گه کار نمیکنه و هنگ میکنه
و سوال دوم اینکه این عددی که میده برامون تو تست برای دانلود و آپلود همون پینگ هستش درسته یعنی هر چی پایین تر بهتر ؟؟؟

**Comment by MortezaBashsiz** [comment]
درود
هنگ میکنه یعنی چی؟
شما باید اطلاعات بیشتری بدید لطفا موارد زیر رو بگید
مشخصات سخت افزاریتون چیه مشخصا تعداد ترد سی‌پی‌یو
دستوری که ران میکنید چی هست دستور کامل رو بزارید
نمونه خروجی از ارور یا عکسی باشه خوبه

در مورد سوال دومتون اون عدد ریسپانس تایم هست هرچی پایین‌تر باشه بهتره

سپاس

**Comment by amirakrami852** [comment]
سی پی یو که استفاده میکنم پنتیوم هستش 
با این دستور سرچ میزنم


bash cfScanner.sh -c arash.config -v NO -m SUBNET -t BOTH -p 8 -n 8 -s 200 
ولی بعد از کارکرد کوتاهی حدودا 2 تا 5 درصدی سرج آی پی ها تو همون قسمت میمونه و جلو نمیره هنگ میکنه انگار البته ویندوز هنگ نمیکنه خود برنامه ابونتو هم هنگ نمیکنه ولی دیگه سرچ انجام نمیشه
