### ISSUE TITLE
Android V1.0.6-C6 bugs

### ISSUE THREAD

**Issue by tkalen1** [MortezaBashsiz/CFScanner#516]
ممنون بابت اسکنر
چند تا مورد تو نسخه اندروید وجود داره
۱.نوتیفیکشن بابت دسترسی ول کن نیست، وقتی از یه تب به تب دیگه میری
۲.در حین سرچ اگر رو تب دیگه کلیک کنی کرش می‌کنه
۳.وقتی کرش می‌کنه اسکن رو سیو نمیکنه
۴.اگر اسکن کامل رندوم باشه خیلی بهتره(همزمان از همه رنج آی پی ها اسکن بگیره، نه اینکه یکی رو بره تا انتها بعد بره سراغ بعدی- یا این موضوع اپشنال باشه)

**Comment by 0ut0fCode** [comment]
1. دلیل اصرار اپ برای گرفتن دسترسی نوتیفیکیشن به خاطر محدودیت اندروید 12 به بالا برای اجرای سرویس در پس زمینه هست ، در صورتی که شما مجوز نوتیفیکیشن رو ندید اپ نمیتونه در پس زمینه اجرا بشه و با جابجا شدن بین تب ها یا حتی خاموش شدن صفحه گوشی پروسه اسکن خاتمه پیدا میکنه ، ولی در نسخه بعد سعی میکنیم خطای گزارش شده رو رفع کنیم اما روشی برای دور زدن این محدودیت در صورت عدم اعطای مجوز نوتیفیکشن وجود نداره.
2. دلیل این مشکل هم همون مورد قبلی هست که خطا رو در نسخه بعد رفع میکنیم
3. اینم به خاطر همون خطا های قبلی هست 
4. با تشکر از پینشهادتون ، این مورد رو برای فیچر های نسخه های اینده در نظر میگیریم
