### ISSUE TITLE
باگ های نسخه اندروید

### ISSUE THREAD

**Issue by Mohammadnyc** [MortezaBashsiz/CFScanner#519]
سلام وقت بخیر خسته نباشید
یه چندتا مورد باگ و کرش کردن دیدم تو استفاده که گفتم اینجا اطلاع بدم :
۱-وقتی یه سابنت مثلا سنگین مثل 1.1.0.0/16 میزنم اسکن کنه هیچ اتفاقی نمیوفته و بعد پیام cfscanner isn't responding  میاد و در اخر برنامع کرش میکنه و میوفته بیرون
۲-توی اسکن ایرانسل سرعت اسکن خوبه ولی توی همراه اول خیلی کند پیش میده دلیلشو نمیدونم ولی روی همراه اول خیلی بیشتر کرش می‌کنه برنامه و خارج میشه
۳-وقتی کرش میکنه بعضی وقتا history تا اونجایی که اسکن کرده سیو نمیشه که بشه دوباره برگشت و از ادامش اسکن کرد و یه مورد عجیب تر اینکه یه بار بعد اینکه کرش کرد تمام بقیه history ها هم پاک شدن

**Comment by 0ut0fCode** [comment]
تشکر بابت گزارش های ارسالی ؛ تمام موارد در لیست باگ ها قرار گرفتن و در نسخه بعدی فیکس خواهند شد.
