### ISSUE TITLE
چند نکته برای اجرا درست

### ISSUE THREAD

**Issue by whereisafshin** [MortezaBashsiz/CFScanner#52]
سلام دوستان چند نکته وجود داره باید رعایتش کنید اول کار.

1-  کانفیگ vmess خودتون رو بردارید تو فایل config.json.temp قرار بدید مطابق متغیرهایی که ست شده تو port,ip,path,host,servername رو تو کانفیگ خودتون جایگذاری کنید ( نسخه اولیه config.json.temp رو ببینید متوجه میشید).
1-1 نکته = تو قسمت path یک / وجود داره جلوش متغیر ENDPOINTENDPOINT نوشته شده  / رو پاک کنید ( برا اونایی که pathشون / هستش (چون تو کانفیگ ۲تا / میزاره کلا کانفیگ به درستی کار نمیکنه))

2- فایل کانفیگ config.real رو با اطلاعات کانفیگ خودتون تغییر بدید ( host ,ServerName) مطابق کانفیگ خودتون بنویسید ( برای من جفتشون دامنه ی خودم هستش)
3- اگه فایل cfFindIP.sh با ادیتو متنی باز کنید خط 260 رو پیدا کنید اگه ۲۰۰ رو تغییر بدید دیگه نمیره از فلان جا ای پی لیست کنه براتون میاد از فایل cf.local.iplist ای پی هارو میخونه ( این کار باعث میشه هر سری کلی ای پی که کار نمیکنه رو اسکن نکنه ( حتی میتونید تعداد ای پی هارو کاهش بدید من تست کردم تو رنج 45 حدود ۶۰ تا ای پی پیدا کردم البته همشون برام کار نکردن با nekoray تست اسپید دانلود گرفتم متوسط بین 1.5 تا 3 بود سرعتشون))
یکی از دوستان هم اومده تغییراتی داده اسکریپت رو بصورت رنج خاص هم میتونید اسکن کنید ( مورد سوم رو براتون خیلی راحت کرده)
برای اسکن هم یه بسته ساعتی بزنید ( اون رنج هایی که کلا تایم اوت هستن رو پاک کنید تا وقتتون گرفته نشه )

**Comment by MortezaBashsiz** [comment]
درود
مشکل path و سابنتهای کاستوم برطرف شد
