### ISSUE TITLE
پیشنهاد برای بخش رنج های برنامه اندروید

### ISSUE THREAD

**Issue by Mohammadnyc** [MortezaBashsiz/CFScanner#520]
و چنتا پیشنهاد داشتم برای اضافه کردن یه سری قابلیت :
۱-توی بخش اضافه کردن رنج کاستوم گزینه ای برای هر رنج اضافه بشه که بتونیم اون رنج رو بدون پاک کردن از لیست اسکن خارج کنیم ولی همچنان داشته باشیمش برای اسکن های بعدی شاید نیاز شد دوباره فعالش کنیم...
۲-توی بخش رنج های کاستوم اگر بشه تگ گذاشت و فیلتر و دسته بندی کرد رنج هارو برای هر اپراتور کاربری راحت تر میشه

**Comment by 0ut0fCode** [comment]
با تشکر از پیشنهاد های مطرح شده ، برای نسخه های اینده موارد گفته شده رو حتما در نظر خواهیم گرفت .
