### ISSUE TITLE
استفاده از ایپی لیست به جای ایپی رنج

### ISSUE THREAD

**Issue by kamiepic** [MortezaBashsiz/CFScanner#521]
سلام خیلی ممنون بابت اپ اندرویدی
اگ ممکنه قابلیت اضافه کردن ایپی لیست و سرچ بر اساس ایپی لیست خودمو داشته باشیم تا ایپی رنج عالی میشه ممنون

**Comment by 0ut0fCode** [comment]
با عرض سلام 

این مورد در بخش تنظیمات > Cidr Manager قابل دسترسیه ، کافیه شما ای پی رنج های کاستون خودتون رو اضافه کنید و بعدش گزینه استفاده از رنج کاستوم رو تیک بزنید تا صرفا از چیزایی که خودتون وارد کردید استفاده کنه.

**Comment by kamiepic** [comment]
شرمنده فکر کنم خوب متوجه نشدین یا توضیح من کامل نبود
الان توی بخش Cidr manager ما میتونیم فقط آیپی رنج قرار بدیم مثل 25.25.25.0/24 یا هرچی دیگه که رنج باشه
ولی اگه یه قابلیتی بیاد که بشه از ipv4 استفاده بشه مثلا 25.25.25.25 و.... خیلییی عالی تر میشه 
ممنون
