### ISSUE TITLE
افزایش مموری استفاده شده حین اسکن در نسخه پایتون

### ISSUE THREAD

**Issue by tryeverything91** [MortezaBashsiz/CFScanner#522]
برای اسکن ایپی در تعداد بالا نمیشه از اسکریپت پایتون استفاده کرد چون هی مموری رو پر میکنه و نهایتا به صد که برسه سیستم فریز میشه
اگر شدنی هست رفع کنید مشکل رو
تست شده روی ابونتو 22
سپاس

**Comment by tryeverything91** [comment]
من خود ایپی ها رو میذارم برای اسکن. مثلا 1 میلیون ایپی.
تردش رو هم میذارم100 تا 200 تا این حدود. تنها سوییچی هست که استفاده میکنم
ولی ارتباطی فک نمیکنم داشته باشه که سابنت باشه یا ایپی.
من  جدا با یه اسکریپت دیگه سابنت هایی که میخوام رو تمام ایپی هاشونو رو اکسترکت میکنم توی یه فایل تکست و اون ایپی ها رو میذارم برای اسکن

**Comment by tempookian** [comment]
100 خب خیلی زیاده. با ۸ امتحان کنید و لطفا خبر بدید

**Comment by tryeverything91** [comment]
فرقی نکرد فقط اروم تر پر میشه مموری
مساله اینه که نباید هی فزاینده مموری درگیر بشه
 وقتی که دستور رو متقف میکنم یهو کلی از مموری که درگیر بود خالی میشه

**Comment by tempookian** [comment]
لطف دقیق دستوری که باهاش ران می‌کنید و لیست‌ آیپی‌هایی که به مشکل خورده رو قرار بدید تا بررسی بشه. سپاس

**Comment by tryeverything91** [comment]
`cfscanner -t 192 -s ./custom.subnet.txt -n 2`
[custom.subnet.txt](https://github.com/MortezaBashsiz/CFScanner/files/11352760/custom.subnet.txt)

البته فرقی نداره ترد چند باشه و ایپی ها چی باشن. (ترد بالا باشه زودتر رم پرمیشه پایین باشه دیرتر رم پر میشه)
بعد از یک ساعت رم من که 16 گیگ هست از 30 درصد به 80-90 درصد میرسه و وقتی دستور رو متقف میکنم اون مقدار رم ازاد میشه.
به صد درصد برسه سیستم فریز میشه و اسکن ایپی ها ناقص میمونه

**Comment by tryeverything91** [comment]
این مشکل برطرف نشد ؟

**Comment by tempookian** [comment]
در دست بررسیه. 

PRs are as always welcome :)

**Comment by tempookian** [comment]
ایشو رو می‌بندم. لطفا اگر مشکل پابرجا بود ایشوی جدید باز بفرمایید
