### ISSUE TITLE
دقیق نبودن تست در نسخه آندروید و ویندوز

### ISSUE THREAD

**Issue by amirakrami852** [MortezaBashsiz/CFScanner#523]
سلام و خسته نباشید و تشکر بابت نسخه آندروید اسکنر
فقط احساس میکنم دقت تست ها درست نیست من دیشب تو نسخه آندروید روی ایرانسل اسکن کردم و حدودا 300 تا آیپی تو یک ساعت تست بهم داد کمترین پینگ 600 بود که خوب بود ولی بعد از بهینه سازی با تست سرعت برنامه پینگ ها به شدت افزایش پیدا کردن تقریبا دو برابر شدن حالا من گیج شدم اولویت ما پینگ باید باشه یا speed ??? 
در ضمن از دیروز عصر روی برنامه ویندوز روز ایرانسل هم تست کردم کل رنج ها تست شد 1600 تا آیپی داد ولی الان که تست میکنم آی پی ها رو زیاد جالب جواب نمیده 
روی آندروید کانفیگ به صورت زیر بود
v2ray costum کانفیگ شخصی worker 8 speed 500
روی ویندوز کانفیگ خود برنامه با آپلود 50k/s دانلود 200k/s و thread 8

**Comment by alizarei54** [comment]
سلام، 
بله منم تست کردم یه رنجی که برام کار میکرد رو با نرم‌افزار تست کردم ولی اون رنج ها رو شناسایی نکرد، نمیدونم شاید من جایی اشتباه کردم
