### ISSUE TITLE
توضیح در مورد کانفیگ شخصی یا خود برنامه

### ISSUE THREAD

**Issue by amirakrami852** [MortezaBashsiz/CFScanner#524]
ممنون میشم توضیح در مورد اینکه اسکنر با کانفیگ شخصی دقیق تره یا کانفیگ خود برنامه ؟
منظور همون مشخصات سرور v2ray که تو برنامه هست چه آندروید چه ویندوز 
حتما باید آدرس سرور خودمون رو بدیم ؟
و وقتی با کانفیگ شخصی تست میکنیم به دلیل استفاده از دامین شخصی و بالا رفتن درخواست ها در ا نتیجه تست و اسکن آیپی مشکلی برای سرور مون پیش نمیاد ؟

**Comment by MortezaBashsiz** [comment]
درود

اسکنر با کانفیگ شخصی سریعتره
به این دلیل که کانفیگ شخصی رو فقط خودتون استفاده میکنید ولی کانفیگ برنامه رو هزاران نفر
توی فایل کانفیگ باید مشخصات کانفیگ خودتون رو مشابه کانفیگ برنامه بزارید
تعداد ریکوستی که اسکنر میفرسته در مقایسه با مصرف شخصی خودتون خیلی کم هست و نگران فیلتر شدن کانفیگ خودتون
آی‌پی سرور که پشت کلادفلر هست و اصلا براش مشکلی پیش نمیاد
سپاس
