### ISSUE TITLE
 آیا روی ورژن خاصی به بعد از اندروید فقط نصب میشه؟

### ISSUE THREAD

**Issue by PERSIA-MISI** [MortezaBashsiz/CFScanner#525]
هیچکدوم از این لینکها روی گوشی من که اندروید 6 هست کار نمیکنه
مشکلش چیه؟
عکس خطاشو هم گذاشتم
![Capture+_2023-04-28-18-45-26](https://user-images.githubusercontent.com/124380548/235186997-8c878113-d48d-4f0c-ae85-72ec3456e0a5.png)

**Comment by 0ut0fCode** [comment]
بله ،در حال حاضر فقط روی اندروید 7 و بالاتر قابل اجراست.
در روز های آینده احتمالا مینیمم اندروید مورد نیاز رو به 5 کاهش بدیم.
