### ISSUE TITLE
امکان توقف موقت (پاز) برنامه

### ISSUE THREAD

**Issue by liketolivefree** [MortezaBashsiz/CFScanner#530]
**Is your feature request related to a problem? Please describe.**
خیلی خوب میشد اگر امکان پاز کردن برنامه وجود داشت. این امکان مخصوصا موقع اسکن رنج های گسترده آی پی کارسازه. چون موقع استفاده از این برنامه فیلترشکن باید قطع باشه. یه وقتهایی آدم یه کار ضروری براش پیش میاد و باید فیلترشکن رو روشن کنه (یا کل سیستم رو تونل کنه) اونوقت باید برنامه رو قطع کنی. وقتی دوباره اجراش میکنی نمیدونی دفعه قبل تا کجای یه رنج پیش رفته بود.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tempookian** [comment]
کدوم نسخه؟ ویندوز؟ پایتون؟ اندروید؟

**Comment by liketolivefree** [comment]
ویندوز

**Comment by goingfine** [comment]
نسخه ویندوزی گزینه توقف داره

**Comment by liketolivefree** [comment]
کجاست این گزینه. چرا من پیداش نمیکنم پس؟
منظورم توقف موقته ها. مثلا داری یه رنج 500 هزار تایی رو اسکن میکنی (که حدود 40 تا 50 ساعت طول میکشه). تمام این مدت VPN باید خاموش باشه. مثلا 100 هزار تاشو اسکن کرده ولی یهو یه کار فوری پیش میاد که باید VPN رو روشن کنی یا بدتر از اون، اینترنتت قطع میشه و خلاصه میخای یه مدت اسکن متوقف بشه. اگه استپ بزنی، دیگه نمیتونی از همونجا ادامه بدی. دفعه بعد هم که شروع کنی مجددا باید اون 100 هزار تا اسکن کنی بیخودی.
