### ISSUE TITLE
ترکر (ردیاب) در نسخه اندروید

### ISSUE THREAD

**Issue by liketolivefree** [MortezaBashsiz/CFScanner#531]
**Is your feature request related to a problem? Please describe.**
آیا واقعاً وجود این همه ترکر در نسخه اندروید برنامه لازمه؟ نمیخام ناشکری کنم و مطمئن باشین ارزش زحمتهای شما رو میدونم. اما وجود این همه ترکر عملاً این اپلیکیشن رو برای خیلی از کاربران بلااستفاده کرده. 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0ut0fCode** [comment]
با عرض سلام 

ترکر ها برای گزارش کرش های مربوط به کاربر ها به همراه مدل دستگاه و همچنین گزارش اماری از تعداد نصب برنامه مورد استفاده قرار میگیره که از سورس برنامه این موارد به طور شفاف قابل بررسی هستن ، اما به زودی در نسخه های اینده قبل از مقدار دهی اولیه سرویس های مربوط به گزارش خطا و انالیز اماری از کاربر مجوز دریافت خواهد شد.

**Comment by liketolivefree** [comment]
عرض ادب.
درسته بله. امیدوارم همینطور بشه و این مجوز واقعا «مجوز» باشه. البته حقیقتش امیدوارم که نسخه های بعدی کلاً از وجود این موجودات منحوس پاک بشن.
 آیا آگاهی به این اطلاعات فقط با ترکرها ممکنه؟ البته من نمیدونم این اطلاعات چقدر برای عملکرد صحیح اپلیکیشن ضروری هستن، ولی اینو میدونم که اپ های خیلی زیادی دارن بدون حتی یک ترکر، کارشون رو تمام و کمال انجام میدن، اپ هایی حتی از جنس همین اپ.

با توجه به سابقه ترکرها و گردانندگان اصلیشون، استفاده از این اپ با این شرایط قطعاً با طیب و فراغ خاطر همراه نخواهد بود (برای من و بیشک، خیلی های دیگه) و امیدوارم شما در مقام یکی از تولیدکنندگان خوشنام محتوا در گیتهاب - پاتوق و مأمن دغدغه مندهای امنیت و حریم خصوصی - این نگرانی رو درک کنین.
ممنون از لطف و پاسخگویی تون
