### ISSUE TITLE
USE CF's API to add found IP's as A records

### ISSUE THREAD

**Issue by A5DkjGQUZx** [MortezaBashsiz/CFScanner#536]
Would be great if we can have an option (especially with the Python version) to allow us auto update/replace our A records hosted with CF.
There could be a config file CF's API credentials and also a switch for Update or Repalce.
Update: add found IP's as a new A record
Replace: wipe all old A records and just add new found IP's
https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/
Thanks :)

@tempookian

**Comment by MortezaBashsiz** [comment]
Hi

Thank you so much for your contribution and this suggestion
Unfortunately we are not going to proceed this since we do not have any plan for it, and we prefer to focus on scanner's main goal
