### ISSUE TITLE
نسخه گولنگ

### ISSUE THREAD

**Issue by karimzzzm** [MortezaBashsiz/CFScanner#537]
سلام بچه ها خسته نباشید 
دمتون گرم 
اسکنر گولنگ رو روی ویندوز نصب میکنم ولی نمیتونه ریزالت رو ذخیره کنه 
هر دو حالت یعنی جیسون و اکسل رو هم تست کردم فرقی نکرد 
لطفا اگر روش خاصی داره که من نمیدونم بهم بگید

**Comment by karimzzzm** [comment]
Error creating interim results file: failed to create interim results file: open C:\Users\Jazireh\Desktop\gggg\CFScanner\golang\result\2023-05-10_05:47:19_result.csv: The filename, directory name, or volume label syntax is incorrect.

اینم متن ارور هست که به خاطر وجود کارکتر های غیر مجاز ویندوز توی اسم فایل که میخواد ذخیر کنه به وجود میاد 




ممنون از زحماتی که می کشید

**Comment by rahman8521** [comment]
سلام من همون golang که تو پوشه اصلی هست رو روی ویندوز استفاده میکنم 
باید برنامه go نصب کنید که کامپایل بشه go1.20.3.windows-amd64

همین برنامه شما هم واشه من همین ارور رو میده 

پیشنهاد میکنم go رو نصب کنید

**Comment by SonyaCore** [comment]
درود این باگ در آخرین نسخه برطرف شده.
لطفا آخرین نسخه را از این قسمت دریافت کنید :

https://github.com/MortezaBashsiz/CFScanner/releases/tag/v23.05.11
