### ISSUE TITLE
فیلتر شدن ادرس speed.cloudflare

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#538]
مشکلی که از امروز پیش اومده اینه که ادرس speed.cloudflare.com روی یه سری دیتاسنتر ها فیلتر شده
و واسه همین عملا اصلا نمی شه از اسکنر استفاده کرد
پیشنهادی دارید که چطور می شه این مشکل رو حل کرد ؟ 
ممنونم

**Comment by MortezaBashsiz** [comment]
درود
مدل اسکنر ما اینه که خودمون دستی دامنه اسپید رو به آی پی ریزالو میکنیم
یعنی اصلا برای ریزالو دامنه سراغ دی ان اس نمیریم
فیلتر هم بشه تاثیری توی عملکرد نداره

**Comment by Jolge100** [comment]
به نظرت مشکل چی می تونه باشه ؟ 
چون چند نفر دیگه هم همین مشکل اسکن ایپی رو دارن
روی دیتاسنتر ها یعنی ایپی های کلود رو بستن ؟

**Comment by MortezaBashsiz** [comment]
ریپوزیتوریتون رو آپدیت کنید همین الان یه تغییری دادم ممکنه درست شده باشه

این قسمت مشکل هست که احتمال میدم به خاطر باینری باشه
`The SSL connection could not be established, see inner exception`
شما یکی از اون کانفیگ ها رو با ویتوری دستی ران کنید اونی که مطمینید درسته
بعدش روی آی‌پی لوپبک یه پورت ساکس باز میکنه با ساکس ۵ ست کنید روی بروزرتون و تست کنید ببینید اسپید رو باز میکنه یا نه
من به نظرم مشکل سر عدم سازگاری وی تو ری با لایبرریهای سیستم عامله

اون تکته آخر اینکه اگه میبینید فایل نمیسازه بخاطر اینه که کلا اون آی‌پی تستش فیل شده حتی بدون وی پی ان هم براتون کار نمیکنه یعنی اون قسمت فرانتینگ رو رد نکرده
سپاس

**Comment by Jolge100** [comment]
بله اینکاری که فرمودین رو انجام دادم البته روی نسخه ویندوز یه رنج ایپی که روش ایپی سالم داشتم رو اسکن زدم و خیلی با سرعت همه رو رد کردو دستی یه دونه از همون ایپی ها رو ران کردم روی SOCKS5 که خود کانفیگ ساخته بود و بدون مشل کار هم کرد
الان از همین رنج که اسکن زدم روی نسخه ویندوز هیچی بهم نداده که توی عکس معلومه
![image](https://user-images.githubusercontent.com/118624183/237043730-06adf04c-c936-418d-b5ea-c99967235ac0.png)

عکس دوم هم مربوط به ایپی هستش که دستی توی کانفیگ گذاشتم
![image](https://user-images.githubusercontent.com/118624183/237045330-111b41fe-39a6-4157-bd47-ed9adb6623fa.png)


توی نسخه bash که کلا هیچ ایپی حتی با تست سرعت اپلود 1 کیلوبایت بهم نمی ده

**Comment by MortezaBashsiz** [comment]
من دقیقا همین رنج 91.195.110.0/24 رو تست گرفتم و کار کرد توی نسخه بش
شما کانفیگ پیشفرض میزارید یا کانفیگ خودتون رو استفاده میکنید؟

**Comment by Jolge100** [comment]
اگر هم فکر می کنید کمکی می کنه یه راه ارتباطی بهم بدید براتون مشخصات یه سرور ایران بدم تست کنید

**Comment by Biftor** [comment]
من هم همین چند دقیقه پیش ۳۰۰۰ هزارتا ای پی اسکن شده تمیز و کثیف رو چند بار با اسکنر ویندوز اسکن کردم همه رو رد کرد. ترافیک رو چک کردم اصلا اپلود دانلود نداشتم
همون ۳۰۰۰ تا ای پی رو با نسخه گو تست کردم یه چیزایی داره پیدا میکنه الان
تا دیروز پریروز نسخه ویندوز اوکی بود چون خوبتر نتیجه میداد من اکثرا با اون اسکن میکردم

**Comment by Biftor** [comment]
گویا ادرس speed.cloudflare.com اختلال خورده 
 % ping speed.cloudflare.com
PING speed.cloudflare.com (10.10.34.36): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
^C

**Comment by MortezaBashsiz** [comment]
> > من دقیقا همین رنج 91.195.110.0/24 رو تست گرفتم و کار کرد توی نسخه بش شما کانفیگ پیشفرض میزارید یا کانفیگ خودتون رو استفاده میکنید؟
> 
> هر دو رو استفاده می کنم هم از کانفیگ خودتون هم کانفیگ vmess خودم و همینطور vless خودم توی نسخه ویندوز شک کردم شاید دامین فیلتر شده چون یهو بعد 3 ماه مشکل پیدا کرد که اونم نبود تست کردم چون همونطور که گفتم دقیقا همین کانفیگ داره الان روی همین سرور با همین ایپی کار می کنه اما تو نتایج اسکن نمیاد نسخه bash حالتی مثل debug یا log نداره بشه جزیی تر بهتون اطلاعات بدم ؟ و یه نکته اخر هم اینکه شما با اینترنت داخل تست زدی یا سرور خارج
> 
> پی نوشت: چون از دیروز غروب که یهو اینجوری شد من خیلی تو گروه های تلگرامی جستجو کردم خیلی های دیگه این مشکل رو داشتن و لیتک این تاپیک رو دادم بهشون که بیان بگن . نمی دونم چرا نیومدن :D

دستوری که باهاش بش رو اجرا میکنید بگید لطفا

**Comment by MortezaBashsiz** [comment]
> گویا ادرس speed.cloudflare.com اختلال خورده % ping speed.cloudflare.com PING speed.cloudflare.com (10.10.34.36): 56 data bytes Request timeout for icmp_seq 0 Request timeout for icmp_seq 1 Request timeout for icmp_seq 2 Request timeout for icmp_seq 3 Request timeout for icmp_seq 4 Request timeout for icmp_seq 5 Request timeout for icmp_seq 6 Request timeout for icmp_seq 7 Request timeout for icmp_seq 8 ^C

در خصوص اسکنر بش کلا اگه فیلتر هم بشه تاثیری نداره چون توی اسکریپت دامنه رو خودمون ریزالو میکنیم
حتما ریپوزیتوری رو سینک کنید و تغییرات آخر رو بگیرید با بش امتحان کنید
و دستوری هم که باهاش اجرا میکنید رو بگید

**Comment by Jolge100** [comment]
> > > من دقیقا همین رنج 91.195.110.0/24 رو تست گرفتم و کار کرد توی نسخه بش شما کانفیگ پیشفرض میزارید یا کانفیگ خودتون رو استفاده میکنید؟
> > 
> > 
> > هر دو رو استفاده می کنم هم از کانفیگ خودتون هم کانفیگ vmess خودم و همینطور vless خودم توی نسخه ویندوز شک کردم شاید دامین فیلتر شده چون یهو بعد 3 ماه مشکل پیدا کرد که اونم نبود تست کردم چون همونطور که گفتم دقیقا همین کانفیگ داره الان روی همین سرور با همین ایپی کار می کنه اما تو نتایج اسکن نمیاد نسخه bash حالتی مثل debug یا log نداره بشه جزیی تر بهتون اطلاعات بدم ؟ و یه نکته اخر هم اینکه شما با اینترنت داخل تست زدی یا سرور خارج
> > پی نوشت: چون از دیروز غروب که یهو اینجوری شد من خیلی تو گروه های تلگرامی جستجو کردم خیلی های دیگه این مشکل رو داشتن و لیتک این تاپیک رو دادم بهشون که بیان بگن . نمی دونم چرا نیومدن :D
> 
> دستوری که باهاش بش رو اجرا میکنید بگید لطفا

 bash cfScanner.sh -c config.default -v YES -m SUBNET -t UP -p 8 -n 3 -s 10 -f custom.subnets
 
 البته سرعت رو چون الان هیچی نمی ده روی 10 گذاشتم

**Comment by MortezaBashsiz** [comment]
> > > > من دقیقا همین رنج 91.195.110.0/24 رو تست گرفتم و کار کرد توی نسخه بش شما کانفیگ پیشفرض میزارید یا کانفیگ خودتون رو استفاده میکنید؟
> > > 
> > > 
> > > هر دو رو استفاده می کنم هم از کانفیگ خودتون هم کانفیگ vmess خودم و همینطور vless خودم توی نسخه ویندوز شک کردم شاید دامین فیلتر شده چون یهو بعد 3 ماه مشکل پیدا کرد که اونم نبود تست کردم چون همونطور که گفتم دقیقا همین کانفیگ داره الان روی همین سرور با همین ایپی کار می کنه اما تو نتایج اسکن نمیاد نسخه bash حالتی مثل debug یا log نداره بشه جزیی تر بهتون اطلاعات بدم ؟ و یه نکته اخر هم اینکه شما با اینترنت داخل تست زدی یا سرور خارج
> > > پی نوشت: چون از دیروز غروب که یهو اینجوری شد من خیلی تو گروه های تلگرامی جستجو کردم خیلی های دیگه این مشکل رو داشتن و لیتک این تاپیک رو دادم بهشون که بیان بگن . نمی دونم چرا نیومدن :D
> > 
> > 
> > دستوری که باهاش بش رو اجرا میکنید بگید لطفا
> 
> bash cfScanner.sh -c config.default -v YES -m SUBNET -t UP -p 8 -n 3 -s 10 -f custom.subnets
> 
> البته سرعت رو چون الان هیچی نمی ده روی 10 گذاشتم

لطفا تعداد پروسس رو کم کنید و کلا یک بزارید ببینید فرقی میکنه یا نه
و مطمین بشید که از نخسه آخر استفاده میکنید و یه گیت پول هم بزنید

**Comment by Jolge100** [comment]
> > > > > من دقیقا همین رنج 91.195.110.0/24 رو تست گرفتم و کار کرد توی نسخه بش شما کانفیگ پیشفرض میزارید یا کانفیگ خودتون رو استفاده میکنید؟
> > > > 
> > > > 
> > > > هر دو رو استفاده می کنم هم از کانفیگ خودتون هم کانفیگ vmess خودم و همینطور vless خودم توی نسخه ویندوز شک کردم شاید دامین فیلتر شده چون یهو بعد 3 ماه مشکل پیدا کرد که اونم نبود تست کردم چون همونطور که گفتم دقیقا همین کانفیگ داره الان روی همین سرور با همین ایپی کار می کنه اما تو نتایج اسکن نمیاد نسخه bash حالتی مثل debug یا log نداره بشه جزیی تر بهتون اطلاعات بدم ؟ و یه نکته اخر هم اینکه شما با اینترنت داخل تست زدی یا سرور خارج
> > > > پی نوشت: چون از دیروز غروب که یهو اینجوری شد من خیلی تو گروه های تلگرامی جستجو کردم خیلی های دیگه این مشکل رو داشتن و لیتک این تاپیک رو دادم بهشون که بیان بگن . نمی دونم چرا نیومدن :D
> > > 
> > > 
> > > دستوری که باهاش بش رو اجرا میکنید بگید لطفا
> > 
> > 
> > bash cfScanner.sh -c config.default -v YES -m SUBNET -t UP -p 8 -n 3 -s 10 -f custom.subnets
> > البته سرعت رو چون الان هیچی نمی ده روی 10 گذاشتم
> 
> لطفا تعداد پروسس رو کم کنید و کلا یک بزارید ببینید فرقی میکنه یا نه و مطمین بشید که از نخسه آخر استفاده میکنید و یه گیت پول هم بزنید

کلا پاکش کردم دوباره نصب کردم و ترید رو هم 1 گذاشتم و تست اپلود اسپید 100 کیلوبایت رو امتحان کردم و نه متاسفانه تغییری ایجاد نشد

**Comment by MortezaBashsiz** [comment]
خب
حالا یکاری بکنید با باینتری وی تو ری اون فایل کانفیگ رو بیارید بالا مثلا مثل زیر که مطمینید اون آی‌پی درسته

`[/tmp/CFScanner/bin]>$ ./v2ray -c ../bash/tempConfig/config.json.91.195.110.15`

**Comment by Jolge100** [comment]
این خروجی رو بهم داد

curl -x "socks5://127.0.0.1:3560" --resolve "speed.cloudflare.com:443:154.85.99.126" "https://speed.cloudflare.com/__down?bytes=100"
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by Jolge100** [comment]
افتاب امد دلیل افتاب
عرض کردم خیلی ها مشکل دارن این یه نمونه لایو که الان راجبش داره صحبت می شه d:

![image](https://github.com/MortezaBashsiz/CFScanner/assets/118624183/e2f2dbca-826a-42e2-9011-f9e3b26f76ff)

**Comment by MortezaBashsiz** [comment]
عجیبه
الان این فایلی که درست شده برای این آی‌پی 154.85.99.126 باید حتما توسط اسکریپت درست شده باشه درسته؟
اگه پاسخ سوال بالا درسته و کانفیگ توسط اسکریپت درست شده پس باید درست کار کنه چون عملا شم داری نتیجه درست رو میگیری
و کانکشن وی پی انت درسته حالا چه با کانفیگ پیشفرض اسکریپ باشه چه با کانفیگ خودتون

**Comment by NimaZare** [comment]
درود . منم از صبح هرکاری کردم خروجی نداد. همیشه از bash استفاده میکردم و بهترین خروجی رو داشتم اما از صبح قطع شده.  چون اسپید تست کلاد کاملا فیلتر شده و آیپی 10.10.34.36 بر میگردونه.  نمیشه از جای دیگه تست اسپید بگیرید ؟
![image](https://github.com/MortezaBashsiz/CFScanner/assets/12428325/e8ecfa6c-0c18-4b69-b9d6-98077ae14bc7)

**Comment by NimaZare** [comment]
![image](https://github.com/MortezaBashsiz/CFScanner/assets/12428325/e5b30683-24ff-490d-9691-56947935eb02)

برای من این خروجی داشت  و یدونه آی پی هم پیدا کرد با این دستور
bash cfScanner2.sh -c /root/scan/myconfig.json -v YES -m SUBNET -t UP -p 3 -s 100 -n 2 -u 2

**Comment by NimaZare** [comment]
ممنون از زحمتتون 🌹

**Comment by MortezaBashsiz** [comment]
این ایشو رو میبندم
به نظرم فانکشنالیتی اسکریپت مشکلی نداره

**Comment by Jolge100** [comment]
برای من اقا مرتضی حتی به دونه هم پیدا نکردا
چطوری اخه با ایپی های اسکن قبلی داره با سرعت کار می کنه  ولی همونا رو نشون نمی ده
سرورم هم اختصاصی هستش
چطور می تونم بفهمم رو وب ساکت اختلال هست ؟

**Comment by MortezaBashsiz** [comment]
> برای من اقا مرتضی حتی به دونه هم پیدا نکردا چطوری اخه با ایپی های اسکن قبلی داره با سرعت کار می کنه ولی همونا رو نشون نمی ده سرورم هم اختصاصی هستش چطور می تونم بفهمم رو وب ساکت اختلال هست ؟ حتی سرعت 1 کیلوبایت هم به من ایپی نمی ده

ساده نیست فهمیدن اختلال
منم سعی میکنم که در آینده اگه فرصت بشه لاگ دیباگ برای اسکنر بنویسم که کمکی باشه برای فهمیدن بهتر مشکل

**Comment by Jolge100** [comment]
> > برای من اقا مرتضی حتی به دونه هم پیدا نکردا چطوری اخه با ایپی های اسکن قبلی داره با سرعت کار می کنه ولی همونا رو نشون نمی ده سرورم هم اختصاصی هستش چطور می تونم بفهمم رو وب ساکت اختلال هست ؟ حتی سرعت 1 کیلوبایت هم به من ایپی نمی ده
> 
> ساده نیست فهمیدن اختلال منم سعی میکنم که در آینده اگه فرصت بشه لاگ دیباگ برای اسکنر بنویسم که کمکی باشه برای فهمیدن بهتر مشکل سرعت رو هم هرگز روی ۱ کیلوبایت نزارید چون اصلا واقعی نیست سعی کنید همون ۱۰۰ بزارید

مشکل اینه که اصلا به من ایپی به عنوان نتیجه نمی ده که بخوام 1 یا 100 بذارم
همیشه روی 6000 می ذاشتم الان فقط به این دلیل که اصلا result هیچی بهم نمی ده عدد رو پایین ترین گذاشتم
20 رنج کامل رو اسکن کردم هیچی نداد
مطمینن تا امروز فردا بقیه دوستان هم سراغ این داستان میان چون الان یه مقدار اختلال رو اینترنت هستش فکر می کنن به خاطر اختلال ها هستش که ایپی نمی گیرن
ممنون

**Comment by randomguy-on-internet** [comment]
یک مشکل عجیبی که من توی اسکنر ویندوز بهش برخوردم اینه که اگه مثلا فقط اسکنر بزاری روی تست دانلود و سرعت دانلود رو بزاری مثلا روی 100 و سرعت آپلود روی 10 باشه با اینکه تست اپلود غیر فعاله، ای پی پیدا نمیکنه حالا همون رنج رو دوباره با همین تنظیمات و اپلود 50 بزاری شروع میکنه پیدا کردن! نمیدونم این سرعتا چجوری به هم لینک شدن با اینکه فقط تست دانلود رو فعال کردم.
خلاصش اینه که توی تست دانلود برای شما ممکنه روی یک رنج آی پی تمیز هیچ ایپی پیدا نکنه حالا اگر سرعت آپلود رو تغییر بدیم و دوباره همون رنج رو اسکن کنیم پیدا میکنه.
طبق تجربه تست دانلود با سرعت دانلود 200/500 با سرعت اپلود 50 مچ هست.
