### ISSUE TITLE
پیدا نکردن آیپی نسخه ویندوزی

### ISSUE THREAD

**Issue by amin0200** [MortezaBashsiz/CFScanner#541]
سلام دوستان عزیزم امروز هر آی پی رنجی رو که بقیه اسکن میکنن تو شهر خودم اوکیه برا من اصلا اون رنجو اسکن میزنم پیدا نمیکنه چیزی . 
امروز نسخه ویندوزی مشکل خورده .

**Comment by TheErf23** [comment]
بله درسته همه نسخه ها تو یک سری مناطق به مشکل خورده...

**Comment by PERSIA-MISI** [comment]
خیلی وقته مشکل داره حداقل یکماه هست که همشون تقریبا توی شهر من بلا استفاده شدن آی پی های تمیزی هم که بقیه میذارن هم کار نمیکنند
شب اسکن میکنی یه کم کمو بیش جواب میده تو روز دیگه کار نمیکنه تا آخر شب
گرفتاری شدیم ب خدا

**Comment by amin0200** [comment]
بنظرم این به عمد هست . شب ها آی پی ها رو باز میزارن . ماها هممونم بیشتریا شبا میزاریم رو اسکن صبح ک پا میشیم کلی آی پی درجه یک پیدا کرده همونو تو روز استفاده کنی فیلتره . اینا به عمده تا ما رو به اشتباه بندازن.
