### ISSUE TITLE
اختلال شدید در اسکنرها

### ISSUE THREAD

**Issue by TheErf23** [MortezaBashsiz/CFScanner#542]
اقا مرتضی سلام.2 روزه علی رغم اینکه همه دارن به نحوی گزارش میدن که توی اسکنر ها اختلال پیش اومده میگید مشکل نداره!اسکنر های پایتونی و ویندوزی و بش رو تست کردم روی اپراتور های مختلف اما کارساز نیست به نظر میاد یه اختلال عمدی توی اسکنر ها انداختن از دیروز... با کاستوم کانفیگ های مختلف هم تست کردم...اسکنر ها مشکلی ندارن روی سرور خارج به راحتی اسکن میکنه این یعنی یک اختلال عمدی هستش!

**Comment by erf56** [comment]
ای پی هایی که همین الان allready باهاش وصلم رو میذارم تو اسکنر خطا میده!

**Comment by erf56** [comment]
بنظرم برای متوجه شدن شرایط ما ، روی یک سرور ایران تست کنید از خارج کشور همه چی اوکیه

**Comment by TheErf23** [comment]
![Capture](https://github.com/MortezaBashsiz/CFScanner/assets/82929677/661e6c76-049c-4838-849b-c45212388c57)
![photo_2023-05-09_19-58-31](https://github.com/MortezaBashsiz/CFScanner/assets/82929677/f07abb76-6842-46db-98c3-ae68dc726cf4)

**Comment by MortezaBashsiz** [comment]
درود
بله حرف شما درسته
اختلال وجود داره و این چند روزه نمیدونم چه اتفاقی افتاده که اینطوری شده
ماهم که دیگه دستمون بستست و ابزارمون محدود هست و داریم بررسی میکنیم که چه اتفاقی افتاده و چکار میتونیم بکنیم
اسکنر ما صرفا یک ابزار اسکن هست و وقتی روی پروتوکل اختلال بندازن خوب طبیعتا اسکنر هم نمیتونه درست کار کنه
چند روزی صبر کنیم تا بتونیم یه راه حلی پیدا کنیم
سپاس

**Comment by TheErf23** [comment]
جالبه!من دارم از ایپی تمیز و همین پروتکل استفاده میکنم دقیقا!
ایپی سالمه و داره جواب میده روی همون پروتکل میذارم اسکن همون ایپی رو اسکن نمیکنه

**Comment by TheErf23** [comment]
اسکنر اقا وحید کار میکنه اما خیلی کند تقریبا میشه گفت اونم کار نمیکنه...

**Comment by TheErf23** [comment]
به نظر میرسه توی تست سرعت به مشکل میخوره

**Comment by MortezaBashsiz** [comment]
خواهش میکنم اینقدر پیام‌ها رو جدا جدا و یک خطی مثل چت ندید
سعی کنید پیام‌ها رو توی یک پیام بدید یا ادیت بکنید و قبلی ها رو اضافه بکنید

صبر کنید بررسی میکنیم ببینیم مشکل کجاست

**Comment by TheErf23** [comment]
عذرخواهی میکنم♥
ویرایش شد و منتظر جواب شما ام
ممنون بابت زحماتتون

**Comment by aboozar1368** [comment]
سلام مرتضی جان 
من از امروز صبح با ارور 
One or more errors occurred. (The SSL connection could not be established, see inner exception.)
با این ارور مواجه شدم
![Capture](https://github.com/MortezaBashsiz/CFScanner/assets/119940685/99dbeb99-1545-4739-8016-34d58707b901)

**Comment by m2tts2001** [comment]
سلام و درود و خسته نباشید
راستش دو روزه دارم تست میگیرم به نتیجه نمیرسم. اومدم ایشو جدید باز کنم دیدم دوستان باز کردند. صرفا تجربه این دو روزه رو میگم.
با اسکنر بش تست گرفتم کلا فیل میشد. حتی ip سالمی که خیلی خیلی عالی داره برام کار میکنه. کل ساب نت رو گذاشتم تو اسکن بش بازم هیچی نیافت. 
اسکنر پایتون روی لینوکس هم تقریبا همین بود. وقتی کل ساب نت رو میدادم یه چندتا ای پی میداد اما اون ای پی اصلی که سرعتش خوبه رو نه. اونایی که میداد هم خیلی ضعیف بود. سرعت دانلود و آپلود رو جدا جدا حتی تا ١ هم کم کردم برای هر دو اسکنر فایده نداشت. تعداد پروسس ها رو کم میکردم هم نشد زیاد میکردم هم نشد اما لیتینسی رو تغییر میدادم تعداد ای پی های پایتون چندتا بیشتر میشد اما بازم اون ای پی سالمه که تو ساب نت هست رو نمیداد. 
اگر برای بهتر شدن شرایط کمک دیگه یا سوال دیگه داشتید یا خواستید چیزی رو تست کنم اطلاع بدید. واقعا خوشحال میشم بتونم کمکی کنم. 
در ضمن کل تست ها روی یک سرور ایران با رم ٢ و cpu ٢ هسته بوده.

**Comment by mohamad15516** [comment]
ممنون از اقای باشمیز و دوستان من یه برسی ریزی  کردم دیدم  مثل این که دامنه
 https://speed.cloudflare.com/

فیلتر شده و یا هرچیزی چون با ایپی ایران باز نمیشه و به گمونم مشکل اسکن نشدن ایپی ها همین باشه

**Comment by Jolge100** [comment]
افا مرتضی همونطور که توی اون یکی تاپیک عرض کرده بودم کم کم بچه ها پیداشون می شه D:
به نظرم بهتره روی سرور ایران تست کنین
از طریق ایمیلتون یه سرور ایران بفرستم براتون ؟ 
دقیقا اسکنر شما این مدت اینترنت رو نگه داشته و نبودش قشنگ تازه فیلترینگ رو به شدت تاثیر گذارکرده

**Comment by aminhyper** [comment]
سلام 
این دستور رو زدم
python3 -m pip install --upgrade cfscanner 
نسخه ی جدید:

Successfully installed cfscanner-1.3.16

بعد این دستور رو زدم:
python3 -m cfscanner -t 8 -r 20 --shufle-subnets --no-fronting

نتیجه:

__main__.py: error: unrecognized arguments: --shufle-subnets --no-fronting

**Comment by tempookian** [comment]
> سلام این دستور رو زدم python3 -m pip install --upgrade cfscanner نسخه ی جدید:
> 
> Successfully installed cfscanner-1.3.16
> 
> بعد این دستور رو زدم: python3 -m cfscanner -t 8 -r 20 --shufle-subnets --no-fronting
> 
> نتیجه:
> 
> **main**.py: error: unrecognized arguments: --shufle-subnets --no-fronting

ببخشید یه f کم گذاشته بودم:
‍‍‍
```bash
python3 -m cfscanner -t 8 -r 20 --shuffle-subnets --no-fronting
```

**Comment by Jolge100** [comment]
به من این ارور رو می ده 

__main__.py: error: unrecognized arguments: --no-fronting

**Comment by tempookian** [comment]
> به من این ارور رو می ده
> 
> **main**.py: error: unrecognized arguments: --no-fronting

اول اجرا چه ورژنی می‌زنه؟ 
1.3.16
باید باشه. اگر نیست یعنی درست آپگرید نکردید:
```bash
pip install --upgrade cfscanner
```

**Comment by Jolge100** [comment]
![image](https://github.com/MortezaBashsiz/CFScanner/assets/118624183/8cc82c63-1e73-4af9-a66a-6c152645d83c)
خدمت شما

**Comment by m2tts2001** [comment]
با تشکر از زحمات شما
تست کردم و نتیجه گرفتم. خیلی بهتر بود اسکن ها.

**Comment by tempookian** [comment]
> ![image](https://user-images.githubusercontent.com/118624183/237349351-8cc82c63-1e73-4af9-a66a-6c152645d83c.png) خدمت شما
> 
> پی نوشت : دوباره اپدیت زدم و می گه نسخه اخر موجوده

خیلی عجیبه. من رو ویندوز و اوبونتو و مک‌اواس تست کردم الآن اوکی بود. 

‍‍‍```bash
pip install --force-reinstall cfscanner
```

کنید یه بار امیدوارم مشکل رو حل کنه.

**Comment by Jolge100** [comment]
بله الان درست شده و دارم اسکن می زنم
واقعا ممنونم ازتون امیدوارم جواب بگیرم

**Comment by Jolge100** [comment]
بله الان بهم ایپی می ده و دیگه مطمینن می شه گفت اختلال روی وب سوکت انداخته شده و سرعت به شدت افت کرده
اما اسکنر الان درست کار می کنه 
ممنونم ازتون

**Comment by m2tts2001** [comment]
در نسخه ١٧ پایتون بدون no fronting چیزی پیدا نشد
اما اگر no fronting رو میذاشتم پیدا میکرد

**Comment by tempookian** [comment]
سپاس از اطلاع‌رسانی. لطفا با ۱.۳.۱۸ امتحان کنید. مشکلی بود که برطرف شد. امیدوارم کار کنه. ایشوی #551 رو دنبال کنید لطفا
