### ISSUE TITLE
cfscanner: error:  --shufle-subnets

### ISSUE THREAD

**Issue by prxpostern** [MortezaBashsiz/CFScanner#545]
سلام

cfscanner: error: unrecognized arguments: --shufle-subnets

این ارگومان خطا میده.

**Comment by Jolge100** [comment]
> سلام
> 
> cfscanner: error: unrecognized arguments: --shufle-subnets
> 
> این ارگومان خطا میده.
اینو وارد کنین

cfscanner: error: unrecognized arguments: --shuffle-subnets
