### ISSUE TITLE
fronting timeout

### ISSUE THREAD

**Issue by alefra1181** [MortezaBashsiz/CFScanner#552]
درود آقا مرتضی
با اجرا نسخه ۱.۳.۱۷ این ارور میاد
گویا رفع نشده
حداقل واس من
 روی نت همراه اول و مخابرات یه رنج آی پی میشناسم ک مطمئنا اکثرشون تمیزن
ولی همه رو fronting timeout میده
ممنون بابت تلاشتون♥️

**Comment by tempookian** [comment]
سپاس از اطلاع‌رسانی. لطفا از ایشوی #551 موضوع رو دنبال کنید. تشکر

**Comment by alefra1181** [comment]
> سپاس از اطلاع‌رسانی. لطفا از ایشوی #551 موضوع رو دنبال کنید. تشکر
حل شد ♥️
