### ISSUE TITLE
مشکل در وارد کردن کانفیگ شخصی

### ISSUE THREAD

**Issue by ghermez** [MortezaBashsiz/CFScanner#555]
سلام
خدا قوت

من کانفیگ خودم رو به نسخه ویندوز اضافه کردم و موقع تست این پیغام ها رو میگیرم:

`Start diagnosing for 203.17.126.126 at 5/11/2023 2:21:59 PM...
Starting scan engine with target speed: 100,000, dl timeout: 2, config: 'my.json' => {
  "policy": {
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "log": {
    "access": "",...

------------ Start IP Check ------------
IP: 203.17.126.126

----- Fronting Test -----
Start fronting check, timeout: 1, Resolver IP: 203.17.126.126, withCustumDNSResolver: True
Fronting check with url: https://speed.cloudflare.com/__down?bytes=100
Fronting check done in 525 ms, content: '00000000000000000000000000000000000000000000000000'

----- Running v2ray.exe -----
Starting v2ray.exe with arg: run -config="v2ray-config/generated/config.203.17.126.126.json"
v2ray.exe executed success: False
v2ray.exe Error: Failed to start: main/commands: failed to load config: [v2ray-config/generated/config.203.17.126.126.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: geosite:category-ads-all > infra/conf/rule: failed to load geosite: category-ads-all > infra/conf/geodata/standard: failed to open file: geosite.dat > open C:\Users\yyyy\Downloads\v1.2.8530.30281-Windows-x64\geosite.dat: The system cannot find the file specified.

Fronting  Result:    SUCCESS
v2ray.exe Execution: FAILED
Download  Result:    FAILED
Upload    Result:    FAILED

------------ End IP Check ------------
`

به نظرتون کجای کار من ایراد داره؟

**Comment by goingfine** [comment]
توی کانفیگتون یسری پارامترای اضافی هست که باید پاک کنید 
مثل geosite
