### ISSUE TITLE
Windows scanner will close immediately after opening

### ISSUE THREAD

**Issue by AghaFarokh** [MortezaBashsiz/CFScanner#556]
Hi
first of all thanks for your great job
I'm on windows 11 and when open the .exe file it will close immediately after opening

**Comment by goingfine** [comment]
یکم اطلاعات بیشتر بدید 
ایا فقط با نسخه جدید مشکل دارید و قبلیا کار میکنن
اگر فایل لاگ توی مسیر برنامه ایجاد میشه اون رو هم بزارید تا بررسی کنیم
توی برنامه  event viewer‌ ویندوز ببنید بعد از اجرای برنامه لاگی میوفته
