### ISSUE TITLE
مشکل اسکن 

### ISSUE THREAD

**Issue by sirvan1133** [MortezaBashsiz/CFScanner#561]
سلام و درود ، بنده در نسخه ی ویندوز  با یه ایپی تمیز که همین الان دارم باهاش کار میکنم با کانفیگ شخصی تست میکنم میگه کار نمیکنه !
نسخه ی اندروید هم کلا اولاش پیدا میکرد الان یدونه هم پیدا نمیکنه !
کانفیگ شخصی هم میدم

**Comment by goingfine** [comment]
تو ویندوز تایم اوت رو بزارید رو عدد بالاتر
ضمنا تست دیاگنوس رو انجام بدید
