### ISSUE TITLE
درخواست اضافه شدن دسته بندی از نوع زمانی

### ISSUE THREAD

**Issue by mohsen-armoun** [MortezaBashsiz/CFScanner#564]
سلام و خسته نباشید به مرتضی عزیز و باقی دوستان که تو این پروژه و پروژه های دیگه دارن باری از دوش فیلترینگ کشور ورمیدارن

اگه امکانش هست میخواستم درخواست کنم، تو بخش results اسکن یه فیلتر زمان هم اضافه کنین که براساس زمان اسکن و پیدا شدن ip هم دسته بندی کنه
البته اگه دردسرش کمه براتون

ممنون
نسخه استفاده شده : ویندوز

**Comment by goingfine** [comment]
متوجه منظورتون نشدم

نتایج همین الانم بر اساس تاریخ ذخیره و مرتب میشن
