### ISSUE TITLE
پیدا نکردن حتی یک آی پی

### ISSUE THREAD

**Issue by SalarAbapour** [MortezaBashsiz/CFScanner#565]
1 => One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:3481))
1 => One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:3494))
1 => One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:3418))
1 => One or more errors occurred. (No connection could be made because the target machine actively refused it. (127.0.0.1:3526))
من سه روزه تلاش می کنم اما نمی تونم حتی یک آ یپی پیدا کنم. خطاهایی که هم میده اینان. ممن.ن میشم راهنمایی بفرماینن

**Comment by goingfine** [comment]
این رنج چطوره؟ 203.32.120.1

**Comment by goingfine** [comment]
بله اسکنر داره کار میکنه برای خیلی های دیگه
شما باید دیگانوست رو بزاری ببینیم
این مشکل هم ربطی به فایروال نداره و اینکه اقای باشسیز هم اصلا ویندوز کار نیست ;)

**Comment by SalarAbapour** [comment]
با رنجی که فرمودین هم نتونست پیدا کنه.

**Comment by SalarAbapour** [comment]
با رنج ip گروه ircf گذاشتم دوباره پیدا کنه. 
تنظیمات:
only Upload
Skip after 10%
Target Speed: 100 , 50
Random
فقط بفرمایین دیگانوست رو چجوری دربیارم و کجاست :)

**Comment by mahyar777** [comment]
سلام من تمام مراحل درست رفتم وقتی میخوام استارت کنم حتی یدونه ای پی پیدا نمیکنه و این ارور رو میده 

Top Fronting Errors:

**Comment by asefsoft** [comment]
> با رنج ip گروه ircf گذاشتم دوباره پیدا کنه. تنظیمات: only Upload Skip after 10% Target Speed: 100 , 50 Random فقط بفرمایین دیگانوست رو چجوری دربیارم و کجاست :)

https://github.com/MortezaBashsiz/CFScanner/discussions/331

**Comment by goingfine** [comment]
> با رنج ip گروه ircf گذاشتم دوباره پیدا کنه. تنظیمات: only Upload Skip after 10% Target Speed: 100 , 50 Random فقط بفرمایین دیگانوست رو چجوری دربیارم و کجاست :)

نحوه دیاگنوس: https://github.com/MortezaBashsiz/CFScanner/discussions/331
