### ISSUE TITLE
تایمر استارت اتوماتیک برای نت شبانه

### ISSUE THREAD

**Issue by AliMilani** [MortezaBashsiz/CFScanner#566]
قابلیت شروع و اتمام اسکن اتوماتیک برای استفاده از نت شبانه
برای اسکن میتونه کمک کنه تا هزینه ها کاهش پیدا کنه.

**Comment by tempookian** [comment]
سپاس از پیشنهادتون. از چه نسخه‌ای استفاده می‌کنید؟ اگر از نسخه‌هایی که تو ترمینال ران می‌شن (بش، پایتون، گولنگ) استفاده می‌کنید، می‌تونید خیلی راحت تنظیم کنید که دستور مورد نظرتون کی ران بشه و کی استاپ بشه (بسته به سیستم عاملتون متفاوته). همچین فیچری به نظرم توی تمرکز و هدف اصلی اسکنر نیست
