### ISSUE TITLE
قابلیت استفاده اپلود خودکار ای پی ها روی دامنه کلود فلر

### ISSUE THREAD

**Issue by sh-vp** [MortezaBashsiz/CFScanner#567]
سلام وقتتون بخیر
من از طرف خودم و دوستانی که داریم با کمک زحمات شما از امکانات دسترسی به اینترنت آزاد استفاده میکنیم کمال تشکر رو دارم

بنده یک پیشنهاد برای اضافه شدن قابلیت قرار گرفتن ای پی های پیدا شده در اسکنر پایتون به صورت خودکار روی دامنه مشخص به صورت a رکورد رو داشتم
چون من با خیلی از دویتان که صحبت میکردم مشکلی که اکثرا داریم این هست که چون ممکنه این کانفیگ ها رو برای چند نفر نصب کنیم و خیلی سخت میشه که مثلا به کسانی که دانش استفاده از این نرم افزار ها رو ندارن بگیم که ای پی ادرس کانفیگشون رو عوض کنن از این جهت خود من اومدم یک ساب دامنه ایجاد کردم که این ای پی ها رو به صورت دستی روی اون قرار میدم
در چند روز اخیر که فیلترین ای پی ها شدید تر شده اسکن کردن و قرار دادن دستی ای پی ها  پشت ساب دامنه خیلی سخت تر شده اگر امکان داره و فرصتش رو دارید ممنون میشن این قابلیت رو به نسخه پایتون اضافه کنید 

و یک موضوع هم این که اخیرا همه ما داریم مدام پشت سر هم اسکن رو انجام میدیم چون اکثر ای پی ها کمتر از یک ساعت فعال هستند اگر قابلیت لوپ روی اسکنر پایتون بود که میشد بعد از انجام اسکن با گذشت زمان مشخصی مجدد اسکن میکرد و نتایج رو روی دامنه اپدیت میکرد بسیار عالی میشد 

ببخشید که مطلب طولانی شد 

مجددا از همه زحمات شما سپاسگزارم

@tempookian 
@MortezaBashsiz

**Comment by tempookian** [comment]
سلام. ممنون از محبت و پیشنهادتون. منتها موضوعی که هست اینه که به نظرم بهتره ابزارها رو متمرکز روی هدفشون نگه داریم. ابزاری که شما می‌فرمایید بایستی مجزا تهیه بشه و نتیجه اسکن رو بگیره و نهایتا رکوردها رو ثبت کنه. 

مورد دوم رو لطفا بیشتر و دقیق‌تر توضیح بدید که ببینم قابلیت پیاده‌سازی داره یا نه.

**Comment by sh-vp** [comment]
بله حتما 
اول سپاس از پاسخگویی شما

از این جهت که دائم ای پی ها در حال فیلتر شدن هستند اگر امکانش بود پارامتری تعریف میشد که پس از اتمام اسکن بعد از گذشت زمان مشخصی مجددا اسکن رو اجرا میکرد حالا اگر این مورد قابلیت اتصال به api کلود فلر رو هم داشت دیگه عملا هیچ کانفیگی قطع نمیشد چون دائم اسکنر داشت ای پی تمیز روی دامنه یا سابدامنه جایگذاری میکرد  البته اگر فقط بخش اجرای مجدد اسکریپت هم روی اسکنر اضافه بشه باز هم خیلی خوب میشه چا که میتونیم هر زمان یک ای پی قطع شد سریع از روی اسکنر اخرین ای پی سالم رو برداریم و استفاده کنیم

پیشنهاد اول من به این جهت بود که حالا عده ای کار فروش دارن و بحث جدایی داره عده ای هم این سرویس ها رو برای دویتان و نزدیکانی که سن زیادی دارن یا اشنایی با تکنولوژی ندارند نصب کردند که بتونن استفاده روزمره داشته باشند الان خیلی این مورد سخت شده که مثلا به یک فرد 60 ساله بخواهیم توضیح بدیم که ای پی چی هست و چطور ای پی رو که به دستشون رسوندیم باید در کانفیگ جایگزاری کنن 

حالا این در مورد همه جمعیت میانسال کشور تقریبا صدق میکنه اکثر پدر مادر ها این مشکل رو دارند و خیلی سخت شده تعویض ای پی برای این افراد

ببخشید که مطلب طولانی شد 
سپاس و تشکر 
@tempookian
