### ISSUE TITLE
اضافه شدن اپشنی برای سورت کردن

### ISSUE THREAD

**Issue by mohammadRezaeian** [MortezaBashsiz/CFScanner#568]
سلام و ممنونم از تمام زحمات تون
میخواستم خواهش کنم اپشنی اضافه کنید که در زمان اتمام کار یک فایل دیگه ایجاد کنه و بهترین ای پی ها رو از اول به اخر سورت کنه
و بازهم تشکر از تمام زحمات تون.

**Comment by tempookian** [comment]
با چه نسخه‌ای کار می‌کنید

**Comment by mohammadRezaeian** [comment]
نسخه اخر 1.3.19

**Comment by tempookian** [comment]
سپاس از پیشنهادتون. ممکنه برای کاربرهای مختلف اولویت توابع هدف متفاوت باشه. برای یکی لیتنسی مهمه برای یکی سرعت آپلود و ... . بنابراین بعد از اسکن، یا با دستور sort در لینوکس یا با استفاده از ابزاری مثل excel، فایل csv رو بر اساس معیار مورد نظرتون مرتب کنید
