### ISSUE TITLE
استفاده از چند آی پی روی یک دامنه

### ISSUE THREAD

**Issue by dadashali61** [MortezaBashsiz/CFScanner#57]
فایده این که چند آی پی رو ست کنیم روی دامنه چی هست؟ چیزی که من متوجه شدم این هست که این آی پی ها به صورت لود بالانسر عمل می کنن اما به فرض اگر یکی از این آی پی ها بلاک بشه، چه اتفاقی برای اون کاربر میافته؟ طبیعتا نمی تونه وصل بشه در اون لحظه، درسته؟ راهکاری براش هست؟

**Comment by NadiaGarcia6** [comment]
You should create A record for each IP address and do not point one A record to multiple IP addresses.

For example:

server1.yourdomain.com => 1.1.1.1
server2.yourdomain.com => 1.1.1.2
server3.yourdomain.com => 1.1.1.3
server4.yourdomain.com => 1.1.1.4

Then give your domain addresses to your clients ...

**Comment by dadashali61** [comment]
It seems there was a misunderstanding with the translator. 
Here is my question:
What's the point of using several IPs on the same domain? I just found that if I set several IPs for one domain it will work as a load balancer but there is a matter. If one of that IPs does not work so what will happen to access that domain? I think the client could not connect to the domain! Is there any resolvent?
