### ISSUE TITLE
اسکنر ویندوزی 

### ISSUE THREAD

**Issue by karimzzzm** [MortezaBashsiz/CFScanner#570]
پیشنهادی دارم با توجه به زحمت و تلاشی که شما دارین انجام می دید زیاده خواهش شاید به حساب بیاد 

یه قابلیت باشه برای سریع تر شده اسکن رنج های خیلی بزرگ برای پیدا کردن رنج های کوچیک تر 
برای مثال وقتی مشخص میکنی که 104.31.0.0/16 اسکن بشه مخص کنیم توی هر رنج 255 تای فقط مثلا یک ایپی پیدا کنه یا چندتا 
و دیگه باقی رنج رو نگرده اینجوری میتونیم خیل سریع تر توی رنج های خیلی بزرگ بگردیم و بعد تمو شدن اسکن میریم رنج های 255 تای کوچیک تر رو اسکن می کنیم اینجوری وابسطی به کانال ها و هجوم روی یه ایپی یا یه رنج خیلی کمتر میشه نه سمت فیلتر چی حجم بالا میره که لیمیت کنه ایپی رو نه سمت کلودفلر 

بازم خیلی خیلی خیلی ممنونم از زحماتی که می کشید 
امیدوارم این قابلیت اضافه بشه تا توی زمان صرفه جوی بشه

**Comment by goingfine** [comment]
![image](https://github.com/MortezaBashsiz/CFScanner/assets/126115050/508c245c-662e-4970-8434-141fc4ac8ff2)

گزینه skip موجوده و میتونه بهتون کمک کنه

**Comment by goingfine** [comment]
برای حالت های کاستومایز میتونید خودتون سورس برنامه رو رو ویرایش و بعد کامپایل کنید
