### ISSUE TITLE
عدم اتصال به اینترنت اپ اندروید

### ISSUE THREAD

**Issue by 10rino** [MortezaBashsiz/CFScanner#576]
سلام نسخه 1.0.8 اندروید فکر کنم مشکل اتصال به اینترنت داره
چون به جای دکمه استارت مینویسه waiting for network

**Comment by yunesxinus** [comment]
سلام من با اینترنت ایرانسل این مشکل رو داشتم
به تنظیمات APN رفتم پروکسی و پورت هرچیزی داهلش بود رو پاک کردم و بعد درست شد
