### ISSUE TITLE
استفاده برای VLESS

### ISSUE THREAD

**Issue by dadashali61** [MortezaBashsiz/CFScanner#58]
امکانش هست این برنامه برای دیگر پروتکل ها مخصوصا VLESS بشه تنظیمش کرد؟ چون الان بعضی IP ها کار می کنن برای VLESS ولی اکثرا کار نمی کنن و پیدا کردنشونم از بین این همه IP کار بسیار سختی هست.

**Comment by NadiaGarcia6** [comment]
When an IP works with VMESS, it definitely works with other protocols like VLESS and Trojan ...   bear in mind that you should use WebSocket protocol

**Comment by dadashali61** [comment]
I see. But how about the gRPC protocol? I just found that some IPs work but most of them do not!
