### ISSUE TITLE
(Android)استفاده از ایپی های اسکن شده قبلی برای اسکن دوباره به جای ایپی رنج

### ISSUE THREAD

**Issue by kamiepic** [MortezaBashsiz/CFScanner#580]
سلام خیلی ممنون بابت اپ اندرویدی
اگ ممکنه قابلیت اضافه کردن ایپی لیست (ipv4)و سرچ بر اساس ایپی لیست(ipv4) خودمو داشته باشیم تا ایپی رنج [CIDR]
الان توی بخش Cidr manager ما میتونیم فقط آیپی رنج قرار بدیم مثل25.25.25.0/24  یا هرچی دیگه که رنج باشه
ولی اگه یه قابلیتی بیاد که بشه از ipv4 استفاده بشه مثلا 25.25.25.25 و45.45.45.25و...  خیلییی عالی تر میشه
مثلا 100تا ایپی ipv4بدیم فقط اونارو اسکن کنه
این قابلیت در تمامی ورژن ها جز اندروید هستش و حیفه که اضافه نشه 
ممنون

**Comment by 0ut0fCode** [comment]
با تشکر از پیشنهاد مطرح شده ، در لیست فیچر های درخواستی ورژن بعد قرار گرفت.
