### ISSUE TITLE
CIDRS fetching failed on Android version

### ISSUE THREAD

**Issue by MahdiAmini-edu** [MortezaBashsiz/CFScanner#596]
Today, I've encountered this problem in the Android version. I've tested it on two different ISPs but nothing happens.

**Comment by EmperorofWeb** [comment]
همینطوره
همچنین در بخش CIDRs لیست آی پی ها نمایش داده نمیشه و حتی لیست کاستوم آی پی ها هم در دسترس نیست و امکان اضافه کردن آی پی جدید وجود نداره
با حذف و نصب مجدد هم تغییری حاصل نمیشه

**Comment by arashsr68** [comment]
سلام وقت بخیر منم با دوستمون موافقم از چند نفر هم پرسیدم همین مشکل رو داشتن امکان اضافه کردن آی پی جدید وجود نداره لطفا این مشکل رو حل بفرمایید متشکرم

**Comment by HamidOffline** [comment]
منم دقیقا این مشکل رو دارم لطفاً رفع باگ کنید ممنون خیلی نیاز دارم بهش واقعا عالیه

**Comment by s-alireza** [comment]
منم این مشکل پیش اومده برام

**Comment by xc0000e9** [comment]
اول ارو fronting بود که با تعویض آدرس مشکل برطرف شد اما در حال حاظر نه لیست ای پی ها به صورت پیش فرض میاد و نه ای پی کاستوم میشه وارد کرد

**Comment by HamidOffline** [comment]
مرتضی جان لطفاً پاسخ چشم انتظارا رو بدید ممنون

**Comment by 0ut0fCode** [comment]
سلام ، تشکر بابت گزارش خطا 

مشکل در ورژن 1.0.9 رفع شد و اپدیت در اختیار کاربر ها قرار گرفت .
