### ISSUE TITLE
Fronting not working

### ISSUE THREAD

**Issue by mahanmi** [MortezaBashsiz/CFScanner#597]
The Fronting doesn't work for me I think that Its domain is filtered (My operator is MCI)

**Comment by tempookian** [comment]
Hi. Thanks for the report. Which version are you using? Bash? Windows? Python? ...

**Comment by mahanmi** [comment]
> Hi. Thanks for the report. Which version are you using? Bash? Windows? Python? ...

Windows

**Comment by mahanmi** [comment]
I Discovered Government has blocked the Cloudflare speed test subdomain  
![image](https://github.com/MortezaBashsiz/CFScanner/assets/101924479/108e3c12-9f82-4d5d-857f-f474dab5dca4)

**Comment by tempookian** [comment]
All versions are equipped with a feature to skip the fronting test. I recommend checking the telegram channel. Try searching for `no-fronting` there:

https://t.me/Sudoer_GRP/785

**Comment by hamidamadani** [comment]
Thanks. What is the downside with not using Fronting?

**Comment by mahanmi** [comment]
Yes I can do that but, I really prefer to use fronting

**Comment by tempookian** [comment]
The fronting method is a bit different in Python which might work even when the fronting domain is blocked. You can try that.

**Comment by tempookian** [comment]
> Thanks @tempookian. What is the downside with not using Fronting, specifically in the Windows app?

using fronting speeds up the whole process since fronting is faster than download/upload test in general.

**Comment by mahanmi** [comment]
> The fronting method is a bit different in Python which might work even when the fronting domain is blocked. You can try that.

isn't any way to fix it in Windows?
