### ISSUE TITLE
روی همراه اول ارتباط با دامنه speed.cloudflare.com مشکل داره.

### ISSUE THREAD

**Issue by Amirreza-al** [MortezaBashsiz/CFScanner#598]
زمان انجام اسکن fronting ارور روی 100 درصد ولی با vpn روشن ارور به 0 میرسه.

**Comment by tempookian** [comment]
سلام لطفا بفرمایید از کدام نسخه استفاده می‌کنید. بش؟ ویندوز؟ ...

**Comment by Amirreza-al** [comment]
سلام. از نسخه ویندوز  Sent from Mail for Windows From: tempookianSent: Friday, July 14, 2023 1:10 AMTo: MortezaBashsiz/CFScannerCc: Amirreza-al; AuthorSubject: Re: [MortezaBashsiz/CFScanner] روی همراه اول ارتباط با دامنه speed.cloudflare.com مشکل داره. (Issue #598) سلام لطفا بفرمایید از کدام نسخه استفاده می‌کنید. بش؟ ویندوز؟ ...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by tempookian** [comment]
می‌تونید مرحله تست فرانتینگ رو از فرایند اسکن حذف کنید. لطفا مطالب حوالی این پست رو بخونید:
https://t.me/Sudoer_GRP/785

**Comment by Amirreza-al** [comment]
خیلی ممنونم ازتون. مشکلم حل شد با این کار Sent from Mail for Windows From: tempookianSent: Saturday, July 15, 2023 9:16 AMTo: MortezaBashsiz/CFScannerCc: Amirreza-al; AuthorSubject: Re: [MortezaBashsiz/CFScanner] روی همراه اول ارتباط با دامنه speed.cloudflare.com مشکل داره. (Issue #598) می‌تونید مرحله تست فرانتینگ رو از فرایند اسکن حذف کنید. لطفا مطالب حوالی این پست رو بخونید:https://t.me/Sudoer_GRP/785—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
