### ISSUE TITLE
empty file 

### ISSUE THREAD

**Issue by 123asd321dsa** [MortezaBashsiz/CFScanner#6]
سلام
وقتی اجرا میکنم اتفاق خاصی نیمافته و یه فایل خالی میسازه.

`bash -x cfFindIP.sh 16
+ set -o nounset
++ uname
+ [[ Linux == \L\i\n\u\x ]]
+ command -v parallel
+ command -v nmap
+ command -v bc
+ command -v timeout
+ threads=16
++ curl -s -XGET https://www.cloudflare.com/ips-v4
+ cloudFlareIpList=
++ date +%Y%m%d-%H%M%S
+ now=20230126-235727
+++ dirname -- cfFindIP.sh
++ cd -- .
++ pwd
+ scriptDir=/home/USER/CFScanner/scripts
+ resultDir=/home/USER/CFScanner/scripts/../result
+ resultFile=/home/USER/CFScanner/scripts/../result/20230126-235727-result.cf
+ '[' '!' -d /home/USER/CFScanner/scripts/../result ']'
+ export -f fncCheckSubnet
+ echo ''
+ sort -n -k1 -t, /home/USER/CFScanner/scripts/../result/20230126-235727-result.cf -o /home/USER/CFScanner/scripts/../result/20230126-235727-result.cf`

**Comment by MortezaBashsiz** [comment]
درود

```
[~]>$ curl -s -XGET https://www.cloudflare.com/ips-v4
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22[~]>$
```

**Comment by mohamadmirzajani** [comment]
سلام مرتضی جان 
اسکن روی isp  ایرانسل چه نت همراه و چه TDLTE  همه ی اسکن ها FAILED  هستش و نتیجه ای رو ذخیره نمی کنه راه حلی دارید مهندس بابت این موضوع ؟

**Comment by MortezaBashsiz** [comment]
> 

نه متاسفانه راه حلی براش نیست
شاید روزهای دیگه بهتر بشه
ایرانسل خیلی اختلال داره مثل اینکه

**Comment by MortezaBashsiz** [comment]
> > درود من که میزنم باز میشه لطفا خروجی دستور رو و ورژن کرلتون رو بهم میدید؟
> 
> خروجی خالی هست. `curl 7.81.0 `
> 
> من فعلا برای حل مشکل ب جای ادرس `https://www.cloudflare.com/ips-v4` از ادرس `http://bot.sudoer.net/result.cf` در خط 41 استفاده کردم و جواب گرفتم.
> 
> شاید بتونید یه حالتی بذارید که سوال کنه از کدام ادرس برای گرفتن لیست ای پی ها اقدام کنه. ممنون بخاطر کار عالیتون

مرسی
عجیبه که شما نمیتونید بگیرید چون خیلیا دارن استفاده میکنن
