### ISSUE TITLE
سلام وقت بخير زمان اسكن اين اررور نمايش داده مي شود

### ISSUE THREAD

**Issue by hatinati2** [MortezaBashsiz/CFScanner#615]
سلام وقت بخير زمان اسكن اين اررور نمايش داده مي شود

Top Fronting Errors: (562)
435 => One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
126 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)

**Comment by hatinati2** [comment]
Top Fronting Errors: (269)
255 => One or more errors occurred. (The SSL connection could not be established, see inner exception.)
10 => One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
2 => One or more errors occurred. (Response status code does not indicate success: 404 ().)
1 => One or more errors occurred. (An error occurred while sending the request.)

**Comment by tempookian** [comment]
مشکل بایستی برطرف ضده باشه لطفا دوباره تلاش کنید و اگر درست نشده بود اطلاع بدید
