### ISSUE TITLE
مشکل اسکن در نسخه پایتون بعد از اپدیت

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#621]
**Describe the bug**
بعد از اینکه نسخه پایتون رو امروز اپدیت کردم برای ابونتو وقتی اسکن می زنم این ارور رو می ده

NO 192.133.11.0    fronting Unknown error
NO 192.133.11.1    fronting Unknown error
NO 192.133.11.2    fronting Unknown error
NO 192.133.11.3    fronting Unknown error
NO 192.133.11.4    fronting Unknown error
NO 192.133.11.5    fronting Unknown error
NO 192.133.11.6    fronting Unknown error
NO 192.133.11.7    fronting Unknown error
NO 192.133.11.8    fronting Unknown error
NO 192.133.11.9    fronting Unknown error
NO 192.133.11.10   fronting Unknown error

بعد از اینکه دستور --no-fronting رو اضافه می کنم تمام ایپی ها رو download error می ده 

NO 192.133.11.5    download error
NO 192.133.11.6    download error
NO 192.133.11.7    download error
NO 192.133.11.8    download error
NO 192.133.11.9    download error
NO 192.133.11.10   download error
NO 192.133.11.11   download error
NO 192.133.11.12   download error
NO 192.133.11.13   download error

در حالی که روی سرور دیگم که هنوز اپدیت نکردم همین ایپی ها از همین دیتاسنتر سالمه
ممنون می شم راهنمایی کنید مشکل کجاست یا چطور می تونم همون نسخه قدیمم رو دوباره روی همین سرور کپی کنم
روی حالت NOVPN کار می کنه ولی در حالت نرمال چه با کانفیگ خودم و چه کانفیگ پیش فرض ارور بالا رو می ده

**Comment by Jolge100** [comment]
کسی این مشکل رو نداره ؟

**Comment by tempookian** [comment]
سلام. سپاس از اطلاع‌رسانی. مشکل رفع شد. لطفا دوباره امتحان کنید
