### ISSUE TITLE
--template flag in python script produce strange results

### ISSUE THREAD

**Issue by just1random** [MortezaBashsiz/CFScanner#625]
The Python script isn't functioning as expected with the `--template` flag. Despite having a `1.json` file with specific content, the script seems to disregard my settings. I executed the script using `python3 -m cfscanner --threads 5 --tries 1 --sample 2 --shuffle-subnet --template "./1.json"`. Surprisingly, it still produced results, even though I was running it in an unrestricted location and knew the configuration file was wrong. To test further, I replaced the file's content with a random non-JSON string, yet the script operated successfully and returned results. This leaves me uncertain whether I'm misusing the template option or if the script defaults to a standard configuration in case of errors.

My initial `1.json` file:
```
{
  "inbounds": [
    {
      "port": "1337",
      "listen": "127.0.0.1",
      "tag": "socks-inbound",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": false,
        "ip": "127.0.0.1"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "redacted.redacted",
            "port": 8443,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "000000-0000-0000-xxxx-xxx",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "redacted.redacted"
        },
        "wsSettings": {
          "headers": {
            "Host": ""
          },
          "path": ""
        }
      },
      "tag": "proxy"
    }
  ],
  "other": {}
}
```

This file is clearly incorrect, but if you copy the exact content, save it as a JSON file, and use it with the `--template` flag, it will still produce results in unrestricted networks. How is this possible?

**Comment by tempookian** [comment]
Hi,

The script doesn't validate your template structure. If the structure is incorrect, preventing the xray service from starting, an error will occur. Otherwise, a "Fronting Error" will be displayed. For an example of a correct template structure, refer to the example below.

Note: The script will automatically substitute `"PORTPORT"` and `"IP.IP.IP.IP"` with the appropriate values.

```json
{
  "inbounds": [
    {
      "port": PORTPORT,
      "listen": "127.0.0.1",
      "tag": "socks-inbound",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": false,
        "ip": "127.0.0.1"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "IP.IP.IP.IP",
            "port": 443,
            "users": [
              {
                "id": "201b62c5-0f84-5e61-a220-4911c0c221b4"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "headers": {
            "Host": "api01.morteza.beauty"
          },
          "path": "/api01"
        },
        "tlsSettings": {
          "serverName": "whateverrandomsni.morteza.beauty",
          "allowInsecure": false
        }
      }
    }
  ],
  "other": {}
}
```

**Comment by just1random** [comment]
Thanks for answering. It would be better if script provides a warning regarding fallback to default config.
