### ISSUE TITLE
fronting timeout error

### ISSUE THREAD

**Issue by JustPooya** [MortezaBashsiz/CFScanner#629]
سلام و عرض ادب 
متاسفانه چند روزی هستش که در زمان اسکن آیپی ها با استفاده از اسکنر پایتونی روی سرور برای تمام آیپی ها فرانتینگ تایم اوت میگیرم و هیچ آیپی سالمی پیدا نمیشه
ممکنه راهنمایی کنین این مشکل به چه علت هستش و چجوری باید رفع بشه ؟
تمام مشخصات کانفیگ خودم و اس اس ال سرور رو هم چک کردم 
تشکر فراوان

**Comment by tempookian** [comment]
سلام. ممنون می‌شم اگر نسخه آزمایشی جدید رو امتحان کنید و همین‌جا بگید که مشکل مرتفع شده یا خیر:

```bash
python3 -m pip install --force-reinstall --pre cfscanner
```

**Comment by JustPooya** [comment]
متشکرم ازتون تستش کردم و مشکل برطرف شده و اسکن انجام شد

**Comment by xmohammad1** [comment]
روی نسخه پایتون چطوری میشه بدون fronting تست گرفت؟ مثل نسخه ویندوز که میشه گذاشت روی no fronting
