### ISSUE TITLE
پروژه دیگه آپدیت نمیشه؟

### ISSUE THREAD

**Issue by solidwar** [MortezaBashsiz/CFScanner#638]
سلام جناب مهندس @MortezaBashsiz  
درخواستی دارم🙏🏻 لطفا پروژه رو آپدیت کنید که این قابلیت رو داشته باشه که آیپی ورژن 6 هم اسکن کنه. و خیلی موارد دیگه برای ارتقا هست . لطفا بازم مثل چند ماه پیش روی پروژه و بهتر شدن آن وقت بزارید. 

سپاس از شما

**Comment by tempookian** [comment]
از چه نسخه‌ای استفاده می‌کنید؟ بش، ویندوز، گولنگ، ویندوز، ....
نسخه پایتون و گولنگ صددرصد پشتیبانی می‌کنند. بقیه نسخه‌ها رو نمی‌دونم

**Comment by solidwar** [comment]
> از چه نسخه‌ای استفاده می‌کنید؟ بش، ویندوز، گولنگ، ویندوز، .... نسخه پایتون و گولنگ صددرصد پشتیبانی می‌کنند. بقیه نسخه‌ها رو نمی‌دونم

Windows

**Comment by solidwar** [comment]
> از چه نسخه‌ای استفاده می‌کنید؟ بش، ویندوز، گولنگ، ویندوز، .... نسخه پایتون و گولنگ صددرصد پشتیبانی می‌کنند. بقیه نسخه‌ها رو نمی‌دونم

راهی هست بتونم با شما ارتباط بگیرم؟ ایمیل یا آیدی تلگرامی لطف کنید ممنون میشم. یا اصلا همینجا آموزشی بزارید که بتونم با گو اسکن انجام بدم(متاسفانه علم انجام اینکارو ندارم که در لحظه با خوندن ریلیز ها  بفهمم چی به چیه)

**Comment by tempookian** [comment]
گو رو مطمئن نیستم. ولی می‌تونید نسخه پایتون رو امتحان کنید. [این‌جا](https://github.com/MortezaBashsiz/CFScanner/discussions/505) آموزش مقدماتی هست و می‌تونید توی یوتوب هم برای آموزش‌های ویدیویی جست‌وجو کنید
