### ISSUE TITLE
دانلود ارور

### ISSUE THREAD

**Issue by JustPooya** [MortezaBashsiz/CFScanner#643]
با سلام و احترام
بنده چند وقتی هستش که با اسکنر پایتون ، کار اسکن رنج آیپی هارو انجام میدم
اما چند روزی هستش که بدون هیچ تغییری در هیچ چیزی فقط و فقط خطای دانلود ارور میگیرم و هیچ جواب و آیپی تمیزی داده نمیشه 
اتصال به کانکشنی ک خودم تعریف کردم هم برقرار میشه و در حقیقت اون رو به عنوان کلاینت آنلاین میشناسه
دامنه ها هم بدون مشکل هستن و پورت های مختلف رو هم تست کردم 
ممنون میشم اگر راهنمایی بفرمایید . متشکرم

**Comment by tempookian** [comment]
سلام. لطفا آپدیت کنید و احتمالا مشکل برطرف می‌شه

```bash
pip install -U cfscanner
```

**Comment by JustPooya** [comment]
نسخه آخر رو نصب کرده بودم ، مجددا آپدیت کردم اما همچنان مشکل دانلود ارور یا آپلود ارور هستش
متن کانفیگ شخصی : 
{
  "id": "8e3ad944-38af-41e1-b654-fb7fba9dbf57",
  "host": "germany.takdelman.top",
  "port": "2083",
  "path": "api120",
  "serverName": "germany.takdelman.top"
}

**Comment by JustPooya** [comment]
اسکن صرفا روی دانلود کار میکنه
اما وقتی آپلود رو اسکن میکنی یا دوتایی باهم اسکن میکنی ارور میده و اسکن انجام نمیشه

**Comment by amireeghani1991** [comment]
سلام و عرض ادب
منم امروز دقیقا همین مشکل رو داشتم
در صورتی که تا هفته ی پیش روی همون سرور با همون کانفیگ توی هر اسکن بالای 5000 تا آیپی پیدا میشد برای من 
اما امروز همش ارور میخورد

**Comment by tempookian** [comment]
> اسکن صرفا روی دانلود کار میکنه اما وقتی آپلود رو اسکن میکنی یا دوتایی باهم اسکن میکنی ارور میده و اسکن انجام نمیشه



> اسکن صرفا روی دانلود کار میکنه اما وقتی آپلود رو اسکن میکنی یا دوتایی باهم اسکن میکنی ارور میده و اسکن انجام نمیشه

بله درسته مشکل دانلود حل شده بود ولی آپلود باقی مونده بود. لطفا مجددا به‌روز کنید و ممنون می‌شم اگر این‌جا هم اطلاع بدید. سپاس

**Comment by amireeghani1991** [comment]
> > اسکن صرفا روی دانلود کار میکنه اما وقتی آپلود رو اسکن میکنی یا دوتایی باهم اسکن میکنی ارور میده و اسکن انجام نمیشه
> 
> بله درسته مشکل دانلود حل شده بود ولی آپلود باقی مونده بود. لطفا مجددا به‌روز کنید و ممنون می‌شم اگر این‌جا هم اطلاع بدید. سپاس

آقا دم شما گرم بله درست شد ❤️
