### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by xmohammad1** [MortezaBashsiz/CFScanner#646]
سلام خسته نباشید
میشه امکان اسکن دامنه هارو هم اضافه کنید منظورم اینکه بجای اینکه فقط ای پی دریافت کنه دامنه هم قبول کنه

is it possible scanner accept domains also?

**Comment by tempookian** [comment]
سلام و سپاس بابت پیشنهاد. به نظرم امکانی که اشاره کردید از اسکوپ اسکنر خارجه. با کمی جست‌وجو به ابزارهایی که لیست دامین بگیرند و آیپی برگردونن پیدا خواهید کرد.
