### ISSUE TITLE
ساپورت ipv6 روی پایتون

### ISSUE THREAD

**Issue by Jolge100** [MortezaBashsiz/CFScanner#647]
توی یه تاپیک دیدم که نوشته شده بود اسکنر پایتون از ipv6 پشتیبانی می کنه اما من هر چی تلاش کردم نتونستم آرگومانش رو پیدا کنم
ممنون می شم راهنمایی کنین

**Comment by tempookian** [comment]
> توی یه تاپیک دیدم که نوشته شده بود اسکنر پایتون از ipv6 پشتیبانی می کنه اما من هر چی تلاش کردم نتونستم آرگومانش رو پیدا کنم
> ممنون می شم راهنمایی کنین

آرگومان خاصی نداره. فقط باید آیپی‌ها و سابنت‌های مدنظرتون رو داخل یک فایل بذارید و با 
--subnets /path/to/subnet_file
آدرس رو به اسکنر بدید
