### ISSUE TITLE
عدم وصل شدن به کانفیگ

### ISSUE THREAD

**Issue by aliafshany** [MortezaBashsiz/CFScanner#69]
سلام
خیلی ممنونم از این اسکریپتی که حاضر کردید.

من روی مک با اجرای این برنامه مشکل دارم.

مشخصات کانفیگی که دادم درسته, آدرس ها فیلتر نیستند و در اون لحظه کلی نفر در حال وبگردی هستند باهاش.
پس فرض خراب بودن کانفیگ رد میشه.

تو این عکس اگر دقت کنید من اول بدون VPN اسکریپت رو اجرا کردم که نهایتا روی reading config ... موند و ایستاد, چند دقیقه ای هم صبر کردم حتا.
در مرحله بعد VPN رو روشن کردم و دوباره رانش کردم, میبینید که به کانفیگ وصل شد و اجرا شد.
در صورتی که هیچ فیلترینگی نه شامل سرور و نه دامین و نه چیز دیگه ای شده. پشت کلود فلیر هم که هست.

کانفیگ من vmess+cdn+ws+tls هست, ممکنه از اون باشه ایراد؟
ممنونم از توجهتون

<img width="788" alt="image" src="https://user-images.githubusercontent.com/40741745/218983268-3b6a4b49-9b9d-4564-98bc-878986d8f108.png">

**Comment by MortezaBashsiz** [comment]
درود
خیلی عجیبه که توی مرحله reading config میمونه
قاعدتا حتی اگه کانفیگ هم اشتباه باشه باید failed بده
امکانش هست یبار با حالت custome subnet اجراش کنید؟

**Comment by aliafshany** [comment]
با حالت کاستوم اجراش میکردم.
جالبه که با فایل کانفیگ اصلی خودتون اجرا شد 

احساس میکنم مشکل مربوط به توضیحات ویرایش فایل config.json.temp  باشه. 
در این ایشو https://github.com/MortezaBashsiz/CFScanner/issues/52#issue-1583959018

من نتونستم راستش بفهمم کدوم متغیر هارو باید تغییر بدم.


<img width="788" alt="image" src="https://user-images.githubusercontent.com/40741745/218987976-0761f222-6cec-44d9-a86b-3346f090e321.png">

**Comment by MortezaBashsiz** [comment]
پس مشکل از فایل کانفیگتون هست
میتونید نشون بدی توی فایل کانفیگت چی داری؟
با رعایت نکات امنیتی البته

**Comment by aliafshany** [comment]
اره دامین ها و id رو پنهان کردم 
این رو از v2rayng برداشتم برای همین اضافات زیاد داره


`{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      {
        "address": "fakedns",
        "domains": [
          "geosite:cn"
        ]
      },
      "1.1.1.1"
    ]
  },
  "fakedns": [
    {
      "ipPool": "198.18.0.0/15",
      "poolSize": 10000
    }
  ],
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls",
          "fakedns"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "sub.domain.com",
            "port": 2053,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "8c6",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "fingerprint": "",
          "serverName": "sub1.domain.com"
        },
        "wsSettings": {
          "headers": {
            "Host": "sub1.domain.com"
          },
          "path": "/"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "geoip:ir"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  }
}`

**Comment by aliafshany** [comment]
حل شد
- من همین کانفیگ رو مستقیم که از v2rayng گرفتم, گذاشتم تو فایل config.json.temp, بدون تغییری
- مشخصات خودمم گذاشتم داخل config.real

اجرا که کردم حل شد

دمت گرم مرسی واقعا
