### ISSUE TITLE
Is it possible to add upload speed?

### ISSUE THREAD

**Issue by Hojakndi** [MortezaBashsiz/CFScanner#78]
Thanks for the work. What I am seeing recently is that they tend to throttle the upload speed and I am wondering whether this is the case on all CF ips or just some of them. Maybe we can add an upload column and see if that's the case?

**Comment by MortezaBashsiz** [comment]
Hi
It could be possible but needs time
Will let this issue open and will check it later

**Comment by miadabdi** [comment]
@MortezaBashsiz 
سلام 
اپراتوری مثل همراه اول سرعت آپلود رو خیلی خیلی محدود کرده و عملا با این که سرعت دانلود 20 30 40 مگابیت هست سرعت آپلود افتضاحه شاید 10 20 کیلوبایت. واقعا به تست آپلود هم نیازه.
ممنون از تلاش هاتون

**Comment by MortezaBashsiz** [comment]
Upload test is supported now on Linux version
