### ISSUE TITLE
operator detection

### ISSUE THREAD

**Issue by FarshadGhanbari** [MortezaBashsiz/CFScanner#79]
Hi, thank you very much for this scanner
I from this link:
http://bot.sudoer.net/best.cf.iran
I use it for healthy IPs, but the IR-MCI has not been updated for two days, I wanted to see how you test an IP with different operators?

**Comment by MortezaBashsiz** [comment]
We execute this script behind different operators and try to update it every day but sometimes it is a little bit difficult to update it everyday
