### ISSUE TITLE
Random range selection

### ISSUE THREAD

**Issue by hamed98** [MortezaBashsiz/CFScanner#80]
Hi
Thanks for your useful script
I think most of the times some ranges of ips are blocked and it may be time consuming to scans all blocked ranges to reach one unblocked range.
so i think it's better to add a feature to randomly select cloudflare ip ranges to scan.

**Comment by saeex2** [comment]
> Hi Thanks for your useful script I think most of the times some ranges of ips are blocked and it may be time consuming to scans all blocked ranges to reach one unblocked range. so i think it's better to add a feature to randomly select cloudflare ip ranges to scan.

that's a useful idea and much time saver 
like select 10 100 or 1000 random ips from subnet list

**Comment by MortezaBashsiz** [comment]
Hi
Since we want to be sure that the scan process is the same because it depends on the ISP and also location, I can not to that
But you can use your custom subnets as input to the script
Will close this issue
