### ISSUE TITLE
لیست آی‌پی به جای لیست ساب‌نت

### ISSUE THREAD

**Issue by pulsarice** [MortezaBashsiz/CFScanner#82]
سلام. من می‌خوام به جای ساب‌نت‌های پیش‌فرض، لیست آی‌پی‌های http://bot.sudoer.net/best.cf.iran.all رو با کانفیگ خودم تست کنم. مجبورم انتهای همه آی‌پی‌ها 32/ بذارم. خیلی کند پیش می‌ره اسکن. هرچقدر هم تعداد threadها رو زیاد می‌کنم، به نظر میاد که هر ساب‌نت جداگانه بررسی می‌شه و عملا بالا بردن تعداد تردها فایده‌ای نداره.

**Comment by xlirezx** [comment]
به نظر من هم اگر قابلیتی دیده بشه که لیست آیپی خودمون بتونیم بدیم برای تست، خیلی در زمان صرفه‌جویی میشه، اینجوری خیلی طول میکشه متاسفانه.

**Comment by MortezaBashsiz** [comment]
درود
بله حتما این مورد رو به عنوان یک فیچر در نظر میگیرم

**Comment by MortezaBashsiz** [comment]
Done

**Comment by NabiKAZ** [comment]
این برای نسخه ویندوز هم اجرا بشه مفید خواهد بود.
