### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by Adibov** [MortezaBashsiz/CFScanner#83]
Installing and managing dependencies have some overheads which will make users, not use this repository. Dockerizing would be an excellent solution to solve this problem.

In the _Dockerfile_ we can install dependencies and have some default values for the runtime variables, users will just have to change the _config_ file and run the container with the prepared docker command.

**Comment by Adibov** [comment]
Btw, if others agree on the solution, I can make a PR for this issue.

**Comment by MortezaBashsiz** [comment]
Done
