### ISSUE TITLE
اجرا بر روی ویندوز

### ISSUE THREAD

**Issue by Saeedaares** [MortezaBashsiz/CFScanner#85]
مرتضی جان در ابتدا از زحماتت تشکر میکنم،آیا امکان استفاده بر روی ویندوز وجود دارد؟

**Comment by Alirezaaraby** [comment]
You need to have a terminal in windows like 
[Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=de-de&gl=de&rtc=1) or a bash shell. ( If you have installed git on your windows you should have an app that name is `git bash` then you need to install the dependencies which are linked in the README of the project.

**Comment by MortezaBashsiz** [comment]
دیگه با داکر میتونید روی ویندوز هم اجرا کنید
