### ISSUE TITLE
OS not supported

### ISSUE THREAD

**Issue by miladj3** [MortezaBashsiz/CFScanner#86]
hi, thanks for this script
I have a problem to this script. my os is ubuntu 22.10, when i run command `bash cfFindIP.sh 8 ./config.real 100`, show me error 
`I require 'parallel' but it's not installed. Please install it and try again.
reading config ...
OS not supported only Linux or Mac`
i install parallel, but still this error

**Comment by MortezaBashsiz** [comment]
Docker image is available
So you are not depended on the OS
