### ISSUE TITLE
ارور مهمparallel eror : persing of --jobs/-j/--max-procs/-p failed. #88

### ISSUE THREAD

**Issue by armanem2** [MortezaBashsiz/CFScanner#89]
چگونگی رفع این ارور پارالل بااین ارور عملا هیچ ایپی اسکن نمیکند
سیستم : اوبونتو بیست روی ویندوز ران شده

**Comment by aliraza7926** [comment]
دوست عزیز من خیلی سر رشته زیادی ندارم ولی خب منم روی wsl2 هستم و منم مشکل مشابهی رو داشتم
توی قسمت نیازمندی های این برنامه گفته که ورژن برنامه parallel باید بیشتر از  20220515 باشه 
و خب میتونید با استفاده از دستور 
`parallel --version`
ورژنش رو چک کنید 
برای من که ورژنش کمتر بود و واسه همین به مشکل میخوردم احتمالا اگه ورژن جدیدش رو نصب کنید مشکلتون برطرف بشه

**Comment by shQaza** [comment]
چطوری میشه آپدیتش کرد من که نتوونستم

**Comment by aliraza7926** [comment]
با استفاده از مخازن پیش فرض نمیشه
فکر کنم باید به صورت دستی مخزنش رو اضافه کنید 
یا خودتون از روی سورس کامپایلش کنید

**Comment by armanem2** [comment]
خوب بگید چجوری اپدیت میشه دوستان

**Comment by armanem2** [comment]
من هرچی نت گشتم پیدا نکردم 

parallel: Error: Parsing of --jobs/-j/--max-procs/-P failed.
Usage:

parallel [options] [command [arguments]] < list_of_arguments
parallel [options] [command [arguments]] (::: arguments|:::: argfile(s))...
cat ... | parallel --pipe [options] [command [arguments]]

-j n            Run n jobs in parallel
-k              Keep same order
-X              Multiple arguments with context replace
--colsep regexp Split input on regexp for positional replacements
{} {.} {/} {/.} {#} {%} {= perl code =} Replacement strings
{3} {3.} {3/} {3/.} {=3 perl code =}    Positional replacement strings
With --plus:    {} = {+/}/{/} = {.}.{+.} = {+/}/{/.}.{+.} = {..}.{+..} =
                {+/}/{/..}.{+..} = {...}.{+...} = {+/}/{/...}.{+...}

-S sshlogin     Example: foo@server.example.com
--slf ..        Use ~/.parallel/sshloginfile as the list of sshlogins
--trc {}.bar    Shorthand for --transfer --return {}.bar --cleanup
--onall         Run the given command with argument on all sshlogins
--nonall        Run the given command with no arguments on all sshlogins

--pipe          Split stdin (standard input) to multiple jobs.
--recend str    Record end separator for --pipe.
--recstart str  Record start separator for --pipe.

GNU Parallel can do much more. See 'man parallel' for details

Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2021, August 22). GNU Parallel 20210822 ('Kabul').
  Zenodo. https://doi.org/10.5281/zenodo.5233953
