### ISSUE TITLE
دانلود نشدن خودکار فایل config.real

### ISSUE THREAD

**Issue by aliraza7926** [MortezaBashsiz/CFScanner#90]
سلام وقت بخیر 
قبلش خیلی ممنونم به خاطر وقت و زمانی که روی این پروژه میگذارید

توی اخرین اپدیت شما این ویژگی رو  اضافه کردین که فایل config.real به صورت خودکار دانلود بشه اما مشکلی که این وسط پیش میاد این هست که کد شما فقط در صورتی کار میکنه که از قبل یک conifg.real موجود باشه و اون رو اپدیت میکنه
ولی اگه پروژه رو تازه دانلود کنیم یا به هر دلیلی config.real موجود نباشه اسکریپت با پیغام 
`config file does not exist ./config.real`
متوقف میشه 
با دانش اندکی که من از bash دارم دلیلش تابع fncValidateConfig هست 
https://github.com/MortezaBashsiz/CFScanner/blob/b8e2f428c551af18591e223d513518b4a8aa4c89/scripts/cfFindIP.sh#L440-L441

ما اینجا اول fncValidateConfig  رو صدا میکنیم بعد اسکریپت اصلی رو اجرا میکنیم ولی قسمت دانلود config.real 
اینجا قرار داره
https://github.com/MortezaBashsiz/CFScanner/blob/b8e2f428c551af18591e223d513518b4a8aa4c89/scripts/cfFindIP.sh#L291-L303

و وقتی config.real وجود نداشته باشه اسکریپت اصلا به اونجا نمیرسه که بخواد  به طور خودکار این فایل رو دانلود کنه
نمیدونم هدف اصلی  این اپدیت برای این بود که فقط config.real اپدیت بشه یا اگه وجود نداره به صورت خودکار دانلود بشه و حدس میزنم مورد دوم مد نظر شماس

**Comment by MortezaBashsiz** [comment]
انجام شد
تشکل
